force-app/main/default/objects/DRC_NBC_Restricted_Product__c/DRC_NBC_Restricted_Product__c.object-meta.xml
<CustomObject>
    <label>Account Products</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Restricted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Customer_s_Product_code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_s_Product_code__c</fullName>
    <label>Customer’s Product code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Product__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Restricted_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DRC_NBC_CustomerRefrenceItems_BC_Callout.cls
public class DRC_NBC_CustomerRefrenceItems_BC_Callout {

    public static DRC_NBC_Integration_Payload.CustomerItemReferencePayload mapToPayload(
        DRC_NBC_Restricted_Product__c rp,
        String customerNumber,
        Account acc
    ) {
        DRC_NBC_Integration_Payload.CustomerItemReferencePayload payload =
            new DRC_NBC_Integration_Payload.CustomerItemReferencePayload();

        payload.Reference_Type_No   = customerNumber;
        payload.Item_No             = rp.DRC_NBC_Product__r.DRC_NBC_FG_Code__c;
        payload.Unit_of_Measure     = 'KGS';
        payload.Reference_Type      = acc.Type;
        payload.Reference_No        = rp.Name;
        payload.Reference_Type_Name = acc.Name;
        payload.Description         = rp.DRC_NBC_Customer_s_Product_code__c;
        payload.Description_2       = '';

        System.debug(LoggingLevel.DEBUG, 'MAPPED CUSTOMER ITEM REF PAYLOAD >>> ' + JSON.serialize(payload, true));

        return payload;
    }
}