force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Line_Item_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Line_Item_Endpoint__c</fullName>
    <label>BC Line Item Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_GST_Credit_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Credit_Value__c</fullName>
    <label>GST Credit Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Password__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Line_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Line_Namespace__c</fullName>
    <label>SOAP Line Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Username__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <label>FG Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD (UNIT-III)</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Sample_Order.recordType-meta.xml
<RecordType>
    <fullName>Sample_Order</fullName>
    <active>true</active>
    <label>Sample Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Discount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Discount__c</fullName>
    <label>Discount</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Packing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Quantity__c</fullName>
    <label>Packing Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Total_Price__c</fullName>
    <formula>IF(
				NOT(ISNULL(DRC_NBC_Discount__c)) ,
			 UnitPrice * Quantity * ( 100 - DRC_NBC_Discount__c)* 0.01,
				UnitPrice * Quantity
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_GST_Group_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Group_Code__c</fullName>
    <label>GST Group Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 UNIT</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>18 KG CARBOY</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS MS</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>20 KG TIN</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse_Location_Code__mdt/Warehouse_Location_Code__mdt.object-meta.xml
<CustomObject>
    <label>Warehouse Location Code</label>
    <pluralLabel>Warehouse Location Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/Warehouse_Location_Code__mdt/fields/DRC_NBC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location_Code__mdt/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DRC_NBC_LineItemCreator.cls
/**
* @File Name : DRC_NBC_LineItemCreator.cls
* @Description : Handles Creation of Line Items in Business Central using SOAP CreateMultiple
* @Author : Satish Yadav 
* @Last Modified On : April 22, 2026
**/
public class DRC_NBC_LineItemCreator {
    
    private static DRC_NBC_BC_Integration__c bcSettings = DRC_NBC_BC_Integration__c.getInstance();
    private static final String BC_LINE_ITEM_ENDPOINT   = bcSettings.DRC_NBC_BC_Line_Item_Endpoint__c;
    private static final String SOAP_LINE_NAMESPACE     = bcSettings.DRC_NBC_SOAP_Line_Namespace__c;
    private static final String GST_CREDIT_VALUE        = bcSettings.DRC_NBC_GST_Credit_Value__c;
    private static final String BC_USERNAME             = bcSettings.DRC_NBC_Username__c;
    private static final String BC_PASSWORD             = bcSettings.DRC_NBC_Password__c;
    
    public static String createLineItemsAtLineNumber(String bcOrderNo, List<OrderItem> orderItems,
                                                     Order ord, Integer startingLineNo) {
                                                         System.debug('*** CREATE Line Items at Line Number Started ***');
                                                         System.debug('BC Order Number: ' + bcOrderNo);
                                                         System.debug('Starting Line Number: ' + startingLineNo);
                                                         for (OrderItem itemOrder : orderItems) {
                                                             System.debug('Item Id: ' + itemOrder.Id);
                                                             System.debug('FG Code: ' + itemOrder.Product2.DRC_NBC_FG_Code__c);
                                                             System.debug('HSN SAC Code: ' + itemOrder.Product2.DRC_NBC_HSN_SAC_Code__c);
                                                             System.debug('GST Group Code: ' + itemOrder.Product2.DRC_NBC_GST_Group_Code__c);
                                                         }
                                                         
                                                         if (orderItems == null || orderItems.isEmpty()) {
                                                             System.debug('No product items to create');
                                                             return 'NO_ITEMS_TO_CREATE';
                                                         }
                                                         
                                                         try {
                                                             String requestBody = buildCreateMultipleSOAPRequest(bcOrderNo, orderItems, startingLineNo, ord);
                                                             String bcLocationCode = DRC_NBC_UpdateOrderAndLineItems.buildReadSOAPRequest(bcOrderNo);
                                                             
                                                             System.debug('========== LOCATION CODE CHECK (Before Line Create) ==========');
                                                        
                                                             System.debug('BC Order Location  : ' + (String.isBlank(bcLocationCode) ? '[EMPTY/NOT FOUND]' : bcLocationCode));
                                                            
                                                             
                                                             
                                                             HttpRequest req = new HttpRequest();
                                                             req.setEndpoint(BC_LINE_ITEM_ENDPOINT);
                                                             req.setMethod('POST');
                                                             req.setHeader('Content-Type', 'text/xml; charset=utf-8');
                                                             req.setHeader('SOAPAction', SOAP_LINE_NAMESPACE + ':CreateMultiple');
                                                             req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(
                                                                 Blob.valueOf(BC_USERNAME + ':' + BC_PASSWORD)
                                                             ));
                                                             System.debug(LoggingLevel.ERROR, 'SOAP Payload before callout: ' + requestBody);
                                                             debugLongString('SOAP Payload before callout', requestBody);
                                                             
                                                             req.setBody(requestBody);
                                                             req.setTimeout(120000);
                                                             
                                                             HttpResponse response = new Http().send(req); // ← CALLOUT
                                                             
                                                             System.debug('CreateMultiple Response Status: ' + response.getStatusCode());
                                                             
                                                             if (response.getStatusCode() == 200) {
                                                                 // ✅ No log here — in the middle of process
                                                                 // Final SUCCESS log written by intelligentLineItemSync after all steps pass
                                                                 System.debug('Line Items Created Successfully');
                                                                 return 'SUCCESS';
                                                                 
                                                             } else {
                                                                 // ✅ ERROR log — safe because caller (intelligentLineItemSync)
                                                                 // stops immediately after seeing FAILURE, no more callouts follow
                                                                 System.debug('ERROR: CreateMultiple failed - ' + response.getStatusCode());
                                                                 System.debug('Response Body: ' + response.getBody());
                                                                 DRC_NBC_API_Log_Handler.createApiLog(
                                                                     BC_LINE_ITEM_ENDPOINT,
                                                                     requestBody,
                                                                     response.getBody(),
                                                                     'createLineItemsAtLineNumber',
                                                                     'CreateMultiple failed: ' + response.getStatusCode(),
                                                                     response.getStatusCode(),
                                                                     null,
                                                                     'ERROR',
                                                                     ord.Id
                                                                 );
                                                                 return 'FAILURE: ' + response.getStatusCode();
                                                             }
                                                             
                                                         } catch (Exception ex) {
                                                             System.debug('*** CreateMultiple Exception: ' + ex.getMessage());
                                                             // ✅ ERROR log — exception means no more callouts, safe to DML
                                                             DRC_NBC_API_Log_Handler.createApiLog(
                                                                 BC_LINE_ITEM_ENDPOINT,
                                                                 null,
                                                                 null,
                                                                 'createLineItemsAtLineNumber',
                                                                 ex.getMessage(),
                                                                 null,
                                                                 ex.getStackTraceString(),
                                                                 'ERROR',
                                                                 ord.Id
                                                             );
                                                             return 'ERROR: ' + ex.getMessage();
                                                         }
                                                     }
    
    // ── Legacy method — kept for backward compatibility ───────────────────
    public static String createLineItems(String bcOrderNo, List<OrderItem> orderItems,
                                         Order ord, Integer startingLineCounter) {
                                             return createLineItemsAtLineNumber(bcOrderNo, orderItems, ord, startingLineCounter * 10000);
                                         }
    
    private static String buildCreateMultipleSOAPRequest(String bcOrderNo, List<OrderItem> orderItems,
                                                         Integer startingLineNo, Order ord) {
                                                             String locationCode = '';
                                                             if (ord != null && ord.DRC_NBC_Shipping_Address__r != null &&
                                                                 String.isNotBlank(ord.DRC_NBC_Warehouse__c)) {
                                                                     
                                                                     List<Warehouse_Location_Code__mdt> metaList = [
                                                                         SELECT DRC_NBC_Code__c FROM Warehouse_Location_Code__mdt
                                                                         WHERE MasterLabel = :ord.DRC_NBC_Warehouse__c
                                                                         AND DRC_NBC_Type__c = 'Warehouse Location'
                                                                         LIMIT 1
                                                                     ];
                                                                     if (!metaList.isEmpty()) {
                                                                         locationCode = metaList[0].DRC_NBC_Code__c;
                                                                         System.debug('Location_Code from metadata: ' + locationCode);
                                                                     }
                                                                 }
                                                             
                                                             String soapBody =
                                                                 '<?xml version="1.0" encoding="utf-8"?>' +
                                                                 '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
                                                                 '<soap:Body>' +
                                                                 '<CreateMultiple xmlns="' + SOAP_LINE_NAMESPACE + '">' +
                                                                 '<SalesOrderLineSalesForce_List>';
                                                             
                                                             Integer currentLineNo = startingLineNo;
                                                             
                                                             for (OrderItem item : orderItems) {
                                                                 System.debug('Creating line at: ' + currentLineNo);
                                                                 System.debug('Item Id: ' + item.Id);
                                                                 System.debug('FG Code: ' + item.Product2.DRC_NBC_FG_Code__c);
                                                                 System.debug('HSN SAC Code: ' + item.Product2.DRC_NBC_HSN_SAC_Code__c);
                                                                 System.debug('GST Group Code: ' + item.Product2.DRC_NBC_GST_Group_Code__c);
                                                                 
                                                                 Boolean isSampleOrder      = item.Order.RecordType.Name == 'Sample_Order';
                                                                 Decimal discountPercent    = item.DRC_NBC_Discount__c != null ? item.DRC_NBC_Discount__c : 0;
                                                                 Decimal totalPrice         = item.DRC_NBC_Total_Price__c != null ? item.DRC_NBC_Total_Price__c : 0;
                                                                 Decimal lineDiscountAmount = (totalPrice * discountPercent) / 100;
                                                                 
                                                                 if (isSampleOrder) {
                                                                     totalPrice         = 0;
                                                                     lineDiscountAmount = 0;
                                                                 }
                                                                 
                                                                 soapBody +=
                                                                     '<SalesOrderLineSalesForce>' +
                                                                     '<Document_Type>Order</Document_Type>' +
                                                                     '<Document_No>' + escapeXml(bcOrderNo) + '</Document_No>' +
                                                                     '<Line_No>' + currentLineNo + '</Line_No>' +
                                                                     '<Type>Item</Type>' +
                                                                     '<No>' + escapeXml(item.Product2.DRC_NBC_FG_Code__c) + '</No>' +
                                                                     '<Customer_item_no>'      + escapeXml(item.Product2.DRC_NBC_FG_Code__c) + '</Customer_item_no>' +
                                                                     '<Description>' + escapeXml(item.Description != null ? item.Description : '') + '</Description>' +
                                                                     '<Location_Code>' + escapeXml(locationCode) + '</Location_Code>' +
                                                                     '<Quantity>' + (item.Quantity != null ? item.Quantity : 0) + '</Quantity>' +
                                                                     '<Unit_of_Measure_Code>KGS</Unit_of_Measure_Code>' +
                                                                     '<Unit_Price>' + (isSampleOrder ? 0 : (item.UnitPrice != null ? item.UnitPrice : 0)) + '</Unit_Price>' +
                                                                     '<Line_Amount>' + totalPrice + '</Line_Amount>' +
                                                                     '<Line_Discount_Percent>' + discountPercent + '</Line_Discount_Percent>' +
                                                                     '<Line_Discount_Amount>' + lineDiscountAmount + '</Line_Discount_Amount>' +
                                                                     '<Inv_Discount_Amount>0</Inv_Discount_Amount>' +
                                                                     '<GST_Credit>' + GST_CREDIT_VALUE + '</GST_Credit>' +
                                                                     '<GST_Group_Code>' + escapeXml(item.Product2.DRC_NBC_GST_Group_Code__c) + '</GST_Group_Code>' +
                                                                     '<HSN_SAC_Code>' + escapeXml(item.Product2.DRC_NBC_HSN_SAC_Code__c) + '</HSN_SAC_Code>' +
                                                                     '<No_of_Pkg_for_Qty>' + (item.DRC_NBC_Packing_Quantity__c != null ? String.valueOf(item.Quantity) : '0') + '</No_of_Pkg_for_Qty>' +
                                                                     '<Packing_Details>' + escapeXml(item.DRC_NBC_Packing_Size__c != null ? item.DRC_NBC_Packing_Size__c : '') + '</Packing_Details>' +
                                                                     '</SalesOrderLineSalesForce>';
                                                                 
                                                                 currentLineNo += 10000;
                                                             }
                                                             
                                                             soapBody +=
                                                                 '</SalesOrderLineSalesForce_List>' +
                                                                 '</CreateMultiple>' +
                                                                 '</soap:Body>' +
                                                                 '</soap:Envelope>';
                                                             
                                                             return soapBody;
                                                         }
    
    private static String escapeXml(String value) {
        if (String.isBlank(value)) return '';
        return value.escapeXml();
    }
    private static void debugLongString(String label, String text) {
        if (String.isBlank(text)) {
            System.debug(LoggingLevel.ERROR, label + ': [EMPTY]');
            return;
        }
        
        Integer chunkSize = 3000;
        Integer len = text.length();
        
        for (Integer i = 0; i < len; i += chunkSize) {
            Integer endIdx = Math.min(i + chunkSize, len);
            System.debug(LoggingLevel.ERROR,
                         label + ' [' + i + '-' + (endIdx - 1) + ']: ' + text.substring(i, endIdx)
                        );
        }
    }
}