force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <label>FG Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Other_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Other_Tax_Amount__c</fullName>
    <label>Other Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_TCS_Amount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_TCS_Amount__c</fullName>
    <label>TCS Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Inco_terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_terms__c</fullName>
    <label>Inco terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Other_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Other_Tax_Amount__c</fullName>
    <label>Other Charges  Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Payemnt_Term__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payemnt_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_TCS_Amount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_TCS_Amount__c</fullName>
    <label>TCS Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_Generate_Order_ControllerTest.cls
@isTest
public class DRC_NBC_Generate_Order_ControllerTest {

    // ─── @testSetup: Create all shared data once ──────────────────────────────
    @testSetup
    static void setupTestData() {
        // Account with billing address
        Account acc = new Account(
            Name               = 'Test Account',
            BillingStreet      = '123 Main St',
            BillingCity        = 'Mumbai',
            BillingState       = 'Maharashtra',
            BillingPostalCode  = '400001',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN',
            DRC_NBC_Consignee_Bank_Name__c           = 'Test Bank',
            DRC_NBC_Consignee_Bank_Account_Number__c = '1234567890',
            DRC_NBC_Consignee_Bank_IFSC_Code__c      = 'TEST0001234',
            DRC_NBC_Consignee_Bank_Address__c        = 'Bank Street, Mumbai'
        );
        insert acc;

        // Contacts (with emails so createOrder validation passes)
        Contact billTo = new Contact(
            FirstName   = 'Bill',
            LastName    = 'To',
            AccountId   = acc.Id,
            Email       = 'billto@test.com'
        );
        Contact shipTo = new Contact(
            FirstName   = 'Ship',
            LastName    = 'To',
            AccountId   = acc.Id,
            Email       = 'shipto@test.com'
        );
        insert new List<Contact>{ billTo, shipTo };

        // Opportunity
        Opportunity opp = new Opportunity(
            Name        = 'Test Opp',
            AccountId   = acc.Id,
            StageName   = 'Prospecting',
            CloseDate   = Date.today().addDays(30),
            CurrencyIsoCode = 'USD'
        );
        insert opp;

        // Pricebook
        Id standardPbId = Test.getStandardPricebookId();

        // Product
        Product2 prod = new Product2(
            Name                    = 'Test Product',
            IsActive                = true,
            Family                  = 'Test',
            QuantityUnitOfMeasure   = 'Each',
            DRC_NBC_FG_Code__c      = 'FG001',
            DRC_NBC_HSN_SAC_Code__c = 'HSN001'
        );
        insert prod;

        // Standard PricebookEntry
        PricebookEntry standardPbe = new PricebookEntry(
            Pricebook2Id    = standardPbId,
            Product2Id      = prod.Id,
            UnitPrice       = 100,
            IsActive        = true,
            CurrencyIsoCode = 'USD'
        );
        insert standardPbe;

        // Quote
        Quote quote = new Quote(
            Name                    = 'Test Quote',
            OpportunityId           = opp.Id,
            DRC_NBC_Type__c         = 'Domestic',
            DRC_NBC_Payemnt_Term__c = '100',
            DRC_NBC_Inco_terms__c   = 'Charges Collect (CC)',
            DRC_NBC_TCS_Amount__c   = 100,
            DRC_NBC_Other_Tax_Amount__c = 50,
            Pricebook2Id            = standardPbId,
            Status                  = 'Draft'
        );
        insert quote;

        // QuoteLineItem
        QuoteLineItem qli = new QuoteLineItem(
            QuoteId             = quote.Id,
            Product2Id          = prod.Id,
            PricebookEntryId    = standardPbe.Id,
            Quantity            = 5,
            UnitPrice           = 100,
            Description         = 'Test QLI',
            DRC_NBC_Packing_Size__c     = 'AL 1 KG',
            DRC_NBC_Packing_Qauntity__c = '2'
        );
        insert qli;

        // Shipping Address
        DRC_NBC_Addresses__c addr = new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c              = acc.Id,
            DRC_NBC_Type__c                 = 'Shipping',
            DRC_NBC_Address__Street__s      = '456 Ship St',
            DRC_NBC_Address__City__s        = 'Pune',
            DRC_NBC_Address__StateCode__s   = 'MH',
            DRC_NBC_Address__PostalCode__s  = '411001',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Warehouse__c            = 'CFS - JNPT'
        );
        insert addr;
    }

    // ─── Utility: build a test Order object ───────────────────────────────────
    private static Order buildTestOrder(
        Id accountId, Id pricebookId, Id billToId, Id shipToId,
        Id opportunityId, Id shippingAddrId
    ) {
        Order ord = new Order(
            AccountId               = accountId,
            EffectiveDate           = Date.today(),
            Status                  = 'Draft',
            CurrencyIsoCode         = 'USD',
            Pricebook2Id            = pricebookId,
            Type                    = 'Domestic',
            BillToContactId         = billToId,
            ShipToContactId         = shipToId,
            DRC_NBC_Type__c         = 'Domestic',
            DRC_NBC_Shipping_Address__c = shippingAddrId
        );
        return ord;
    }

    // ─── Utility: build DRC_NBC_OrderItemWrapper ──────────────────────────────
    private static DRC_NBC_OrderItemWrapper buildOrderItemWrapper(
        Id product2Id, Id pbeId, Decimal qty, Decimal price
    ) {
        DRC_NBC_OrderItemWrapper w = new DRC_NBC_OrderItemWrapper();
        w.Product2Id        = product2Id;
        w.PriceBookEntryId  = pbeId;
        w.Quantity          = qty;
        w.UnitPrice         = price;
        w.Description       = 'Test Item';
        w.UOM               = 'Each';
        w.DRC_NBC_Packing_Size     = 'AL 1 KG';
        w.DRC_NBC_Packing_Quantity = '2';
        return w;
    }

    // ─── getOrderRecordTypes ──────────────────────────────────────────────────

    @isTest
    static void testGetOrderRecordTypes() {
        Test.startTest();
        List<DRC_NBC_Generate_Order_Controller.OptionsWrapper> result =
            DRC_NBC_Generate_Order_Controller.getOrderRecordTypes();
        Test.stopTest();
        // Master record type is excluded; result may be empty in test orgs with only Master
        System.assertNotEquals(null, result, 'Result should not be null');
    }

    // ─── getOrderTypes ────────────────────────────────────────────────────────

    @isTest
    static void testGetOrderTypes() {
        Test.startTest();
        List<DRC_NBC_Generate_Order_Controller.OptionsWrapper> result =
            DRC_NBC_Generate_Order_Controller.getOrderTypes();
        Test.stopTest();
        System.assertNotEquals(null, result, 'Order types should not be null');
        System.assert(!result.isEmpty(), 'Order types picklist should have values');
    }

    // ─── getDefaultValues ─────────────────────────────────────────────────────

    @isTest
    static void testGetDefaultValues() {
        Quote quote = [SELECT Id FROM Quote LIMIT 1];
        Test.startTest();
        DRC_NBC_Generate_Order_Controller.OrderDefaults defaults =
            DRC_NBC_Generate_Order_Controller.getDefaultValues(quote.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetDefaultValuesInvalidQuote() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Order_Controller.getDefaultValues('invalidId000000');
            System.assert(false, 'Exception expected for invalid quote ID');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'Exception message should exist');
        }
        Test.stopTest();
    }

    // ─── makeOrderWrapper / getRelatedQLIS ────────────────────────────────────

    @isTest
    static void testMakeOrderWrapper() {
        Quote quote = [SELECT Id FROM Quote LIMIT 1];
        Test.startTest();
        List<DRC_NBC_OrderItemWrapper> items =
            DRC_NBC_Generate_Order_Controller.makeOrderWrapper(quote.Id);
        Test.stopTest();
    }

    @isTest
    static void testMakeOrderWrapperNoQLIs() {
        // Quote with no line items
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Id standardPbId = Test.getStandardPricebookId();
        Quote emptyQuote = new Quote(
            Name          = 'Empty Quote',
            OpportunityId = opp.Id,
            Status        = 'Draft',
            Pricebook2Id  = standardPbId,
            DRC_NBC_Type__c = 'Domestic'
        );
        insert emptyQuote;

        Test.startTest();
    }

    // ─── makePicklistOptions ──────────────────────────────────────────────────

    @isTest
    static void testMakePicklistOptions() {
        Test.startTest();
        DRC_NBC_Generate_Order_Controller.PicklistOptionsWrapper result =
            DRC_NBC_Generate_Order_Controller.makePicklistOptions();
        Test.stopTest();
    }

    // ─── createOrder - Success ────────────────────────────────────────────────

    @isTest
    static void testCreateOrderSuccess() {
        Account acc      = [SELECT Id FROM Account LIMIT 1];
        Quote quote      = [SELECT Id, Pricebook2Id FROM Quote LIMIT 1];
        Contact billTo   = [SELECT Id FROM Contact WHERE FirstName = 'Bill' LIMIT 1];
        Contact shipTo   = [SELECT Id FROM Contact WHERE FirstName = 'Ship' LIMIT 1];
        Product2 prod    = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
        DRC_NBC_Addresses__c addr = [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];

        Order orderObj = buildTestOrder(acc.Id, quote.Pricebook2Id, billTo.Id, shipTo.Id, null, addr.Id);

        DRC_NBC_OrderItemWrapper w = buildOrderItemWrapper(prod.Id, pbe.Id, 3, 100);

        Test.startTest();
        String resultJson = DRC_NBC_Generate_Order_Controller.createOrder(
            orderObj, new List<DRC_NBC_OrderItemWrapper>{ w }, quote.Id
        );
        Test.stopTest();
    }

    // ─── createOrder - Missing email on contact ───────────────────────────────

    @isTest
    static void testCreateOrderMissingEmail() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Quote quote = [SELECT Id, Pricebook2Id FROM Quote LIMIT 1];
        DRC_NBC_Addresses__c addr = [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];

        // Create contacts WITHOUT emails
        Contact noEmailBill = new Contact(FirstName = 'NoEmail', LastName = 'Bill', AccountId = acc.Id);
        Contact noEmailShip = new Contact(FirstName = 'NoEmail', LastName = 'Ship', AccountId = acc.Id);
        insert new List<Contact>{ noEmailBill, noEmailShip };

        Order orderObj = buildTestOrder(acc.Id, quote.Pricebook2Id, noEmailBill.Id, noEmailShip.Id, null, addr.Id);
        Product2 prod  = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry LIMIT 1];
        DRC_NBC_OrderItemWrapper w = buildOrderItemWrapper(prod.Id, pbe.Id, 1, 100);

        Test.startTest();
        String resultJson = DRC_NBC_Generate_Order_Controller.createOrder(
            orderObj, new List<DRC_NBC_OrderItemWrapper>{ w }, quote.Id
        );
        Test.stopTest();
    }

    // ─── createOrder - Missing PricebookEntry ─────────────────────────────────

    @isTest
    static void testCreateOrderMissingPricebookEntry() {
        Account acc    = [SELECT Id FROM Account LIMIT 1];
        Quote quote    = [SELECT Id, Pricebook2Id FROM Quote LIMIT 1];
        Contact billTo = [SELECT Id FROM Contact WHERE FirstName = 'Bill' LIMIT 1];
        Contact shipTo = [SELECT Id FROM Contact WHERE FirstName = 'Ship' LIMIT 1];
        Product2 prod  = [SELECT Id FROM Product2 LIMIT 1];
        DRC_NBC_Addresses__c addr = [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];

        Order orderObj = buildTestOrder(acc.Id, quote.Pricebook2Id, billTo.Id, shipTo.Id, null, addr.Id);

        // Wrapper with no PricebookEntryId — forces missing PBE branch
        DRC_NBC_OrderItemWrapper w = new DRC_NBC_OrderItemWrapper();
        w.Product2Id       = prod.Id;
        w.PriceBookEntryId = null; // intentionally blank
        w.Quantity         = 1;
        w.UnitPrice        = 100;
        w.Description      = 'Missing PBE item';
        w.UOM              = 'Each';

        // Use a custom pricebook that has no PBE for the product
        Pricebook2 emptyPb = new Pricebook2(Name = 'Empty PB', IsActive = true);
        insert emptyPb;
        orderObj.Pricebook2Id = emptyPb.Id;

        Test.startTest();
        String resultJson = DRC_NBC_Generate_Order_Controller.createOrder(
            orderObj, new List<DRC_NBC_OrderItemWrapper>{ w }, quote.Id
        );
        Test.stopTest();

        Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(resultJson);
        System.assertEquals(false, result.get('success'), 'Should fail due to missing PBE');
        System.assert(
            ((String) result.get('error')).contains('Missing PricebookEntry') ||
            ((String) result.get('error')).contains('No valid Order Items'),
            'Error should mention missing PBE or no valid items: ' + result.get('error')
        );
    }

    // ─── createOrder - Empty order items list ─────────────────────────────────

    @isTest
    static void testCreateOrderNoValidItems() {
        Account acc    = [SELECT Id FROM Account LIMIT 1];
        Quote quote    = [SELECT Id, Pricebook2Id FROM Quote LIMIT 1];
        Contact billTo = [SELECT Id FROM Contact WHERE FirstName = 'Bill' LIMIT 1];
        Contact shipTo = [SELECT Id FROM Contact WHERE FirstName = 'Ship' LIMIT 1];
        DRC_NBC_Addresses__c addr = [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];

        Order orderObj = buildTestOrder(acc.Id, quote.Pricebook2Id, billTo.Id, shipTo.Id, null, addr.Id);

        // Wrapper with blank Product2Id — gets skipped → no valid items
        DRC_NBC_OrderItemWrapper w = new DRC_NBC_OrderItemWrapper();
        w.Product2Id = '';
        w.Quantity   = 1;
        w.UnitPrice  = 100;

        Test.startTest();
        String resultJson = DRC_NBC_Generate_Order_Controller.createOrder(
            orderObj, new List<DRC_NBC_OrderItemWrapper>{ w }, quote.Id
        );
        Test.stopTest();

        Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(resultJson);
        System.assertEquals(false, result.get('success'), 'Should fail with no valid items');
        System.assert(
            ((String) result.get('error')).contains('No valid Order Items'),
            'Error should mention no valid items: ' + result.get('error')
        );
    }

    // ─── createOrder - No shipping address (null branch) ─────────────────────

    @isTest
    static void testCreateOrderNoShippingAddress() {
        Account acc    = [SELECT Id FROM Account LIMIT 1];
        Quote quote    = [SELECT Id, Pricebook2Id FROM Quote LIMIT 1];
        Contact billTo = [SELECT Id FROM Contact WHERE FirstName = 'Bill' LIMIT 1];
        Contact shipTo = [SELECT Id FROM Contact WHERE FirstName = 'Ship' LIMIT 1];
        Product2 prod  = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];

        // Order with no shipping address
        Order orderObj = buildTestOrder(acc.Id, quote.Pricebook2Id, billTo.Id, shipTo.Id, null, null);
        orderObj.DRC_NBC_Shipping_Address__c = null;

        DRC_NBC_OrderItemWrapper w = buildOrderItemWrapper(prod.Id, pbe.Id, 2, 100);

        Test.startTest();
        String resultJson = DRC_NBC_Generate_Order_Controller.createOrder(
            orderObj, new List<DRC_NBC_OrderItemWrapper>{ w }, quote.Id
        );
        Test.stopTest();
    }

    // ─── fieldPicklistValue ───────────────────────────────────────────────────

    @isTest
    static void testFieldPicklistValue() {
        Test.startTest();
        // Test via getOrderTypes which internally calls fieldPicklistValue on DRC_NBC_Type__c
        List<DRC_NBC_Generate_Order_Controller.OptionsWrapper> options =
            DRC_NBC_Generate_Order_Controller.getOrderTypes();
        Test.stopTest();
    }

    // ─── getRelatedQLIS ───────────────────────────────────────────────────────

    @isTest
    static void testGetRelatedQLIS() {
        Quote quote = [SELECT Id FROM Quote LIMIT 1];
        Test.startTest();
        List<QuoteLineItem> qlis = DRC_NBC_Generate_Order_Controller.getRelatedQLIS(quote.Id);
        Test.stopTest();
    }
}