force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NBC_DRC_Account_DRC_Code__c.field-meta.xml
<CustomField>
    <fullName>NBC_DRC_Account_DRC_Code__c</fullName>
    <externalId>true</externalId>
    <label>Account DRC Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_KIND_OF_PKG__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_KIND_OF_PKG__c</fullName>
    <label>KIND OF PKG</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IBC (900 KGS)</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
            <value>
                <fullName>250 GRAMS AL</fullName>
            </value>
            <value>
                <fullName>250 GRAMS PAPER</fullName>
            </value>
            <value>
                <fullName>250 KGS SS</fullName>
            </value>
            <value>
                <fullName>30 KGS PAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Inco_terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_terms__c</fullName>
    <label>Inco terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Payemnt_Term__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payemnt_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_DomesticPDFControllerTest.cls
/**
* @File Name : DRC_NBC_DomesticQuotationPDFControllerTest.cls
* @Description : Test class for DRC_NBC_DomesticQuotationPDFController
*/
@isTest
private class DRC_NBC_DomesticPDFControllerTest {
    
    // ─── Test Data Setup ──────────────────────────────────────────────────────
    
    @TestSetup
    static void setupTestData() {
        // Account
        Account acc = new Account(
            Name = 'Test Account',
            AccountNumber = 'CUST001',
            NBC_DRC_Account_DRC_Code__c = 'DRC-CODE-001',
            CurrencyIsoCode = 'INR',
            Phone = '1234567890',
            DRC_NBC_PAN_No__c = 'AWVPY9594J',
            DRC_NBC_GST_Number__c = '27AWVPY9594J1ZY',
            DRC_NBC_Payment_Term_Code__c = '10 DAYS',
            DRC_NBC_Account_Email_Email__c = 'test@example.com',
            BillingStreet = '123 Street',
            BillingCity = 'City',
            BillingCountry = 'India',
            BillingCountryCode = 'IN',
            BillingPostalCode = '462002',
            BillingState = 'Maharashtra',
            BillingStateCode = 'MH',
            DRC_NBC_Volume__c = 70, 
            DRC_NBC_Credit_Limit__c = 123456787,
            DRC_NBC_Value__c = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c = 'Punjab National bank',
            Industry = 'Chemicals Construction',
            Type = 'Analyst'
        );
        insert acc;
        
        // Contact
        Contact con = new Contact(
            FirstName  = 'Test',
            LastName   = 'Contact',
            AccountId  = acc.Id
        );
        insert con;
        
        // Opportunity (required to create Quote)
        Opportunity opp = new Opportunity(
            Name            = 'Test Opportunity',
            AccountId       = acc.Id,
            StageName       = 'Prospecting',
            CloseDate       = Date.today().addDays(30)
        );
        insert opp;
        
        // Product
        Product2 prod = new Product2(
            Name                        = 'Test Product',
            IsActive                    = true,
            QuantityUnitOfMeasure       = 'KG',
            DRC_NBC_HSN_SAC_Code__c     = 'HSN001',
            DRC_NBC_KIND_OF_PKG__c      = 'Box',
            Description                 = 'Test product description'
        );
        insert prod;
        
        // Pricebook entry
        Id stdPbId = Test.getStandardPricebookId();
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = stdPbId,
            Product2Id   = prod.Id,
            UnitPrice    = 500,
            IsActive     = true
        );
        insert pbe;
        
        // Domestic Quote — no sequence number yet → triggers assignQuoteSequenceNumber Domestic path
        Quote domesticQuote = new Quote(
            Name                                    = 'Domestic Test Quote',
            OpportunityId                           = opp.Id,
            Pricebook2Id                            = stdPbId,
            ContactId                               = con.Id,
            Status                                  = 'Draft',
            ExpirationDate                          = Date.today().addDays(30),
            BillingStreet                           = '123 Test Street',
            BillingCity                             = 'Indore',
            BillingState                            = 'Madhya Pradesh',
            BillingCountry                          = 'India',
            BillingPostalCode                       = '452001',
            ShippingStreet                          = '456 Ship Street',
            ShippingCity                            = 'Mumbai',
            ShippingState                           = 'Maharashtra',
            ShippingPostalCode                      = '400001',
            ShippingCountry                         = 'India',
            CurrencyISOCode                         = 'INR',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Payemnt_Term__c                 = '100',
            DRC_NBC_Inco_terms__c                   = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c             = 50,
            DRC_NBC_TCS_Amount__c                   = 25,
            DRC_NBC_Special_Requirements__c         = 'Requirement one. Requirement two. Requirement three.',
            DRC_NBC_Import_Starting_Sequence__c     = null
        );
        insert domesticQuote;
        
        // Quote Line Item for Domestic Quote
        QuoteLineItem qliDomestic = new QuoteLineItem(
            QuoteId         = domesticQuote.Id,
            Product2Id      = prod.Id,
            PricebookEntryId= pbe.Id,
            Quantity        = 2,
            UnitPrice       = 500,
            DRC_NBC_Unit_Of_Measurement__c = 'KGS'
        );
        insert qliDomestic;
        
        // Export Quote — no sequence number yet → triggers assignQuoteSequenceNumber Export path
        Quote exportQuote = new Quote(
            Name                                        = 'Export Test Quote',
            OpportunityId                               = opp.Id,
            Pricebook2Id                                = stdPbId,
            ContactId                                   = con.Id,
            Status                                      = 'Draft',
            ExpirationDate                              = Date.today().addDays(30),
            BillingStreet                               = '123 Test Street',
            BillingCity                                 = 'Indore',
            BillingState                                = 'Madhya Pradesh',
            BillingCountry                              = 'India',
            BillingPostalCode                           = '452001',
            ShippingStreet                              = '789 Export Street',
            ShippingCity                                = 'Chennai',
            ShippingState                               = 'Tamil Nadu',
            ShippingPostalCode                          = '600001',
            ShippingCountry                             = 'India',
            CurrencyISOCode                             = 'INR',
            DRC_NBC_Type__c                             = 'Export',
            DRC_NBC_Payemnt_Term__c                     = '100',
            DRC_NBC_Inco_terms__c                       = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c                 = 30,
            DRC_NBC_TCS_Amount__c                       = 10,
            DRC_NBC_Special_Requirements__c             = 'Export requirement one. Export requirement two.',
            DRC_NBC_Invoice_Export_Sequence_Number__c   = null
        );
        insert exportQuote;
        
        // Quote Line Item for Export Quote
        QuoteLineItem qliExport = new QuoteLineItem(
            QuoteId         = exportQuote.Id,
            Product2Id      = prod.Id,
            PricebookEntryId= pbe.Id,
            Quantity        = 2,
            UnitPrice       = 500,
            DRC_NBC_Unit_Of_Measurement__c = 'KGS'
        );
        insert qliExport;
        
        // Domestic Quote — sequence already set → assignQuoteSequenceNumber returns null
        Quote domesticQuoteSeqSet = new Quote(
            Name                                    = 'Domestic Quote Seq Set',
            OpportunityId                           = opp.Id,
            Pricebook2Id                            = stdPbId,
            ContactId                               = con.Id,
            Status                                  = 'Draft',
            ExpirationDate                          = Date.today().addDays(30),
            BillingStreet                           = '123 Test Street',
            BillingCity                             = 'Indore',
            BillingState                            = 'Madhya Pradesh',
            BillingCountry                          = 'India',
            BillingPostalCode                       = '452001',
            ShippingStreet                          = '456 Ship Street',
            ShippingCity                            = 'Mumbai',
            ShippingState                           = 'Maharashtra',
            ShippingPostalCode                      = '400001',
            ShippingCountry                         = 'India',
            CurrencyISOCode                         = 'INR',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Payemnt_Term__c                 = '100',
            DRC_NBC_Inco_terms__c                   = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c             = 0,
            DRC_NBC_TCS_Amount__c                   = 0,
            DRC_NBC_Special_Requirements__c         = null,  // null → covers blank specialInstructions path
            DRC_NBC_Import_Starting_Sequence__c     = 999    // already set → assignQuoteSequenceNumber returns null
        );
        insert domesticQuoteSeqSet;
        
        // Export Quote — sequence already set → assignQuoteSequenceNumber returns null
        Quote exportQuoteSeqSet = new Quote(
            Name                                        = 'Export Quote Seq Set',
            OpportunityId                               = opp.Id,
            Pricebook2Id                                = stdPbId,
            ContactId                                   = con.Id,
            Status                                      = 'Draft',
            ExpirationDate                              = Date.today().addDays(30),
            BillingStreet                               = '123 Test Street',
            BillingCity                                 = 'Indore',
            BillingState                                = 'Madhya Pradesh',
            BillingCountry                              = 'India',
            BillingPostalCode                           = '452001',
            ShippingStreet                              = '789 Export Street',
            ShippingCity                                = 'Chennai',
            ShippingState                               = 'Tamil Nadu',
            ShippingPostalCode                          = '600001',
            ShippingCountry                             = 'India',
            CurrencyISOCode                             = 'INR',
            DRC_NBC_Type__c                             = 'Export',
            DRC_NBC_Payemnt_Term__c                     = '100',
            DRC_NBC_Inco_terms__c                       = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c                 = 0,
            DRC_NBC_TCS_Amount__c                       = 0,
            DRC_NBC_Special_Requirements__c             = null,   // null → covers blank path
            DRC_NBC_Invoice_Export_Sequence_Number__c   = 999     // already set → returns null
        );
        insert exportQuoteSeqSet;
    }
    
    // ── Helpers ───────────────────────────────────────────────────────────────
    
    private static Quote getDomesticQuote() {
        return [SELECT Id FROM Quote WHERE Name = 'Domestic Test Quote' LIMIT 1];
    }
    
    private static Quote getExportQuote() {
        return [SELECT Id FROM Quote WHERE Name = 'Export Test Quote' LIMIT 1];
    }
    
    private static Quote getDomesticQuoteSeqSet() {
        return [SELECT Id FROM Quote WHERE Name = 'Domestic Quote Seq Set' LIMIT 1];
    }
    
    private static Quote getExportQuoteSeqSet() {
        return [SELECT Id FROM Quote WHERE Name = 'Export Quote Seq Set' LIMIT 1];
    }
    
    private static ApexPages.StandardController buildController(Id quoteId) {
        Quote q = new Quote(Id = quoteId);
        return new ApexPages.StandardController(q);
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 1 — Domestic Quote, no sequence set
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testConstructor_DomesticQuote_NoSequence() {
        Quote q = getDomesticQuote();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 2 — Export Quote, no sequence set
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testConstructor_ExportQuote_NoSequence() {
        Quote q = getExportQuote();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 3 — Domestic Quote, sequence already set
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testConstructor_DomesticQuote_SequenceAlreadySet_NullSpecialReq() {
        Quote q = getDomesticQuoteSeqSet();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 4 — Export Quote, sequence already set
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testConstructor_ExportQuote_SequenceAlreadySet_NullSpecialReq() {
        Quote q = getExportQuoteSeqSet();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 5 — getFormattedDate with a valid Date
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testGetFormattedDate_NonNullDate() {
        Quote q = getDomesticQuote();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        String result = ctrl.getFormattedDate(Date.today());
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 6 — getFormattedDate with null
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testGetFormattedDate_NullDate() {
        Quote q = getDomesticQuote();
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(q.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        String result = ctrl.getFormattedDate(null);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 7 — calculateAmounts with all null tax fields
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testCalculateAmounts_AllNullTaxFields() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Id stdPbId = Test.getStandardPricebookId();
        
        Quote nullTaxQuote = new Quote(
            Name                                    = 'Null Tax Quote',
            OpportunityId                           = opp.Id,
            Pricebook2Id                            = stdPbId,
            ContactId                               = con.Id,
            Status                                  = 'Draft',
            ExpirationDate                          = Date.today().addDays(30),
            BillingStreet                           = '123 Test Street',
            BillingCity                             = 'Indore',
            BillingState                            = 'Madhya Pradesh',
            BillingCountry                          = 'India',
            BillingPostalCode                       = '452001',
            CurrencyISOCode                         = 'INR',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Payemnt_Term__c                 = '100',
            DRC_NBC_Inco_terms__c                   = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c             = null,
            DRC_NBC_TCS_Amount__c                   = null,
            DRC_NBC_Special_Requirements__c         = null,
            DRC_NBC_Import_Starting_Sequence__c     = 1000
        );
        insert nullTaxQuote;
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(nullTaxQuote.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 8 — Special Requirements with newline and carriage return characters
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testSpecialRequirements_WithNewlinesAndCarriageReturns() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Id stdPbId = Test.getStandardPricebookId();
        
        Quote newlineQuote = new Quote(
            Name                                    = 'Newline Special Req Quote',
            OpportunityId                           = opp.Id,
            Pricebook2Id                            = stdPbId,
            ContactId                               = con.Id,
            Status                                  = 'Draft',
            ExpirationDate                          = Date.today().addDays(30),
            BillingStreet                           = '123 Test Street',
            BillingCity                             = 'Indore',
            BillingState                            = 'Madhya Pradesh',
            BillingCountry                          = 'India',
            BillingPostalCode                       = '452001',
            CurrencyISOCode                         = 'INR',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Payemnt_Term__c                 = '100',
            DRC_NBC_Inco_terms__c                   = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c             = 0,
            DRC_NBC_TCS_Amount__c                   = 0,
            DRC_NBC_Special_Requirements__c         = 'Line one\nLine two\rLine three. Final point.',
            DRC_NBC_Import_Starting_Sequence__c     = 1001
        );
        insert newlineQuote;
        
        Test.startTest();
        ApexPages.StandardController sc = buildController(newlineQuote.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
    
    // ═══════════════════════════════════════════════════════════════════════════
    // Test 9 — Domestic Quote with multiple line items
    // ═══════════════════════════════════════════════════════════════════════════
    
    @isTest
    static void testCalculateAmounts_MultipleLineItems() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Id stdPbId = Test.getStandardPricebookId();
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :prod.Id LIMIT 1];
        
        Quote multiLineQuote = new Quote(
            Name                                    = 'Multi Line Quote',
            OpportunityId                           = opp.Id,
            Pricebook2Id                            = stdPbId,
            ContactId                               = con.Id,
            Status                                  = 'Draft',
            ExpirationDate                          = Date.today().addDays(30),
            BillingStreet                           = '123 Test Street',
            BillingCity                             = 'Indore',
            BillingState                            = 'Madhya Pradesh',
            BillingCountry                          = 'India',
            BillingPostalCode                       = '452001',
            CurrencyISOCode                         = 'INR',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Payemnt_Term__c                 = '100',
            DRC_NBC_Inco_terms__c                   = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Other_Tax_Amount__c             = 20,
            DRC_NBC_TCS_Amount__c                   = 10,
            DRC_NBC_Special_Requirements__c         = 'Req A. Req B.',
            DRC_NBC_Import_Starting_Sequence__c     = 1002
        );
        insert multiLineQuote;
        
        // Two line items → subtotal loop iterates twice
        insert new List<QuoteLineItem>{
            new QuoteLineItem(
                QuoteId          = multiLineQuote.Id,
                Product2Id       = prod.Id,
                PricebookEntryId = pbe.Id,
                Quantity         = 2,
                UnitPrice        = 500,
                DRC_NBC_Unit_Of_Measurement__c = 'KGS'
            ),
                new QuoteLineItem(
                    QuoteId          = multiLineQuote.Id,
                    Product2Id       = prod.Id,
                    PricebookEntryId = pbe.Id,
                    Quantity         = 1,
                    UnitPrice        = 500,
                    DRC_NBC_Unit_Of_Measurement__c = 'KGS'
                )
                };
                    
        Test.startTest();
        ApexPages.StandardController sc = buildController(multiLineQuote.Id);
        DRC_NBC_DomesticQuotationPDFController ctrl =
            new DRC_NBC_DomesticQuotationPDFController(sc);
        Test.stopTest();
    }
}