force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <formula>CASE(
TEXT(DRC_NBC_Payment_Terms_Description__c),

&quot;PDC 90 days&quot;, &quot;PDC90&quot;,
&quot;PDC 60 days&quot;, &quot;PDC60&quot;,
&quot;PDC 45 days&quot;, &quot;PDC45&quot;,
&quot;PDC 30 days&quot;, &quot;PDC30&quot;,

&quot;Irrevocable LC at sight&quot;, &quot;IRRELC&quot;,
&quot;Irrevocable LC 90 days&quot;, &quot;IRRLC90&quot;,
&quot;Irrevocable LC 60 days&quot;, &quot;IRRLC60&quot;,
&quot;Irrevocable LC 45 days&quot;, &quot;IRRLC45&quot;,
&quot;Irrevocable LC 30 days&quot;, &quot;IRRLC30&quot;,

&quot;Free sample&quot;, &quot;FOC&quot;,

&quot;DP AT SIGHT&quot;, &quot;DPSIGHT&quot;,
&quot;DP 90 days&quot;, &quot;DP90&quot;,
&quot;DP 60 days&quot;, &quot;DP60&quot;,
&quot;DP 30 days&quot;, &quot;DP30&quot;,

&quot;DA 90 days&quot;, &quot;DA90&quot;,
&quot;DA 60 days&quot;, &quot;DA60&quot;,
&quot;DA 45 days&quot;, &quot;DA45&quot;,
&quot;DA 30 days&quot;, &quot;DA30&quot;,

&quot;Bond transfer&quot;, &quot;BONTRN&quot;,

&quot;BL 90 days&quot;, &quot;BL90&quot;,
&quot;BL 75 days&quot;, &quot;BL75&quot;,
&quot;BL 60 days&quot;, &quot;BL60&quot;,
&quot;BL 45 days&quot;, &quot;BL45&quot;,
&quot;BL 30 days&quot;, &quot;BL30&quot;,
&quot;BL 120 days&quot;, &quot;BL120&quot;,

&quot;90 days from invoice&quot;, &quot;INV90&quot;,
&quot;75 days from invoice&quot;, &quot;INV75&quot;,
&quot;7 days from invoice&quot;, &quot;INV07&quot;,
&quot;60 days from invoice&quot;, &quot;INV60&quot;,
&quot;45 days from invoice&quot;, &quot;INV45&quot;,
&quot;40 days from invoice&quot;, &quot;INV40&quot;,
&quot;30 days from invoice&quot;, &quot;INV30&quot;,
&quot;20 days from invoice&quot;, &quot;INV20&quot;,
&quot;15 days from invoice&quot;, &quot;INV15&quot;,
&quot;120 days from invoice&quot;, &quot;INV120&quot;,

&quot;60 days from LR&quot;, &quot;LR60&quot;,
&quot;30 days from goods arrival&quot;, &quot;30DDEL&quot;,

&quot;70% advance &amp; 30% CACD&quot;, &quot;70ADV-30CD&quot;,

&quot;50% advance &amp; 50% PDC 45 days&quot;, &quot;50ADV50PDC&quot;,
&quot;50% advance &amp; 50% CACD&quot;, &quot;50ADV-50CD&quot;,
&quot;50% advance &amp; 50% BL 60 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% BL 45 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% against inspection&quot;, &quot;50ADV50INS&quot;,
&quot;50% advance &amp; 50% against dispatch&quot;, &quot;50ADV50DIS&quot;,
&quot;50% advance &amp; 50% 60 days from invoice&quot;, &quot;50ADV50INV&quot;,

&quot;40% advance &amp; 60% before dispatch&quot;, &quot;40ADV60DIS&quot;,

&quot;30% advance &amp; 70% CACD&quot;, &quot;30ADV-70CD&quot;,
&quot;30% advance &amp; 70% before dispatch&quot;, &quot;30ADV70DIS&quot;,

&quot;25% advance &amp; 75% LC at sight&quot;, &quot;25ADV-75LC&quot;,
&quot;25% advance &amp; 75% CACD&quot;, &quot;25ADV-75CD&quot;,
&quot;25% advance &amp; 75% BL 60 days&quot;, &quot;25ADV-75BL&quot;,
&quot;25% advance &amp; 75% before dispatch&quot;, &quot;25ADV75DIS&quot;,

&quot;20% advance &amp; 80% CACD&quot;, &quot;20ADV-80CD&quot;,
&quot;20% advance &amp; 80% before dispatch&quot;, &quot;20ADV80DIS&quot;,
&quot;20% advance &amp; 80% 60 days from invoice&quot;, &quot;20ADV80INV&quot;,

&quot;100% cash against copy documents&quot;, &quot;CACD&quot;,
&quot;100% against delivery&quot;, &quot;100%DEL&quot;,
&quot;100% advance against proforma&quot;, &quot;100%PI&quot;,
&quot;100% advance against BL copy&quot;, &quot;100%CBL&quot;,
&quot;100% advance&quot;, &quot;100%ADV&quot;,

&quot;10% advance &amp; 90% BL 30 days&quot;, &quot;10ADV-90BL&quot;,
&quot;10% ADV &amp; 90% CACD&quot;, &quot;10ADV-90CD&quot;,

&quot;10 days from invoice&quot;, &quot;INV10&quot;,

&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NBC_DRC_Account_DRC_Code__c.field-meta.xml
<CustomField>
    <fullName>NBC_DRC_Account_DRC_Code__c</fullName>
    <externalId>true</externalId>
    <label>Account DRC Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Hazardous__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Hazardous__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hazardous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_KIND_OF_PKG__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_KIND_OF_PKG__c</fullName>
    <label>KIND OF PKG</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IBC (900 KGS)</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
            <value>
                <fullName>250 GRAMS AL</fullName>
            </value>
            <value>
                <fullName>250 GRAMS PAPER</fullName>
            </value>
            <value>
                <fullName>250 KGS SS</fullName>
            </value>
            <value>
                <fullName>30 KGS PAIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_MARKS_NOS__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_MARKS_NOS__c</fullName>
    <label>MARKS &amp; NOS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Generate_Export_PI_ControllerTest.cls
/**
 * @File Name   : Generate_Export_PI_ControllerTest.cls
 * @Description : Test class for Generate_Export_PI_Controller
 * @Modification Log :
 *==============================================================================
 * Ver | Date       | Modification
 *==============================================================================
 * 1.0 | Mar 2026   | Initial Version
 **/
@IsTest
private class Generate_Export_PI_ControllerTest {

    // =========================================================================
    // @TestSetup — shared data
    // =========================================================================
    @TestSetup
    static void setupData() {

        // 1. Standard Pricebook
        Id stdPbId = Test.getStandardPricebookId();
        update new Pricebook2(Id = stdPbId, IsActive = true);

        // 2. Account
        Account acc = new Account(
            Name            = 'Test Export Account',
            NBC_DRC_Account_DRC_Code__c = 'DRC-CODE-001',
            CurrencyIsoCode = 'INR',
            Phone = '1234567890',
            DRC_NBC_PAN_No__c = 'AWVPY9594J',
            DRC_NBC_GST_Number__c = '27AWVPY9594J1ZY',
            DRC_NBC_Payment_Term_Code__c = '10 DAYS',
            DRC_NBC_Account_Email_Email__c = 'test@example.com',
            BillingStreet = '123 Street',
            BillingCity = 'City',
            BillingCountry = 'India',
            BillingCountryCode = 'IN',
            BillingPostalCode = '462002',
            BillingState = 'Maharashtra',
            BillingStateCode = 'MH',
            DRC_NBC_Volume__c = 70, 
            DRC_NBC_Credit_Limit__c = 123456787,
            DRC_NBC_Value__c = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c = 'Punjab National bank',
            Industry = 'Chemicals Construction',
            Type = 'Analyst'
        );
        insert acc;

        // 3. Products
        Product2 p1 = new Product2(
            Name                        = 'Export Product A',
            IsActive                    = true,
            ProductCode                 = 'EP001',
            DRC_NBC_HSN_SAC_Code__c     = 'HSN001',
            DRC_NBC_Hazardous__c        = false,
            DRC_NBC_MARKS_NOS__c        = 'MARK-A',
            DRC_NBC_KIND_OF_PKG__c      = 'Drums'
        );
        Product2 p2 = new Product2(
            Name                        = 'Export Product B',
            IsActive                    = true,
            ProductCode                 = 'EP002',
            DRC_NBC_HSN_SAC_Code__c     = 'HSN002',
            DRC_NBC_Hazardous__c        = true,
            DRC_NBC_MARKS_NOS__c        = null,   // fallback to product name
            DRC_NBC_KIND_OF_PKG__c      = 'Cans'
        );
        insert new List<Product2>{ p1, p2 };

        // 4. Standard PBEs
        String curr = UserInfo.getDefaultCurrency();
        insert new List<PricebookEntry>{
            new PricebookEntry(Pricebook2Id = stdPbId, Product2Id = p1.Id,
                               UnitPrice = 1, IsActive = true, CurrencyIsoCode = curr),
            new PricebookEntry(Pricebook2Id = stdPbId, Product2Id = p2.Id,
                               UnitPrice = 1, IsActive = true, CurrencyIsoCode = curr)
        };

        // 5. Export Order (no sequence yet — controller will assign)
        Order exportOrd = new Order(
            AccountId           = acc.Id,
            Status              = 'Draft',
            EffectiveDate       = Date.newInstance(2026, 2, 5),
            Pricebook2Id        = stdPbId,
            CurrencyIsoCode     = curr,
            BillingStreet       = '123 Export Street',
            BillingCity         = 'Mumbai',
            BillingState        = 'Maharashtra',
            BillingPostalCode   = '400064',
            BillingCountry      = 'India',
            DRC_NBC_Type__c                             = 'Export',
            DRC_NBC_Payment_Terms__c                    = '100',
            DRC_NBC_Port_Of_Loading__c                  = 'NHAVA SHEVA',
            DRC_NBC_Port_Of_Discharge__c                = 'DUBAI PORT',
            DRC_NBC_Final_Destination__c                = 'UAE',
            DRC_NBC_Country_Of_Origin__c                = 'India',
            DRC_NBC_Shipment_Method__c                  = 'BY SEA',
            DRC_NBC_Inco_Terms__c                       = 'Cost Insurance & Freight (CIF)',
          //  DRC_NBC_Required_Documents__c               = 'Bill of Lading;Packing List\nCertificate of Origin',
            DRC_NBC_Select_Bank__c                      = null,
            DRC_NBC_Invoice_Export_Sequence_Number__c   = null
        );
        insert exportOrd;

        // 6. Domestic Order
        Order domesticOrd = new Order(
            AccountId           = acc.Id,
            Status              = 'Draft',
            EffectiveDate       = Date.today(),
            Pricebook2Id        = stdPbId,
            CurrencyIsoCode     = curr,
            BillingStreet       = '456 Domestic Road',
            BillingCity         = 'Pune',
            BillingState        = 'Maharashtra',
            BillingPostalCode   = '411001',
            BillingCountry      = 'India',
            DRC_NBC_Type__c                         = 'Domestic',
            DRC_NBC_Import_Starting_Sequence__c     = null
        );
        insert domesticOrd;

        // 7. PBEs from std pricebook for order items
        PricebookEntry pbe1 = [SELECT Id FROM PricebookEntry
                               WHERE Product2Id = :p1.Id AND Pricebook2Id = :stdPbId LIMIT 1];
        PricebookEntry pbe2 = [SELECT Id FROM PricebookEntry
                               WHERE Product2Id = :p2.Id AND Pricebook2Id = :stdPbId LIMIT 1];

        // 8. Order Items on export order
        insert new List<OrderItem>{
            new OrderItem(
                OrderId          = exportOrd.Id,
                PricebookEntryId = pbe1.Id,
                Quantity         = 10,
                UnitPrice        = 500,
                Description      = 'Custom Description A'
            ),
            new OrderItem(
                OrderId          = exportOrd.Id,
                PricebookEntryId = pbe2.Id,
                Quantity         = 5,
                UnitPrice        = 200,
                Description      = null   // fallback to product name
            )
        };
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────
    private static Order getExportOrder() {
        return [SELECT Id FROM Order WHERE DRC_NBC_Type__c = 'Export' LIMIT 1];
    }

    private static Order getDomesticOrder() {
        return [SELECT Id FROM Order WHERE DRC_NBC_Type__c = 'Domestic' LIMIT 1];
    }

    private static PageReference buildPage(Id ordId) {
        PageReference pg = Page.DRC_NBC_OrderPI_Export_Template; // your VF page name
        pg.getParameters().put('id', ordId);
        return pg;
    }

    // =========================================================================
    // Constructor — basic load
    // =========================================================================

    // ─── Test: controller loads without exception for valid Export order ───────
    @IsTest
    static void test_constructor_loadsExportOrder() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

    }

    // ─── Test: controller loads without exception for valid Domestic order ─────
    @IsTest
    static void test_constructor_loadsDomesticOrder() {
        Order ord = getDomesticOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: constructor with no id param — no exception, orderRecord null ──
    @IsTest
    static void test_constructor_noId_doesNotThrow() {
        PageReference pg = Page.DRC_NBC_OrderPI_Export_Template;
        // Do NOT set 'id' param
        Test.setCurrentPage(pg);

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

    }

    // =========================================================================
    // Company Info
    // =========================================================================

    // ─── Test: company fields are hard-coded correctly ────────────────────────
    @IsTest
    static void test_companyInfo_isSetCorrectly() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // =========================================================================
    // Line Items
    // =========================================================================

    // ─── Test: items list is populated with correct count ─────────────────────
    @IsTest
    static void test_lineItems_loadedCorrectly() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: item with description uses description not product name ─────────
    @IsTest
    static void test_lineItems_usesDescriptionWhenSet() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: item with null description falls back to product name ──────────
    @IsTest
    static void test_lineItems_fallsBackToProductName_whenDescriptionNull() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

    }

    // ─── Test: item with null marksAndNos falls back to product name ──────────
    @IsTest
    static void test_lineItems_marksAndNos_fallsBackToProductName() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

        Boolean foundFallback = false;
        for (Generate_Export_PI_Controller.ExportLineItem li : ctrl.items) {
            if (li.marksAndNos == 'Export Product B') {
                foundFallback = true;
            }
        }
        System.assertEquals(true, foundFallback,
            'marksAndNos should fall back to product name when null');
    }

    // ─── Test: hazardous true product maps to "Yes" ───────────────────────────
    @IsTest
    static void test_lineItems_hazardousTrue_mapsToYes() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: hazardous false product maps to "No" ───────────────────────────
    @IsTest
    static void test_lineItems_hazardousFalse_mapsToNo() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: totalAmount equals sum of all order item TotalPrices ───────────
    @IsTest
    static void test_lineItems_totalAmountIsCorrect() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: amountInWords is populated ─────────────────────────────────────
    @IsTest
    static void test_lineItems_amountInWordsPopulated() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

        System.assertNotEquals(null, ctrl.amountInWords,
            'amountInWords should not be null');
        System.assert(ctrl.amountInWords.endsWith('ONLY'),
            'amountInWords should end with ONLY. Got: ' + ctrl.amountInWords);
    }

    // =========================================================================
    // Bank Details — null select bank
    // =========================================================================

    // ─── Test: beneficiaryName set even when no bank selected ─────────────────
    @IsTest
    static void test_bankDetails_noBankSelected_beneficiaryNameSet() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // =========================================================================
    // Required Documents
    // =========================================================================

    // ─── Test: required documents parsed from semicolon/newline delimiters ────
    @IsTest
    static void test_requiredDocuments_parsedCorrectly() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: order with no required documents gives empty list ──────────────
    @IsTest
    static void test_requiredDocuments_emptyWhenNull() {
        Order ord = getDomesticOrder();
        // Domestic order was inserted with no DRC_NBC_Required_Documents__c
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // =========================================================================
    // getFormattedEffectiveDate()
    // =========================================================================

    // ─── Test: formatted date returns correct dd-MMM-yyyy string ──────────────
    @IsTest
    static void test_getFormattedEffectiveDate_returnsCorrectFormat() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        String formatted = ctrl.getFormattedEffectiveDate();
        Test.stopTest();
    }

    // ─── Test: getFormattedEffectiveDate returns empty string when no order ───
    @IsTest
    static void test_getFormattedEffectiveDate_returnsEmpty_whenNoOrder() {
        PageReference pg = Page.DRC_NBC_OrderPI_Export_Template ;
        Test.setCurrentPage(pg); // No id param

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        String formatted = ctrl.getFormattedEffectiveDate();
        Test.stopTest();
    }

    // =========================================================================
    // convertAmountToWords — via totalAmount (indirect testing)
    // =========================================================================
    // ─── Test: INR currency uses PAISE in amount words ────────────────────────
    @IsTest
    static void test_amountInWords_inrCurrency_usesPaise() {
        Order ord = getExportOrder();
        ord.CurrencyIsoCode = 'INR';
        update ord;
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();

    }

    // =========================================================================
    // Sequence Number Assignment
    // =========================================================================

    // ─── Test: Export order gets sequence number assigned ─────────────────────
    @IsTest
    static void test_exportSequence_assignedOnFirstLoad() {
        Order ord = getExportOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }

    // ─── Test: Domestic order gets sequence number assigned ───────────────────
    @IsTest
    static void test_domesticSequence_assignedOnFirstLoad() {
        Order ord = getDomesticOrder();
        Test.setCurrentPage(buildPage(ord.Id));

        Test.startTest();
        Generate_Export_PI_Controller ctrl = new Generate_Export_PI_Controller();
        Test.stopTest();
    }
}