force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <formula>CASE(
TEXT(DRC_NBC_Payment_Terms_Description__c),

&quot;PDC 90 days&quot;, &quot;PDC90&quot;,
&quot;PDC 60 days&quot;, &quot;PDC60&quot;,
&quot;PDC 45 days&quot;, &quot;PDC45&quot;,
&quot;PDC 30 days&quot;, &quot;PDC30&quot;,

&quot;Irrevocable LC at sight&quot;, &quot;IRRELC&quot;,
&quot;Irrevocable LC 90 days&quot;, &quot;IRRLC90&quot;,
&quot;Irrevocable LC 60 days&quot;, &quot;IRRLC60&quot;,
&quot;Irrevocable LC 45 days&quot;, &quot;IRRLC45&quot;,
&quot;Irrevocable LC 30 days&quot;, &quot;IRRLC30&quot;,

&quot;Free sample&quot;, &quot;FOC&quot;,

&quot;DP AT SIGHT&quot;, &quot;DPSIGHT&quot;,
&quot;DP 90 days&quot;, &quot;DP90&quot;,
&quot;DP 60 days&quot;, &quot;DP60&quot;,
&quot;DP 30 days&quot;, &quot;DP30&quot;,

&quot;DA 90 days&quot;, &quot;DA90&quot;,
&quot;DA 60 days&quot;, &quot;DA60&quot;,
&quot;DA 45 days&quot;, &quot;DA45&quot;,
&quot;DA 30 days&quot;, &quot;DA30&quot;,

&quot;Bond transfer&quot;, &quot;BONTRN&quot;,

&quot;BL 90 days&quot;, &quot;BL90&quot;,
&quot;BL 75 days&quot;, &quot;BL75&quot;,
&quot;BL 60 days&quot;, &quot;BL60&quot;,
&quot;BL 45 days&quot;, &quot;BL45&quot;,
&quot;BL 30 days&quot;, &quot;BL30&quot;,
&quot;BL 120 days&quot;, &quot;BL120&quot;,

&quot;90 days from invoice&quot;, &quot;INV90&quot;,
&quot;75 days from invoice&quot;, &quot;INV75&quot;,
&quot;7 days from invoice&quot;, &quot;INV07&quot;,
&quot;60 days from invoice&quot;, &quot;INV60&quot;,
&quot;45 days from invoice&quot;, &quot;INV45&quot;,
&quot;40 days from invoice&quot;, &quot;INV40&quot;,
&quot;30 days from invoice&quot;, &quot;INV30&quot;,
&quot;20 days from invoice&quot;, &quot;INV20&quot;,
&quot;15 days from invoice&quot;, &quot;INV15&quot;,
&quot;120 days from invoice&quot;, &quot;INV120&quot;,

&quot;60 days from LR&quot;, &quot;LR60&quot;,
&quot;30 days from goods arrival&quot;, &quot;30DDEL&quot;,

&quot;70% advance &amp; 30% CACD&quot;, &quot;70ADV-30CD&quot;,

&quot;50% advance &amp; 50% PDC 45 days&quot;, &quot;50ADV50PDC&quot;,
&quot;50% advance &amp; 50% CACD&quot;, &quot;50ADV-50CD&quot;,
&quot;50% advance &amp; 50% BL 60 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% BL 45 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% against inspection&quot;, &quot;50ADV50INS&quot;,
&quot;50% advance &amp; 50% against dispatch&quot;, &quot;50ADV50DIS&quot;,
&quot;50% advance &amp; 50% 60 days from invoice&quot;, &quot;50ADV50INV&quot;,

&quot;40% advance &amp; 60% before dispatch&quot;, &quot;40ADV60DIS&quot;,

&quot;30% advance &amp; 70% CACD&quot;, &quot;30ADV-70CD&quot;,
&quot;30% advance &amp; 70% before dispatch&quot;, &quot;30ADV70DIS&quot;,

&quot;25% advance &amp; 75% LC at sight&quot;, &quot;25ADV-75LC&quot;,
&quot;25% advance &amp; 75% CACD&quot;, &quot;25ADV-75CD&quot;,
&quot;25% advance &amp; 75% BL 60 days&quot;, &quot;25ADV-75BL&quot;,
&quot;25% advance &amp; 75% before dispatch&quot;, &quot;25ADV75DIS&quot;,

&quot;20% advance &amp; 80% CACD&quot;, &quot;20ADV-80CD&quot;,
&quot;20% advance &amp; 80% before dispatch&quot;, &quot;20ADV80DIS&quot;,
&quot;20% advance &amp; 80% 60 days from invoice&quot;, &quot;20ADV80INV&quot;,

&quot;100% cash against copy documents&quot;, &quot;CACD&quot;,
&quot;100% against delivery&quot;, &quot;100%DEL&quot;,
&quot;100% advance against proforma&quot;, &quot;100%PI&quot;,
&quot;100% advance against BL copy&quot;, &quot;100%CBL&quot;,
&quot;100% advance&quot;, &quot;100%ADV&quot;,

&quot;10% advance &amp; 90% BL 30 days&quot;, &quot;10ADV-90BL&quot;,
&quot;10% ADV &amp; 90% CACD&quot;, &quot;10ADV-90CD&quot;,

&quot;10 days from invoice&quot;, &quot;INV10&quot;,

&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/DRC_NBC_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Acknowledgement_Date1__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Acknowledgement_Date1__c</fullName>
    <label>Acknowledgement Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Acknowledgement_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Acknowledgement_Number__c</fullName>
    <label>Acknowledgement Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Delivery_Location__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Delivery_Location__c</fullName>
    <label>Delivery Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_EWay_Bill_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_EWay_Bill_Number__c</fullName>
    <label>EWay Bill Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_External_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_External_Document_Number__c</fullName>
    <label>External Document Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_IRN_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_IRN_Number__c</fullName>
    <label>IRN Number</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Order_Number__c</fullName>
    <label>Order Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Shipping_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Customer_Name__c</fullName>
    <label>Shipping Customer Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Shipping_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_GST_Number__c</fullName>
    <label>Shipping GST Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice__c/fields/DRC_NBC_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Vehicle_Number__c</fullName>
    <label>Vehicle Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice_Line_Item__c/DRC_NBC_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Line Number-{0000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Invoice_Line_Item__c/fields/DRC_NBC_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <referenceTo>DRC_NBC_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Invoice_Lot__c/DRC_NBC_Invoice_Lot__c.object-meta.xml
<CustomObject>
    <label>Invoice Lot</label>
    <nameField>
        <displayFormat>Lot-{0000}</displayFormat>
        <label>Invoice Lot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lots</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Invoice_Lot__c/fields/DRC_NBC_Invoice__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>DRC_NBC_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lots</relationshipLabel>
    <relationshipName>Invoice_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Term_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DRC_NBC_Invoice_Sync_WebService.cls
// Test Class - DRC_NBC_Invoice_Sync_WebService_Test

@RestResource(urlMapping = '/InvoiceSync/*')
global without sharing class DRC_NBC_Invoice_Sync_WebService {
    
    @HttpPost
    global static void syncInvoices() {
        Savepoint sp;
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try {
            sp = Database.setSavePoint();
            String body = req.requestBody.toString();
            // Deserialize and validate payload
            DRC_NBC_Integration_Payload.invoiceSyncPayload payload = DRC_NBC_Integration_Utility.validateInvoiceSyncPayload(body);
            System.debug('Payload validated');
            DRC_NBC_Invoice__c invoiceRecord;
            // Try to find existing invoice by DRC_NBC_Invoice_Number__c
            List<DRC_NBC_Invoice__c> existingInvoices = [
                SELECT Id FROM DRC_NBC_Invoice__c
                WHERE DRC_NBC_Invoice_Number__c = :payload.InvoiceNumber
                LIMIT 1
            ];
            if (!existingInvoices.isEmpty()) {
                invoiceRecord = existingInvoices[0];
            } else {
                invoiceRecord = new DRC_NBC_Invoice__c();
            }
            // Populate fields  
            invoiceRecord.DRC_NBC_Invoice_Number__c           = payload.InvoiceNumber;
            invoiceRecord.DRC_NBC_Invoice_Date__c             = payload.InvoiceDate;
            invoiceRecord.DRC_NBC_Order_Number__c           =   payload.OrderNumber;
            invoiceRecord.DRC_NBC_External_Document_Number__c = payload.ExternalDocumentNumber;
            invoiceRecord.DRC_NBC_IRN_Number__c               = payload.IRNNumber;
            invoiceRecord.DRC_NBC_Acknowledgement_Number__c   = payload.AcknowledgementNumber;
            invoiceRecord.DRC_NBC_Acknowledgement_Date1__c     = payload.AcknowledgementDate;
            invoiceRecord.DRC_NBC_EWay_Bill_Number__c         = payload.EWayBillNumber;
            invoiceRecord.DRC_NBC_Vehicle_Number__c           = payload.VehicleNumber;
            invoiceRecord.DRC_NBC_Payment_Terms__c            = payload.PaymentTerms;
            invoiceRecord.DRC_NBC_Delivery_Location__c        = payload.DeliveryLocation;
            invoiceRecord.DRC_NBC_Shipping_Customer_Name__c   = payload.ShippingCustomerName;
            invoiceRecord.DRC_NBC_Shipping_Address__c         = payload.ShippingAddress;
            invoiceRecord.DRC_NBC_Shipping_GST_Number__c      = payload.ShippingGSTNumber;
            invoiceRecord.DRC_NBC_Shipping_State__c           = payload.ShippingState;
            invoiceRecord.DRC_NBC_Shipping_State_Code__c      = payload.ShippingStateCode;
            if (!String.isBlank(payload.OrderNumber)) {
                List<Order> matchedOrders = [
                    SELECT Id, DRC_NBC_Cust_Order_Number__c 
                    FROM Order 
                    WHERE DRC_NBC_Cust_Order_Number__c = :payload.OrderNumber 
                    LIMIT 1
                ];
                
                if (!matchedOrders.isEmpty()) {
                    invoiceRecord.DRC_NBC_Order__c = matchedOrders[0].Id;
                } else {
                    System.debug('No matching Order found for OrderNumber: ' + payload.OrderNumber);
                }
            }
            
            
            // Insert or update invoice
            if (invoiceRecord.Id == null) {
                if (!String.isBlank(payload.ShippingDRCCode)) {
                    List<Account> matchingAccounts = [
                        SELECT Id, Name, DRC_NBC_Customer_Number__c
                        FROM Account
                        WHERE DRC_NBC_Customer_Number__c = :payload.ShippingDRCCode
                        LIMIT 1
                    ];
                    if (!matchingAccounts.isEmpty()) {
                        Account matchedAccount = matchingAccounts[0];
                        invoiceRecord.DRC_NBC_Shipped_To_DRC_Customer_Code__c =  matchedAccount.Id;
                        invoiceRecord.DRC_NBC_Account__c = matchedAccount.Id;
                        System.debug('Matched Account: ' + matchedAccount.Name);
                    } else {
                        System.debug('No Account found with DRC_NBC_Customer_Number__c = ' + payload.ShippingDRCCode);
                    }
                }
                insert invoiceRecord;
            } else {
                update invoiceRecord;
            }
            // Now handle line items
            List<DRC_NBC_Invoice_Line_Item__c> lineItemsToUpsert = new List<DRC_NBC_Invoice_Line_Item__c>();
            Map<String, DRC_NBC_Invoice_Line_Item__c> productCodeToLineItemMap = new Map<String, DRC_NBC_Invoice_Line_Item__c>();
            
            if (payload.lineItems != null && !payload.lineItems.isEmpty()) {
                // 1. Extract product codes from payload
                Set<String> productCodes = new Set<String>();
                for (DRC_NBC_Integration_Payload.invoiceLineItem li : payload.lineItems) {
                    if (!String.isBlank(li.ProductCode)) {
                        productCodes.add(li.ProductCode);
                    }
                }
                
                // 2. Query Product2 records by ProductCode
                Map<String, Product2> productMap = new Map<String, Product2>();
                if (!productCodes.isEmpty()) {
                    for (Product2 p : [
                        SELECT Id, ProductCode
                        FROM Product2
                        WHERE ProductCode IN :productCodes
                    ]) {
                        productMap.put(p.ProductCode, p);
                    }
                }
                
                // 3. Query existing line items for this invoice and product codes
                Map<String, DRC_NBC_Invoice_Line_Item__c> existingLineItemMap = new Map<String, DRC_NBC_Invoice_Line_Item__c>();
                if (!productCodes.isEmpty()) {
                    for (DRC_NBC_Invoice_Line_Item__c existing : [
                        SELECT Id, DRC_NBC_Product__r.ProductCode
                        FROM DRC_NBC_Invoice_Line_Item__c
                        WHERE DRC_NBC_Invoice_Number__c = :invoiceRecord.Id
                        AND DRC_NBC_Product__r.ProductCode IN :productCodes
                    ]) {
                        existingLineItemMap.put(existing.DRC_NBC_Product__r.ProductCode, existing);
                    }
                }
                
                // 4. Build line items for insert/update
                for (DRC_NBC_Integration_Payload.invoiceLineItem li : payload.lineItems) {
                    if (String.isBlank(li.ProductCode)) continue;
                    
                    Product2 matchedProduct = productMap.get(li.ProductCode);
                    if (matchedProduct == null) {
                        System.debug('No Product2 found for ProductCode: ' + li.ProductCode);
                        continue;
                    }
                    
                    DRC_NBC_Invoice_Line_Item__c lineItem;
                    if (existingLineItemMap.containsKey(li.ProductCode)) {
                        lineItem = existingLineItemMap.get(li.ProductCode); // update
                    } else {
                        lineItem = new DRC_NBC_Invoice_Line_Item__c(); // insert
                        lineItem.DRC_NBC_Invoice_Number__c = invoiceRecord.Id;
                        lineItem.DRC_NBC_Product__c = matchedProduct.Id;
                    }
                    
                    // Common fields to update/set
                    lineItem.DRC_NBC_Amount__c = li.Amount;
                    lineItem.DRC_NBC_Product_Code__c = li.ProductCode;
                    
                    lineItemsToUpsert.add(lineItem);
                    productCodeToLineItemMap.put(li.ProductCode, lineItem);
                }
                
                // 5. Upsert line items first
                if (!lineItemsToUpsert.isEmpty()) {
                    upsert lineItemsToUpsert;
                }
                
                // 6. Now handle Invoice Lot records
                List<DRC_NBC_Invoice_Lot__c> invoiceLotsToUpsert = new List<DRC_NBC_Invoice_Lot__c>();
                
                // Query existing Invoice Lot records for these line items
                Set<Id> lineItemIds = new Set<Id>();
                for (DRC_NBC_Invoice_Line_Item__c li : lineItemsToUpsert) {
                    lineItemIds.add(li.Id);
                }
                
                Map<String, DRC_NBC_Invoice_Lot__c> existingLotMap = new Map<String, DRC_NBC_Invoice_Lot__c>();
                if (!lineItemIds.isEmpty()) {
                    for (DRC_NBC_Invoice_Lot__c existingLot : [
                        SELECT Id, DRC_NBC_Invoice_Line_Item__c, DRC_NBC_Lot_Number__c
                        FROM DRC_NBC_Invoice_Lot__c
                        WHERE DRC_NBC_Invoice_Line_Item__c IN :lineItemIds
                    ]) {
                        String key = existingLot.DRC_NBC_Invoice_Line_Item__c + '_' + existingLot.DRC_NBC_Lot_Number__c;
                        existingLotMap.put(key, existingLot);
                    }
                }
                
                // Create or update Invoice Lot records from lotDetails
                for (DRC_NBC_Integration_Payload.invoiceLineItem li : payload.lineItems) {
                    if (String.isBlank(li.ProductCode)) continue;
                    if (li.lotDetails == null || li.lotDetails.isEmpty()) continue;
                    
                    DRC_NBC_Invoice_Line_Item__c lineItem = productCodeToLineItemMap.get(li.ProductCode);
                    if (lineItem == null || lineItem.Id == null) continue;
                    
                    // Get the Product2 ID for this line item
                    Product2 matchedProduct = productMap.get(li.ProductCode);
                    if (matchedProduct == null) continue;
                    
                    for (DRC_NBC_Integration_Payload.lotDetail ld : li.lotDetails) {
                        if (String.isBlank(ld.lot)) continue;
                        
                        String lotKey = lineItem.Id + '_' + ld.lot;
                        DRC_NBC_Invoice_Lot__c invoiceLot;
                        
                        if (existingLotMap.containsKey(lotKey)) {
                            invoiceLot = existingLotMap.get(lotKey); // update
                        } else {
                            invoiceLot = new DRC_NBC_Invoice_Lot__c(); // insert
                            invoiceLot.DRC_NBC_Invoice_Line_Item__c = lineItem.Id;
                            invoiceLot.DRC_NBC_Lot_Number__c = ld.lot;
                            invoiceLot.DRC_NBC_Product__c = matchedProduct.Id; // Add Product lookup
                            invoiceLot.DRC_NBC_Invoice__c = invoiceRecord.Id; // Add Invoice lookup
                        }
                        
                        // Set/update quantity
                        invoiceLot.DRC_NBC_Lot_Quantity__c = string.valueOf(ld.quantity);
                        invoiceLotsToUpsert.add(invoiceLot);
                    }
                }
                
                // 7. Upsert Invoice Lot records
                if (!invoiceLotsToUpsert.isEmpty()) {
                    upsert invoiceLotsToUpsert;
                }
            }
            
            res.statusCode = 201;
            res.responseBody = Blob.valueOf('Invoice ' + payload.InvoiceNumber + ' and line items synced successfully.');
            DRC_NBC_API_Log_Handler.createApiLog('/InvoiceSync', body, res.responseBody?.toString(), 'POST', null, res.statusCode, null, 'Success', null);
            
        } catch (Exception e) {
            Database.rollback(sp);
            res.statusCode = 500;
            res.responseBody = Blob.valueOf('Error: ' + e.getMessage());
            DRC_NBC_API_Log_Handler.createApiLog(
                '/InvoiceSync', req.requestBody.toString(), null, 'POST',
                e.getMessage(), 500, e.getStackTraceString(), 'Error', null
            );
        }
    }
    
    @TestVisible
    private static String formatLotNo(String rawLotNo) {
        if (String.isBlank(rawLotNo)) return null;
        List<String> lotNumbers = new List<String>();
        Integer index = 1;
        
        for (String part : rawLotNo.split(',')) {
            part = part.trim();
            if (!String.isBlank(part)) {
                String lotNumber = part.split(' - Qty')[0].trim();
                lotNumbers.add(index + '. ' + lotNumber);
                index++;
            }
        }
        
        return String.join(lotNumbers, '\n');
    }
    
    @TestVisible
    private static String formatLotQuantity(String rawLotNo) {
        if (String.isBlank(rawLotNo)) return null;
        List<String> lotQuantities = new List<String>();
        Integer index = 1;
        
        for (String part : rawLotNo.split(',')) {
            part = part.trim();
            if (!String.isBlank(part)) {
                // Extract the quantity part after 'Qty :'
                if (part.contains('Qty')) {
                    String[] qtyParts = part.split('Qty\\s*:\\s*');
                    if (qtyParts.size() > 1) {
                        String qty = qtyParts[1].replaceAll(',', '').trim();
                        lotQuantities.add(index + '. ' + qty);
                        index++;
                    }
                }
            }
        }
        
        return String.join(lotQuantities, '\n');
    }
}