force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_BC_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Approval_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved In BC?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Posted_To_bc__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Posted_To_bc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Posted To Bc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>GST Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Account_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Approval_Status__c</fullName>
    <label>Account Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD (UNIT-III)</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_Account_BC_Callout_Test.cls
@isTest
private class DRC_NBC_Account_BC_Callout_Test {
    
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;
        
        public MockHttpResponseGenerator(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }
        
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(responseBody);
            res.setStatusCode(statusCode);
            return res;
        }
    }
    
    @testSetup
    static void setupTestData() {
        // Create any test metadata or configuration records if needed
    }
    
    private static Account createTestAccount(Boolean withApprovalStatus, Boolean withShippingAddress, Boolean withCustomerNumber) {
        Account acc = new Account(
            Name = 'Test Account',
            CurrencyIsoCode = 'INR',
            Phone = '1234567890',
            AccountNumber = 'A123',
            DRC_NBC_PAN_No__c = 'AWVPY9594J',
            DRC_NBC_GST_Number__c = '27AWVPY9594J1ZY',
            DRC_NBC_Customer_Number__c = withCustomerNumber ? 'CUST123' : null,
            DRC_NBC_Payment_Term_Code__c = '10 DAYS',
            DRC_NBC_Account_Email_Email__c = 'test@example.com',
            BillingStreet = '123 Street',
            BillingCity = 'City',
            BillingCountry = 'India',
            BillingCountryCode = 'IN',
            BillingPostalCode = '462002',
            BillingState = 'Maharashtra',
            BillingStateCode = 'MH',
            DRC_NBC_BC_Approval_Status__c = withApprovalStatus
        );
        insert acc;
        
        if (withShippingAddress) {
            DRC_NBC_Addresses__c addr = new DRC_NBC_Addresses__c(
                DRC_NBC_Address__Street__s = 'Street',
                DRC_NBC_Address__City__s = 'City',
                DRC_NBC_Address__StateCode__s = 'MH',
                DRC_NBC_Address__PostalCode__s = '462002',
                DRC_NBC_Address__CountryCode__s = 'IN',
                DRC_NBC_Type__c = 'Shipping',
                DRC_NBC_Warehouse__c = 'CFS - JNPT'
            );
            insert addr;
        }
        
        return acc;
    }
    
    private static Order createTestOrder(Id accountId) {
        Order ord = new Order(
            Name = 'Test Order',
            AccountId = accountId,
            Status = 'Draft',
            EffectiveDate = Date.today(),
            DRC_NBC_Account_Approval_Status__c = 'Pending'
        );
        insert ord;
        return ord;
    }
    
    // Test DRC_NBC_Account_BC_Callout.executeCallout with BC Approval Status true
    @isTest
    static void test_executeCallout_WithBCApprovalStatus() {
        Account acc = createTestAccount(true, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.startTest();
        String result = DRC_NBC_Account_BC_Callout.executeCallout(ord.Id);
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout.executeCallout without BC Approval Status
    @isTest
    static void test_executeCallout_WithoutBCApprovalStatus() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.startTest();
        String result = DRC_NBC_Account_BC_Callout.executeCallout(ord.Id);
        Test.stopTest();
        
        System.assertEquals('Account Sync SUCCESS', result);
    }
    
    // Test DRC_NBC_Account_BC_Callout.executeCallout with null Order Id
    @isTest
    static void test_executeCallout_NullOrderId() {
        Test.startTest();
        String result = DRC_NBC_Account_BC_Callout.executeCallout(null);
        Test.stopTest();
        
        System.assertEquals('FAILURE: Order Id is required', result);
    }
    
    // Test DRC_NBC_Account_BC_Callout.executeCallout with invalid Order Id
    @isTest
    static void test_executeCallout_InvalidOrderId() {
        Test.startTest();
        String result = DRC_NBC_Account_BC_Callout.executeCallout('801000000000000AAA');
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout.getAccountDetails
    @isTest
    static void test_getAccountDetails() {
        Account acc = createTestAccount(false, true, true);
        
        Test.startTest();
        Account result = DRC_NBC_Account_BC_Callout.getAccountDetails(acc.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, result);
        System.assertEquals(acc.Id, result.Id);
        System.assertEquals('Test Account', result.Name);
    }
    
    // Test DRC_NBC_Account_BC_Callout.mapAccountToPayload
    @isTest
    static void test_mapAccountToPayload() {
        Account acc = createTestAccount(false, false, true);
        
        Test.startTest();
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        Test.stopTest();
        
        System.assertEquals('CUST123', payload.No);
        System.assertEquals('Test Account', payload.Name);
        System.assertEquals('INR', payload.Currency_Code);
        System.assertEquals('AWVPY9594J', payload.P_A_N_No);
        System.assertEquals('IND', payload.Country_Region_Code);
    }
    
    // Test DRC_NBC_Account_BC_Callout.updatePostedStatus
    @isTest
    static void test_updatePostedStatus() {
        Account acc = createTestAccount(false, false, true);
        
        Test.startTest();
        DRC_NBC_Account_BC_Callout.updatePostedStatus(acc.Id);
        Test.stopTest();
        
        Account updatedAcc = [SELECT DRC_NBC_Posted_To_bc__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(true, updatedAcc.DRC_NBC_Posted_To_bc__c);
    }
    
    // Test DRC_NBC_Account_BC_Callout_Queueable with existing customer number
    @isTest
    static void test_Queueable_WithExistingCustomerNumber() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"success": true}'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Queueable(ord.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Queueable without customer number (chains to second queue)
    @isTest
    static void test_Queueable_WithoutCustomerNumber() {
        Account acc = createTestAccount(false, false, false);
        Order ord = createTestOrder(acc.Id);
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Queueable(ord.Id));
        Test.stopTest();
        
        Account queriedAcc = [SELECT DRC_NBC_Customer_Number__c FROM Account WHERE Id = :acc.Id];
        System.assertNotEquals(null, queriedAcc);
    }
    
    // Test DRC_NBC_Account_BC_Callout_Queueable with BC approval status
    @isTest
    static void test_Queueable_WithBCApprovalStatus() {
        Account acc = createTestAccount(true, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Queueable(ord.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Queueable with exception
    @isTest
    static void test_Queueable_WithException() {
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Queueable('801000000000000AAA'));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Second_Queue successful execution
    @isTest
    static void test_SecondQueue_SuccessfulExecution() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"success": true}'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Second_Queue(ord.Id, acc.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Second_Queue with BC approval status
    @isTest
    static void test_SecondQueue_WithBCApprovalStatus() {
        Account acc = createTestAccount(true, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Second_Queue(ord.Id, acc.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Second_Queue with failed callout
    @isTest
    static void test_SecondQueue_FailedCallout() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, '{"error": "Server error"}'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Second_Queue(ord.Id, acc.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Second_Queue with exception
    @isTest
    static void test_SecondQueue_WithException() {
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Second_Queue('801000000000000AAA', '001000000000000AAA'));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Integration.prepareRequest
    /*@isTest
    static void test_Integration_PrepareRequest() {
        Account acc = createTestAccount(false, false, true);
        
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        String jsonBody = JSON.serialize(payload);
        
        DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(
            'test-endpoint',
            'POST',
            jsonBody,
            acc.Id
        );
        
        Test.startTest();
        HttpRequest req = integration.prepareRequest();
        Test.stopTest();
        
        System.assertNotEquals(null, req);
        System.assertEquals('POST', req.getMethod());
        System.assertEquals(jsonBody, req.getBody());
    }*/
    
    // Test DRC_NBC_Account_BC_Integration.processResponse with success
    @isTest
    static void test_Integration_ProcessResponse_Success() {
        Account acc = createTestAccount(false, false, true);
        
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        String jsonBody = JSON.serialize(payload);
        
        DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(
            'test-endpoint',
            'POST',
            jsonBody,
            acc.Id
        );
        
        HttpResponse successResp = new HttpResponse();
        successResp.setStatusCode(201);
        successResp.setBody('{"message":"Success"}');
        
        Test.startTest();
        integration.processResponse(successResp);
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Integration.processResponse with error
    @isTest
    static void test_Integration_ProcessResponse_Error() {
        Account acc = createTestAccount(false, false, true);
        
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        String jsonBody = JSON.serialize(payload);
        
        DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(
            'test-endpoint',
            'POST',
            jsonBody,
            acc.Id
        );
        
        HttpResponse errorResp = new HttpResponse();
        errorResp.setStatusCode(500);
        errorResp.setBody('{"error":"Internal Server Error"}');
        
        Test.startTest();
        integration.processResponse(errorResp);
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Integration executeAndReturnResponse
    @isTest
    static void test_Integration_ExecuteAndReturnResponse() {
        Account acc = createTestAccount(false, false, true);
        
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        String jsonBody = JSON.serialize(payload);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"success": true}'));
        
        DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(
            'test-endpoint',
            'POST',
            jsonBody,
            acc.Id
        );
        
        Test.startTest();
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
        
        System.assertNotEquals(null, response);
        System.assertEquals(201, response.getStatusCode());
    }
    
    // Test DRC_NBC_Account_BC_Callout_Queueable with successful callout and status update
    @isTest
    static void test_Queueable_SuccessCalloutWithStatusUpdate() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"success": true}'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Queueable(ord.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Callout_Second_Queue with 200 response
    @isTest
    static void test_SecondQueue_Success200() {
        Account acc = createTestAccount(false, false, true);
        Order ord = createTestOrder(acc.Id);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, '{"success": true}'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Account_BC_Callout_Second_Queue(ord.Id, acc.Id));
        Test.stopTest();
    }
    
    // Test DRC_NBC_Account_BC_Integration with 400 error
    @isTest
    static void test_Integration_ProcessResponse_Error400() {
        Account acc = createTestAccount(false, false, true);
        
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        String jsonBody = JSON.serialize(payload);
        
        DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(
            'test-endpoint',
            'POST',
            jsonBody,
            acc.Id
        );
        
        HttpResponse errorResp = new HttpResponse();
        errorResp.setStatusCode(400);
        errorResp.setBody('{"error":"Bad Request"}');
        
        Test.startTest();
        integration.processResponse(errorResp);
        Test.stopTest();
    }
    
    // Test payload mapping with all fields
    @isTest
    static void test_mapAccountToPayload_AllFields() {
        Account acc = createTestAccount(false, false, true);
        acc = [SELECT Id, Name, DRC_NBC_PAN_No__c, DRC_NBC_Payment_Term_Code__c, 
               DRC_NBC_Customer_Number__c, CurrencyIsoCode, Phone, 
               DRC_NBC_Account_Email_Email__c, BillingCity, BillingCountry, 
               BillingPostalCode, BillingState, BillingStateCode, 
               BillingStreet, DRC_NBC_GST_Number__c 
               FROM Account WHERE Id = :acc.Id];
        
        Test.startTest();
        DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
        Test.stopTest();
    }
}