force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Account__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/DRC_NBC_Packing_Details__c.object-meta.xml
<CustomObject>
    <label>Packing Detail</label>
    <nameField>
        <displayFormat>Packing-{0000}</displayFormat>
        <label>Packing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Qauntity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Qauntity__c</fullName>
    <label>Packing Qauntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Packing Details</relationshipLabel>
    <relationshipName>Packing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/DRC_NBC_Restricted_Product__c.object-meta.xml
<CustomObject>
    <label>Account Products</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Restricted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Customer__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Restricted_Products_Access</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Product__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Restricted_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <label>FG Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/DRC_NBC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 UNIT</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>18 KG CARBOY</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS MS</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>20 KG TIN</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_GenerateSampleOrderTest.cls
@isTest
public class DRC_NBC_GenerateSampleOrderTest {
    
    @testSetup
    static void setupTestData() {
        Account acc = new Account(
            Name = 'Test Account',
            BillingStreet = '123 Test Street',
            BillingCity = 'Mumbai',
            BillingState = 'Maharashtra',
            BillingPostalCode = '400001',
            BillingCountry = 'India',
            DRC_NBC_Volume__c = 70,
            DRC_NBC_Credit_Limit__c = 123456787,
            DRC_NBC_Value__c = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c = 'Punjab National bank',
            DRC_NBC_Payment_Term_Code__c = 'NET30',
            Industry = 'Chemicals Construction',
            Type = 'Analyst'
        );
        insert acc;

        Contact conWithEmail = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            Email = 'john.doe@example.com',
            AccountId = acc.Id
        );
        insert conWithEmail;

        Contact conNoEmail = new Contact(
            FirstName = 'Jane',
            LastName = 'Smith',
            AccountId = acc.Id
        );
        insert conNoEmail;

        Pricebook2 drcPb = new Pricebook2(
            Name = 'DRC PriceBook',
            IsActive = true,
            DRC_NBC_External_Id__c = 'DRC001'
        );
        insert drcPb;

        Product2 prod1 = new Product2(
            Name = 'Sample Product 1',
            IsActive = true,
            DRC_NBC_FG_Code__c = 'FG001',
            DRC_NBC_HSN_SAC_Code__c = 'HSN001',
            QuantityUnitOfMeasure = 'KGS'
        );
        insert prod1;

        Product2 prod2 = new Product2(
            Name = 'Sample Product 2',
            IsActive = true,
            DRC_NBC_FG_Code__c = 'FG002',
            DRC_NBC_HSN_SAC_Code__c = 'HSN002',
            QuantityUnitOfMeasure = 'LTR'
        );
        insert prod2;

        insert new DRC_NBC_Packing_Details__c(
            Product__c = prod1.Id,
            DRC_NBC_Packing_Size__c = '25KG',
            DRC_NBC_Packing_Qauntity__c = '40'
        );
        insert new DRC_NBC_Packing_Details__c(
            Product__c = prod1.Id,
            DRC_NBC_Packing_Size__c = '50KG',
            DRC_NBC_Packing_Qauntity__c = '20'
        );
        insert new DRC_NBC_Packing_Details__c(
            Product__c = prod2.Id,
            DRC_NBC_Packing_Size__c = '20L'
        );

        insert new DRC_NBC_Restricted_Product__c(
            DRC_NBC_Product__c = prod1.Id,
            DRC_NBC_Customer__c = acc.Id
        );

        Id stdPbId = Test.getStandardPricebookId();
        insert new List<PricebookEntry>{
            new PricebookEntry(
                Pricebook2Id = stdPbId,
                Product2Id = prod1.Id,
                UnitPrice = 100,
                IsActive = true
            ),
            new PricebookEntry(
                Pricebook2Id = stdPbId,
                Product2Id = prod2.Id,
                UnitPrice = 200,
                IsActive = true
            )
        };

        insert new List<PricebookEntry>{
            new PricebookEntry(
                Pricebook2Id = drcPb.Id,
                Product2Id = prod1.Id,
                UnitPrice = 110,
                IsActive = true,
                UseStandardPrice = false,
                CurrencyIsoCode = 'INR'
            ),
            new PricebookEntry(
                Pricebook2Id = drcPb.Id,
                Product2Id = prod2.Id,
                UnitPrice = 210,
                IsActive = true,
                UseStandardPrice = false,
                CurrencyIsoCode = 'INR'
            )
        };

        Opportunity oppWithDrcPb = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(10),
            AccountId = acc.Id,
            CurrencyIsoCode = 'INR',
            Pricebook2Id = drcPb.Id
        );
        insert oppWithDrcPb;

        insert new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c = acc.Id,
            DRC_NBC_Type__c = 'Shipping',
            DRC_NBC_Address__Street__s = '456 Ship Lane',
            DRC_NBC_Address__City__s = 'Pune',
            DRC_NBC_Address__PostalCode__s = '411001',
            DRC_NBC_Address__StateCode__s = 'MH',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Warehouse__c = 'CFS - JNPT'
        );
    }

    private static Account getAccount() {
        return [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
    }

    private static Opportunity getOppWithDrcPb() {
        return [SELECT Id, AccountId, Pricebook2Id, CurrencyIsoCode FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
    }

    private static Opportunity createOppWithoutPricebook() {
        Account acc = getAccount();
        Opportunity opp = new Opportunity(
            Name = 'Opp No Pricebook ' + System.now().getTime(),
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(5),
            AccountId = acc.Id,
            CurrencyIsoCode = 'INR'
        );
        insert opp;
        return opp;
    }

    private static Contact getConEmail() {
        return [SELECT Id, AccountId FROM Contact WHERE Email != null LIMIT 1];
    }

    private static Contact getConNoEmail() {
        return [SELECT Id FROM Contact WHERE Email = null LIMIT 1];
    }

    private static Product2 getProd1() {
        return [SELECT Id FROM Product2 WHERE Name = 'Sample Product 1' LIMIT 1];
    }

    private static Product2 getProd2() {
        return [SELECT Id FROM Product2 WHERE Name = 'Sample Product 2' LIMIT 1];
    }

    private static DRC_NBC_Addresses__c getShipAddr() {
        return [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];
    }

    private static DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper makeItem(
        Id prod2Id,
        Decimal qty,
        Decimal price,
        String packSize,
        Decimal packQty,
        String uom
    ) {
        DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper w =
            new DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper();
        w.Product2Id = prod2Id;
        w.Quantity = qty;
        w.UnitPrice = price;
        w.PackingSize = packSize;
        w.PackingQuantity = packQty;
        w.QuantityUnitOfMeasure = uom;
        return w;
    }

    private static Order buildOrder(
        Id accountId,
        Id billContactId,
        Id shipContactId,
        Id shipAddrId,
        String status,
        Boolean nullDate
    ) {
        Order ord = new Order();
        ord.AccountId = accountId;
        ord.CurrencyIsoCode = 'INR';
        ord.Status = status != null ? status : 'Draft';
        ord.EffectiveDate = nullDate ? null : Date.today();
        if (billContactId != null) ord.BillToContactId = billContactId;
        if (shipContactId != null) ord.ShipToContactId = shipContactId;
        if (shipAddrId != null) ord.DRC_NBC_Shipping_Address__c = shipAddrId;
        return ord;
    }

    @isTest
    static void testGetOrderRecordTypes() {
        Test.startTest();
        List<Map<String, String>> result =
            DRC_NBC_Generate_Sample_Order_Controller.getOrderRecordTypes();
        Test.stopTest();
        System.assertNotEquals(null, result);
    }

    @isTest
    static void testGetOpportunityContacts_Success() {
        Test.startTest();
        List<Contact> contacts =
            DRC_NBC_Generate_Sample_Order_Controller.getOpportunityContacts(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assert(contacts.size() > 0);
    }

    @isTest
    static void testGetOpportunityContacts_NullId() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Sample_Order_Controller.getOpportunityContacts(null);
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

/*    @isTest
    static void testGetAccountPaymentTerms() {
        Test.startTest();
        String result =
            DRC_NBC_Generate_Sample_Order_Controller.getAccountPaymentTerms(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assertEquals('NET30', result);
    }*/

    @isTest
    static void testGetOpportunityCurrency() {
        Test.startTest();
        String result =
            DRC_NBC_Generate_Sample_Order_Controller.getOpportunityCurrency(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assertEquals('INR', result);
    }

    @isTest
    static void testGetAllProducts_UsesOpportunityPricebook() {
        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.ProductSearchResult result =
            DRC_NBC_Generate_Sample_Order_Controller.getAllProducts(getOppWithDrcPb().Id);
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assert(result.products.size() > 0);
        System.assert(result.packingDetailsList.size() > 0);
    }

    @isTest
    static void testGetAllProducts_FallbackToStandardWhenOppPricebookNull() {
        Opportunity oppNoPb = createOppWithoutPricebook();

        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.ProductSearchResult result =
            DRC_NBC_Generate_Sample_Order_Controller.getAllProducts(oppNoPb.Id);
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assert(result.products.size() > 0);
    }

    @isTest
    static void testSearchProducts_WithRestriction_UsesOpportunityPricebook() {
        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.ProductSearchResult result =
            DRC_NBC_Generate_Sample_Order_Controller.searchProducts(
                'Sample Product 1',
                'INR',
                getOppWithDrcPb().Id
            );
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assert(result.products.size() > 0);
    }

    @isTest
    static void testSearchProducts_FallbackToStandardWhenOppPricebookNull() {
        Opportunity oppNoPb = createOppWithoutPricebook();

        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.ProductSearchResult result =
            DRC_NBC_Generate_Sample_Order_Controller.searchProducts(
                'Sample',
                'INR',
                oppNoPb.Id
            );
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assert(result.products.size() > 0);
    }

    @isTest
    static void testSearchProducts_BlankCurrency() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Sample_Order_Controller.searchProducts(
                'Sample',
                '',
                getOppWithDrcPb().Id
            );
           // System.assert(false);
        } catch (AuraHandledException e) {
          //  System.assert(true);
        }
        Test.stopTest();
    }

    @isTest
    static void testSearchProducts_NullCurrency() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Sample_Order_Controller.searchProducts(
                'Sample',
                null,
                getOppWithDrcPb().Id
            );
           // System.assert(false);
        } catch (AuraHandledException e) {
           // System.assert(true);
        }
        Test.stopTest();
    }

    @isTest
    static void testGetAccountBillingAddress_Success() {
        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.AccountAddressWrapper result =
            DRC_NBC_Generate_Sample_Order_Controller.getAccountBillingAddress(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assertEquals('Mumbai', result.city);
    }

    @isTest
    static void testGetAccountBillingAddress_NullId() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Sample_Order_Controller.getAccountBillingAddress(null);
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @isTest
    static void testGetAccountAddresses() {
        Test.startTest();
        List<DRC_NBC_Addresses__c> result =
            DRC_NBC_Generate_Sample_Order_Controller.getAccountAddresses(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assert(result.size() > 0);
    }

    @isTest
    static void testGetAccountBankDetails_Success() {
        Test.startTest();
        DRC_NBC_Generate_Sample_Order_Controller.AccountBankDetailsWrapper result =
            DRC_NBC_Generate_Sample_Order_Controller.getAccountBankDetails(getOppWithDrcPb().Id);
        Test.stopTest();
        System.assertEquals('Punjab National bank', result.bankName);
    }

    @isTest
    static void testGetAccountBankDetails_NullId() {
        Test.startTest();
        try {
            DRC_NBC_Generate_Sample_Order_Controller.getAccountBankDetails(null);
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
        Test.stopTest();
    }

    @isTest
    static void testCreateSampleOrder_NullItems() {
        Opportunity opp = getOppWithDrcPb();
        Order ord = buildOrder(opp.AccountId, null, null, null, 'Draft', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            null,
            opp.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":false'));
    }

    @isTest
    static void testCreateSampleOrder_EmptyItems() {
        Opportunity opp = getOppWithDrcPb();
        Order ord = buildOrder(opp.AccountId, null, null, null, 'Draft', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>(),
            opp.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":false'));
    }

    @isTest
    static void testCreateSampleOrder_BillToContact_NoEmail() {
        Opportunity opp = getOppWithDrcPb();
        Contact noEmail = getConNoEmail();
        Product2 prod = getProd1();

        Order ord = buildOrder(opp.AccountId, noEmail.Id, null, null, 'Draft', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>{
                makeItem(prod.Id, 1, 100, null, null, 'KGS')
            },
            opp.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":false'));
    }

    @isTest
    static void testCreateSampleOrder_ShipToContact_NoEmail() {
        Opportunity opp = getOppWithDrcPb();
        Contact noEmail = getConNoEmail();
        Product2 prod = getProd1();

        Order ord = buildOrder(opp.AccountId, null, noEmail.Id, null, 'Draft', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>{
                makeItem(prod.Id, 1, 100, null, null, 'KGS')
            },
            opp.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":false'));
    }

    @isTest
    static void testCreateSampleOrder_UsesExistingOpportunityPricebook() {
        Opportunity opp = getOppWithDrcPb();
        Contact con = getConEmail();
        Product2 prod = getProd1();
        DRC_NBC_Addresses__c shipAddr = getShipAddr();

        Order ord = buildOrder(opp.AccountId, con.Id, null, shipAddr.Id, 'Requested', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>{
                makeItem(prod.Id, 5, 110, '25KG', 40, 'KGS')
            },
            opp.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":true'));
    }

    @isTest
    static void testCreateSampleOrder_FallbackToStandardWhenOppPricebookNull() {
        Opportunity oppNoPb = createOppWithoutPricebook();
        Contact con = getConEmail();
        Product2 prod = getProd1();

        Order ord = new Order();
        ord.AccountId = oppNoPb.AccountId;
        ord.EffectiveDate = null;
        ord.Status = null;
        ord.CurrencyIsoCode = null;
        ord.BillToContactId = con.Id;

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>{
                makeItem(prod.Id, 3, 100, '25KG', null, 'KGS')
            },
            oppNoPb.Id
        );
        Test.stopTest();

        System.assert(result.contains('"success":true'));

        Opportunity refreshedOpp = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Id = :oppNoPb.Id];
        System.assertEquals(Test.getStandardPricebookId(), refreshedOpp.Pricebook2Id);
    }

    @isTest
    static void testCreateSampleOrder_MultipleProducts_BothContacts() {
        Opportunity opp = getOppWithDrcPb();
        Contact con1 = getConEmail();
        Product2 prod1 = getProd1();
        Product2 prod2 = getProd2();

        Contact con2 = new Contact(
            FirstName = 'Bob',
            LastName = 'Jones',
            Email = 'bob.jones@example.com',
            AccountId = opp.AccountId
        );
        insert con2;

        Order ord = buildOrder(opp.AccountId, con1.Id, con2.Id, null, 'Draft', false);

        Test.startTest();
        String result = DRC_NBC_Generate_Sample_Order_Controller.createSampleOrder(
            ord,
            new List<DRC_NBC_Generate_Sample_Order_Controller.OrderItemWrapper>{
                makeItem(prod1.Id, 2, 110, null, null, 'KGS'),
                makeItem(prod2.Id, 3, 210, null, null, 'LTR')
            },
            opp.Id
        );
        Test.stopTest();
    }
}