force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Account__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>GST Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/DRC_NBC_Packing_Details__c.object-meta.xml
<CustomObject>
    <label>Packing Detail</label>
    <nameField>
        <displayFormat>Packing-{0000}</displayFormat>
        <label>Packing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Qauntity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Qauntity__c</fullName>
    <label>Packing Qauntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Packing Details</relationshipLabel>
    <relationshipName>Packing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/DRC_NBC_Restricted_Product__c.object-meta.xml
<CustomObject>
    <label>Account Products</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Restricted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Customer__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Restricted_Products_Access</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Product__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Restricted_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_User__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Restricted_Products_Access</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 UNIT</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>18 KG CARBOY</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS MS</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>20 KG TIN</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
            <value>
                <fullName>AL 5 KG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Lead_Time__c</fullName>
    <description>Lead time</description>
    <label>Lead Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Quotes (Shipping Address Id)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DRC_NBC_Packing_Qauntity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Qauntity__c</fullName>
    <label>Packing Qauntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DRC_NBC_ProductsControllerTest.cls
@isTest
private class DRC_NBC_ProductsControllerTest {
    
    @TestSetup
    static void setupTestData() {
        Account acc = new Account(
            Name = 'Test Account',
            DRC_NBC_Customer_Number__c = 'CUST12345',
            CurrencyIsoCode = 'INR',
            Phone = '1234567890',
            AccountNumber = 'A123',
            DRC_NBC_PAN_No__c = 'AWVPY9594J',
            DRC_NBC_GST_Number__c = '27AWVPY9594J1ZY',
            DRC_NBC_Payment_Term_Code__c = 'PDC90',
            DRC_NBC_Account_Email_Email__c = 'test@example.com',
            BillingStreet = '123 Street',
            BillingCity = 'City',
            BillingCountry = 'India',
            BillingCountryCode = 'IN',
            BillingPostalCode = '462002',
            BillingState = 'Maharashtra',
            BillingStateCode = 'MH',
            DRC_NBC_Volume__c = 70,
            DRC_NBC_Credit_Limit__c = 123456787,
            DRC_NBC_Value__c = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c = 'Punjab National bank',
            Industry = 'Chemicals Construction',
            Type = 'Analyst'
        );
        insert acc;
        
        Contact con = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            AccountId = acc.Id,
            Email = 'test@test.com',
            Phone = '9999999999'
        );
        insert con;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = acc.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30)
        );
        insert opp;
        
        Id standardPricebookId = Test.getStandardPricebookId();
        
        Quote q = new Quote(
            Name = 'Test Quote',
            OpportunityId = opp.Id,
            Pricebook2Id = standardPricebookId,
            Status = 'Draft',
            DRC_NBC_Type__c = 'Domestic',
            ExpirationDate = Date.today().addDays(30),
            ContactId = con.Id,
            Email = 'test@test.com',
            Phone = '9999999999',
            BillingStreet = '123 Main St',
            BillingCity = 'Mumbai',
            BillingPostalCode = '400001',
            BillingCountry = 'India'
        );
        insert q;
        
        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true,
            Family = 'Test Family',
            QuantityUnitOfMeasure = 'Each',
            Description = 'Test Product Description'
        );
        insert prod;
        
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert pbe;
        
        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = prod.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 5,
            UnitPrice = 100,
            DRC_NBC_Packing_Size__c = 'AL 1 KG',
            DRC_NBC_Packing_Qauntity__c = '5'
        );
        insert qli;
        
        DRC_NBC_Addresses__c addr = new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c = acc.Id,
            DRC_NBC_Type__c = 'Shipping',
            DRC_NBC_Address__Street__s = '456 Ship St',
            DRC_NBC_Address__City__s = 'Pune',
            DRC_NBC_Address__StateCode__s = 'MH',
            DRC_NBC_Address__PostalCode__s = '411001',
            DRC_NBC_Address__CountryCode__s = 'IN'
        );
        insert addr;
        
        // New setup required for updated controller
        List<DRC_NBC_Packing_Details__c> packingDetails = new List<DRC_NBC_Packing_Details__c>{
            new DRC_NBC_Packing_Details__c(
                Product__c = prod.Id,
                DRC_NBC_Packing_Size__c = 'AL 1 KG',
                DRC_NBC_Packing_Qauntity__c = '5'
            ),
                new DRC_NBC_Packing_Details__c(
                    Product__c = prod.Id,
                    DRC_NBC_Packing_Size__c = 'AL 5 KG',
                    DRC_NBC_Packing_Qauntity__c = '10'
                )
                };
                    insert packingDetails;
    }
    
    private static Id getQuoteId() {
        return [SELECT Id FROM Quote LIMIT 1].Id;
    }
    
    private static Id getAccountId() {
        return [SELECT Id FROM Account LIMIT 1].Id;
    }
    
    private static Id getProductId() {
        return [SELECT Id FROM Product2 LIMIT 1].Id;
    }
    
    private static Id getPricebookEntryId() {
        return [SELECT Id FROM PricebookEntry LIMIT 1].Id;
    }
    
    private static Id getShippingAddressId() {
        return [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1].Id;
    }
    
    @isTest
    static void testGetAccountContacts_Success() {
        Test.startTest();
        List<Contact> contacts = DRC_NBC_ProductsController.getAccountContacts(getQuoteId());
        Test.stopTest();
        
        System.assertEquals(1, contacts.size());
        System.assertEquals('test@test.com', contacts[0].Email);
    }
    
    @isTest
    static void testGetAccountContacts_BlankQuoteId() {
        Boolean isThrown = false;
        
        Test.startTest();
        try {
            DRC_NBC_ProductsController.getAccountContacts(null);
        } catch (AuraHandledException e) {
            isThrown = true;
            // System.assert(e.getMessage().contains('Quote ID is required.'));
        }
        Test.stopTest();
        
        System.assertEquals(true, isThrown);
    }
    
    @isTest
    static void testGetQuoteRecord_Success() {
        Test.startTest();
        Quote q = DRC_NBC_ProductsController.getQuoteRecord(getQuoteId());
        Test.stopTest();
        
        System.assertNotEquals(null, q);
        System.assertEquals('Draft', q.Status);
    }
    
    @isTest
    static void testGetQuoteRecord_BlankId() {
        Boolean isThrown = false;
        
        Test.startTest();
        try {
            DRC_NBC_ProductsController.getQuoteRecord(null);
        } catch (AuraHandledException e) {
            isThrown = true;
            //  System.assert(e.getMessage().contains('Quote ID is required.'));
        }
        Test.stopTest();
        
        System.assertEquals(true, isThrown);
    }
    
    @isTest
    static void testGetAccountAddresses_Success() {
        Test.startTest();
        DRC_NBC_ProductsController.AddressListWrapper result =
            DRC_NBC_ProductsController.getAccountAddresses(getAccountId());
        Test.stopTest();
        
        System.assertEquals(1, result.billingAddresses.size());
        System.assertEquals(1, result.shippingAddresses.size());
    }
    
    @isTest
    static void testGetAccountAddresses_NoShippingAddresses() {
        Account newAcc = new Account(
            Name = 'Test Account 2',
            DRC_NBC_Customer_Number__c = 'CUST67890',
            CurrencyIsoCode = 'USD',
            Phone = '9876543210',
            AccountNumber = 'A456',
            DRC_NBC_PAN_No__c = 'BNZPY1234K',
            DRC_NBC_GST_Number__c = '29BNZPY1234K1ZX',
            DRC_NBC_Payment_Term_Code__c = 'PDC90',
            DRC_NBC_Account_Email_Email__c = 'demo456@example.com',
            BillingStreet = '456 Park Avenue',
            BillingCity = 'Mumbai',
            BillingCountry = 'India',
            BillingCountryCode = 'IN',
            BillingPostalCode = '400001',
            BillingState = 'Karnataka',
            BillingStateCode = 'KA',
            DRC_NBC_Volume__c = 120,
            DRC_NBC_Credit_Limit__c = 987654321,
            DRC_NBC_Value__c = 1500,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1234567890123456',
            DRC_NBC_Consignee_Bank_Address__c = 'MG Road, Bengaluru',
            DRC_NBC_Consignee_Bank_IFSC_Code__c = 'SBIN0001234',
            DRC_NBC_Consignee_Bank_Name__c = 'State Bank of India',
            Industry = 'Chemicals Construction',
            Type = 'Analyst'
        );
        insert newAcc;
        
        Test.startTest();
        DRC_NBC_ProductsController.AddressListWrapper result =
            DRC_NBC_ProductsController.getAccountAddresses(newAcc.Id);
        Test.stopTest();
        
        System.assertEquals(1, result.billingAddresses.size());
        System.assertEquals(0, result.shippingAddresses.size());
    }
    
    @isTest
    static void testUpdateQuoteRecord_Success() {
        Map<String, Object> fields = new Map<String, Object>{
            'Name' => 'Updated Quote Name',
                'Description' => 'Updated Description',
                'Status' => 'Draft',
                'Email' => 'updated@test.com',
                'Phone' => '8888888888',
                'Fax' => '0000000000',
                'BillingStreet' => '789 New St',
                'BillingCity' => 'Chennai',
                'BillingPostalCode' => '600001',
                'BillingCountry' => 'India',
                'ShippingStreet' => '789 Ship St',
                'ShippingCity' => 'Chennai',
                'ShippingPostalCode' => '600002',
                'ShippingCountry' => 'India'
                };
                    
                    Test.startTest();
        DRC_NBC_ProductsController.updateQuoteRecord(getQuoteId(), fields);
        Test.stopTest();
        
        Quote updatedQuote = [
            SELECT Name, Description, Email, Phone, Fax, BillingCity, ShippingCity
            FROM Quote
            WHERE Id = :getQuoteId()
        ];
        
        System.assertEquals('Updated Quote Name', updatedQuote.Name);
        System.assertEquals('Updated Description', updatedQuote.Description);
        System.assertEquals('updated@test.com', updatedQuote.Email);
        System.assertEquals('Chennai', updatedQuote.BillingCity);
        System.assertEquals('Chennai', updatedQuote.ShippingCity);
    }
    
    @isTest
    static void testUpdateQuoteRecord_BlankQuoteId() {
        Boolean isThrown = false;
        
        Test.startTest();
        try {
            DRC_NBC_ProductsController.updateQuoteRecord(
                null,
                new Map<String, Object>{ 'Name' => 'Test' }
            );
        } catch (AuraHandledException e) {
            isThrown = true;
            // System.assert(e.getMessage().contains('Quote ID is missing.'));
        }
        Test.stopTest();
        
        System.assertEquals(true, isThrown);
    }
    
    @isTest
    static void testUpdateQuoteRecord_EmptyFields() {
        Boolean isThrown = false;
        
        Test.startTest();
        try {
            DRC_NBC_ProductsController.updateQuoteRecord(getQuoteId(), new Map<String, Object>());
        } catch (AuraHandledException e) {
            isThrown = true;
            // System.assert(e.getMessage().contains('No fields provided to update.'));
        }
        Test.stopTest();
        
        System.assertEquals(true, isThrown);
    }
    
    @isTest
    static void testUpdateQuoteRecord_DateFields() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        
        Map<String, Object> fields = new Map<String, Object>{
            'ExpirationDate' => Date.today().addDays(60),
                'DRC_NBC_Lead_Time__c' => String.valueOf(Date.today().addDays(15)),
                'ContactId' => con.Id
                };
                    
                    Test.startTest();
        DRC_NBC_ProductsController.updateQuoteRecord(getQuoteId(), fields);
        Test.stopTest();
        
        Quote updatedQuote = [
            SELECT ExpirationDate, DRC_NBC_Lead_Time__c, ContactId
            FROM Quote
            WHERE Id = :getQuoteId()
        ];
        
        System.assertEquals(Date.today().addDays(60), updatedQuote.ExpirationDate);
        System.assertEquals(Date.today().addDays(15), updatedQuote.DRC_NBC_Lead_Time__c);
        System.assertEquals(con.Id, updatedQuote.ContactId);
    }
    
    
    @isTest
    static void testGetRestrictedProductsAccessList_NoData() {
        Test.startTest();
        List<DRC_NBC_Restricted_Product__c> result =
            DRC_NBC_ProductsController.getrestrictedProductsAccessList(getQuoteId());
        Test.stopTest();
    }
    
    @isTest
    static void testGetRestrictedProductsAccessList_WithData() {
        DRC_NBC_Restricted_Product__c restricted = new DRC_NBC_Restricted_Product__c(
            DRC_NBC_Customer__c = getAccountId(),
            DRC_NBC_Product__c = getProductId(),
            DRC_NBC_User__c = UserInfo.getUserId()
        );
        insert restricted;
        
        Test.startTest();
        List<DRC_NBC_Restricted_Product__c> result =
            DRC_NBC_ProductsController.getrestrictedProductsAccessList(getQuoteId());
        Test.stopTest();
    }
    
    @isTest
    static void testSaveQLIData_DeleteQLI() {
        Quote q = [SELECT Id, CurrencyIsoCode FROM Quote LIMIT 1];
        QuoteLineItem existingQli = [SELECT Id FROM QuoteLineItem WHERE QuoteId = :q.Id LIMIT 1];
        
        Quote quoteData = new Quote(
            Id = q.Id,
            Name = 'Test Quote',
            ExpirationDate = Date.today().addDays(30),
            Status = 'Draft',
            CurrencyIsoCode = q.CurrencyIsoCode
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.saveQLIData(
            new List<QuoteLineItem>(),
            new List<String>{ existingQli.Id },
            quoteData
        );
        Test.stopTest();
    }
    
    @isTest
    static void testSaveQLIData_WithShippingAddressAndPacking() {
        Quote q = [SELECT Id, CurrencyIsoCode FROM Quote LIMIT 1];
        Id productId = getProductId();
        Id pbeId = getPricebookEntryId();
        Id shippingAddressId = getShippingAddressId();
        
        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = productId,
            PricebookEntryId = pbeId,
            Quantity = 3,
            UnitPrice = 75,
            DRC_NBC_Packing_Size__c = 'AL 5 KG',
            DRC_NBC_Packing_Qauntity__c = '10'
        );
        
        Quote quoteData = new Quote(
            Id = q.Id,
            Name = 'Test Quote Shipping',
            ExpirationDate = Date.today().addDays(30),
            Status = 'Draft',
            CurrencyIsoCode = q.CurrencyIsoCode,
            DRC_NBC_Shipping_Address_Id__c = shippingAddressId
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.saveQLIData(
            new List<QuoteLineItem>{ qli },
            new List<String>(),
            quoteData
        );
        Test.stopTest();
    }
    
    @isTest
    static void testSaveQLIData_WithPackingFields() {
        Quote q = [SELECT Id, CurrencyIsoCode FROM Quote LIMIT 1];
        
        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = getProductId(),
            PricebookEntryId = getPricebookEntryId(),
            Quantity = 5,
            UnitPrice = 100,
            DRC_NBC_Packing_Size__c = 'AL 1 KG',
            DRC_NBC_Packing_Qauntity__c = '5'
        );
        
        Quote quoteData = new Quote(
            Id = q.Id,
            Name = 'Test Quote Packing',
            ExpirationDate = Date.today().addDays(30),
            Status = 'Draft',
            CurrencyIsoCode = q.CurrencyIsoCode
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.saveQLIData(
            new List<QuoteLineItem>{ qli },
            new List<String>(),
            quoteData
        );
        Test.stopTest();       
    }
    
    @isTest
    static void testSaveQLIData_NullQuoteData() {
        Quote q = [SELECT Id FROM Quote LIMIT 1];
        
        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = q.Id,
            Product2Id = getProductId(),
            PricebookEntryId = getPricebookEntryId(),
            Quantity = 1,
            UnitPrice = 50
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.saveQLIData(
            new List<QuoteLineItem>{ qli },
            new List<String>(),
            null
        );
        Test.stopTest();
    }
    
    // saveQLIData catches Exception and does not rethrow,
    // so this test only validates that invalid input is handled without failing the test.
    @isTest
    static void testSaveQLIData_InvalidInputHandledInternally() {
        Quote q = [SELECT Id, CurrencyIsoCode FROM Quote LIMIT 1];
        
        Integer beforeCount = [SELECT COUNT() FROM QuoteLineItem WHERE QuoteId = :q.Id];
        
        QuoteLineItem badQli = new QuoteLineItem(
            QuoteId = q.Id,
            PricebookEntryId = getPricebookEntryId(),
            Quantity = 1,
            UnitPrice = 50
        );
        
        Quote quoteData = new Quote(
            Id = q.Id,
            Name = 'Test',
            ExpirationDate = Date.today().addDays(30),
            Status = 'Draft',
            CurrencyIsoCode = q.CurrencyIsoCode
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.saveQLIData(
            new List<QuoteLineItem>{ badQli },
            new List<String>(),
            quoteData
        );
        Test.stopTest();
        
        Integer afterCount = [SELECT COUNT() FROM QuoteLineItem WHERE QuoteId = :q.Id];
        System.assertEquals(beforeCount, afterCount);
    }
    
    @isTest
    static void testAddressWrapper() {
        Test.startTest();
        DRC_NBC_ProductsController.AddressWrapper wrapper =
            new DRC_NBC_ProductsController.AddressWrapper(UserInfo.getUserId(), 'Test Label');
        Test.stopTest();
    }
    
    @isTest
    static void testQliWrapper() {
        Test.startTest();
        DRC_NBC_ProductsController.qliWrapper wrapper =
            new DRC_NBC_ProductsController.qliWrapper();
        wrapper.qlis = new List<QuoteLineItem>();
        wrapper.productsList = new List<PricebookEntry>();
        wrapper.packingDetailsMap =
            new Map<Id, List<DRC_NBC_ProductsController.PackingDetailWrapper>>();
        Test.stopTest();
    }
    
    @isTest
    static void testGetExistingQLIs_BaseCoverage() {
        Id quoteId = getQuoteId();
        Id productId = getProductId();
        
        Test.startTest();
        DRC_NBC_ProductsController.qliWrapper result =
            DRC_NBC_ProductsController.getExistingQLIs(quoteId);
        Test.stopTest();
    }
  
    @isTest
    static void testGetExistingQLIs_WithRestrictedProducts_CoversRestrictedBranch() {
        Id quoteId = getQuoteId();
        Id accountId = getAccountId();
        Id productId = getProductId();
        
        insert new DRC_NBC_Restricted_Product__c(
            DRC_NBC_Customer__c = accountId,
            DRC_NBC_Product__c = productId,
            DRC_NBC_User__c = UserInfo.getUserId()
        );
        
        Test.startTest();
        DRC_NBC_ProductsController.qliWrapper result =
            DRC_NBC_ProductsController.getExistingQLIs(quoteId);
        Test.stopTest();
    }
}