force-app/main/default/objects/Account/fields/DRC_NBC_BC_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Approval_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved In BC?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Account__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_Account_BC_Callout_Second_Queue.cls
public class DRC_NBC_Account_BC_Callout_Second_Queue implements System.Queueable, Database.AllowsCallouts {
    
    private Id orderId;
    private Id accountId;
    
    public DRC_NBC_Account_BC_Callout_Second_Queue(Id orderId, Id accountId) {
        this.orderId = orderId;
        this.accountId = accountId;
    }
    
    public void execute(System.QueueableContext context) {
        try {
            Account acc = DRC_NBC_Account_BC_Callout.getAccountDetails(accountId);
            
           /* if (acc.DRC_NBC_BC_Approval_Status__c) {
                System.enqueueJob(new DRC_NBC_Order_BC_Callout(orderId));
                return;
            }*/
            
          /*  Boolean hasShippingAddressInIndia = false;
            for (DRC_NBC_Addresses__c addr : acc.Address__r) {
                if (addr.DRC_NBC_Type__c == 'Shipping' &&
                    addr.DRC_NBC_Address__CountryCode__s == 'IND') {
                    hasShippingAddressInIndia = true;
                    break;
                }
            }*/
            
            DRC_NBC_Integration_Payload.CustomerPayload payload = DRC_NBC_Account_BC_Callout.mapAccountToPayload(acc);
            String jsonBody = JSON.serialize(payload, true);
            String endpoint = DRC_NBC_BC_Callout_Utility.getConfig().DRC_NBC_Endpoint__c;
            
            DRC_NBC_Account_BC_Integration integration = new DRC_NBC_Account_BC_Integration(endpoint, 'POST', jsonBody, accountId);
            HttpResponse response = integration.executeAndReturnResponse();
            
            if (response != null && response.getStatusCode() == 201) {
                System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(orderId));
              /*  if (hasShippingAddressInIndia) {
                    System.enqueueJob(new DRC_NBC_Shipping_BC_Callout(accountId, orderId));
                }*/
                DRC_NBC_Account_BC_Callout.updatePostedStatus(accountId);
            }
            
        } catch (Exception e) {
            DRC_NBC_API_Log_Handler.createApiLog(
                'DRC_NBC_Account_BC_Callout_Second_Queue',
                null,
                null,
                'QueueableJob',
                e.getMessage(),
                null,
                e.getStackTraceString(),
                'Error',
                accountId
            );
        }
    }
}