force-app/main/default/objects/Account/fields/DRC_NBC_BC_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Approval_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved In BC?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <formula>CASE(
TEXT(DRC_NBC_Payment_Terms_Description__c),

&quot;PDC 90 days&quot;, &quot;PDC90&quot;,
&quot;PDC 60 days&quot;, &quot;PDC60&quot;,
&quot;PDC 45 days&quot;, &quot;PDC45&quot;,
&quot;PDC 30 days&quot;, &quot;PDC30&quot;,

&quot;Irrevocable LC at sight&quot;, &quot;IRRELC&quot;,
&quot;Irrevocable LC 90 days&quot;, &quot;IRRLC90&quot;,
&quot;Irrevocable LC 60 days&quot;, &quot;IRRLC60&quot;,
&quot;Irrevocable LC 45 days&quot;, &quot;IRRLC45&quot;,
&quot;Irrevocable LC 30 days&quot;, &quot;IRRLC30&quot;,

&quot;Free sample&quot;, &quot;FOC&quot;,

&quot;DP AT SIGHT&quot;, &quot;DPSIGHT&quot;,
&quot;DP 90 days&quot;, &quot;DP90&quot;,
&quot;DP 60 days&quot;, &quot;DP60&quot;,
&quot;DP 30 days&quot;, &quot;DP30&quot;,

&quot;DA 90 days&quot;, &quot;DA90&quot;,
&quot;DA 60 days&quot;, &quot;DA60&quot;,
&quot;DA 45 days&quot;, &quot;DA45&quot;,
&quot;DA 30 days&quot;, &quot;DA30&quot;,

&quot;Bond transfer&quot;, &quot;BONTRN&quot;,

&quot;BL 90 days&quot;, &quot;BL90&quot;,
&quot;BL 75 days&quot;, &quot;BL75&quot;,
&quot;BL 60 days&quot;, &quot;BL60&quot;,
&quot;BL 45 days&quot;, &quot;BL45&quot;,
&quot;BL 30 days&quot;, &quot;BL30&quot;,
&quot;BL 120 days&quot;, &quot;BL120&quot;,

&quot;90 days from invoice&quot;, &quot;INV90&quot;,
&quot;75 days from invoice&quot;, &quot;INV75&quot;,
&quot;7 days from invoice&quot;, &quot;INV07&quot;,
&quot;60 days from invoice&quot;, &quot;INV60&quot;,
&quot;45 days from invoice&quot;, &quot;INV45&quot;,
&quot;40 days from invoice&quot;, &quot;INV40&quot;,
&quot;30 days from invoice&quot;, &quot;INV30&quot;,
&quot;20 days from invoice&quot;, &quot;INV20&quot;,
&quot;15 days from invoice&quot;, &quot;INV15&quot;,
&quot;120 days from invoice&quot;, &quot;INV120&quot;,

&quot;60 days from LR&quot;, &quot;LR60&quot;,
&quot;30 days from goods arrival&quot;, &quot;30DDEL&quot;,

&quot;70% advance &amp; 30% CACD&quot;, &quot;70ADV-30CD&quot;,

&quot;50% advance &amp; 50% PDC 45 days&quot;, &quot;50ADV50PDC&quot;,
&quot;50% advance &amp; 50% CACD&quot;, &quot;50ADV-50CD&quot;,
&quot;50% advance &amp; 50% BL 60 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% BL 45 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% against inspection&quot;, &quot;50ADV50INS&quot;,
&quot;50% advance &amp; 50% against dispatch&quot;, &quot;50ADV50DIS&quot;,
&quot;50% advance &amp; 50% 60 days from invoice&quot;, &quot;50ADV50INV&quot;,

&quot;40% advance &amp; 60% before dispatch&quot;, &quot;40ADV60DIS&quot;,

&quot;30% advance &amp; 70% CACD&quot;, &quot;30ADV-70CD&quot;,
&quot;30% advance &amp; 70% before dispatch&quot;, &quot;30ADV70DIS&quot;,

&quot;25% advance &amp; 75% LC at sight&quot;, &quot;25ADV-75LC&quot;,
&quot;25% advance &amp; 75% CACD&quot;, &quot;25ADV-75CD&quot;,
&quot;25% advance &amp; 75% BL 60 days&quot;, &quot;25ADV-75BL&quot;,
&quot;25% advance &amp; 75% before dispatch&quot;, &quot;25ADV75DIS&quot;,

&quot;20% advance &amp; 80% CACD&quot;, &quot;20ADV-80CD&quot;,
&quot;20% advance &amp; 80% before dispatch&quot;, &quot;20ADV80DIS&quot;,
&quot;20% advance &amp; 80% 60 days from invoice&quot;, &quot;20ADV80INV&quot;,

&quot;100% cash against copy documents&quot;, &quot;CACD&quot;,
&quot;100% against delivery&quot;, &quot;100%DEL&quot;,
&quot;100% advance against proforma&quot;, &quot;100%PI&quot;,
&quot;100% advance against BL copy&quot;, &quot;100%CBL&quot;,
&quot;100% advance&quot;, &quot;100%ADV&quot;,

&quot;10% advance &amp; 90% BL 30 days&quot;, &quot;10ADV-90BL&quot;,
&quot;10% ADV &amp; 90% CACD&quot;, &quot;10ADV-90CD&quot;,

&quot;10 days from invoice&quot;, &quot;INV10&quot;,

&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Line_Item_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Line_Item_Endpoint__c</fullName>
    <label>BC Line Item Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Order_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Order_Endpoint__c</fullName>
    <label>BC Order Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Password__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Line_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Line_Namespace__c</fullName>
    <label>SOAP Line Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Order_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Order_Namespace__c</fullName>
    <label>SOAP Order Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Username__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Cust_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Cust_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Term_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD (UNIT-III)</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Sample_Order.recordType-meta.xml
<RecordType>
    <fullName>Sample_Order</fullName>
    <active>true</active>
    <label>Sample Order</label>
</RecordType>

force-app/main/default/classes/DRC_NBC_OrderReadUpdateQueueableTest.cls
/**
* @File Name   : DRC_NBC_OrderReadUpdateQueueableTest.cls
* @Description : Test class for DRC_NBC_OrderReadUpdateQueueable
*                Covers:
*                  1. Happy path  – READ 200 → UPDATE 200 → SF Status set to Released
*                  2. READ fails  – HTTP non-200 from BC, job exits early
*                  3. READ returns no Key in XML – job exits early
*                  4. UPDATE fails – HTTP non-200 from BC, SF Status NOT changed
*                  5. Custom Setting not configured – graceful no-op
*                  6. Null Order Id passed – graceful no-op
*                  7. Sample Order record type path
*                  8. Shipping Address populated path
*                  9. All fields populated path
* @Author      : SATISH YADAV
* @Last Modified On : March 2026
**/
@isTest
private class DRC_NBC_OrderReadUpdateQueueableTest {

    // =========================================================================
    // SOAP RESPONSE CONSTANTS
    // =========================================================================
    private static final String READ_SUCCESS_RESPONSE =
        '<?xml version="1.0" encoding="utf-8"?>' +
        '<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">' +
        '<Soap:Body>' +
        '<Read_Result xmlns="urn:microsoft-dynamics-schemas/page/salesordersalesforce">' +
        '<SalesOrderSalesForce>' +
        '<Key>60;JAAAAACLAQAAAAJ7/1MATwBEAE8ATQAvADIANgAyADcALwAwADAAMAAzADE=8;240356490;</Key>' +
        '<No>SODOM/2627/00031</No>' +
        '<Document_Type>Order</Document_Type>' +
        '<Status>Open</Status>' +
        '<Salesperson_Code>SP001</Salesperson_Code>' +
        '<Location_Code>JNPT</Location_Code>' +
        '<Shipment_Method_Code>CC</Shipment_Method_Code>' +
        '<Order_Date>2025-01-01</Order_Date>' +
        '</SalesOrderSalesForce>' +
        '</Read_Result>' +
        '</Soap:Body>' +
        '</Soap:Envelope>';

    private static final String READ_NO_KEY_RESPONSE =
        '<?xml version="1.0" encoding="utf-8"?>' +
        '<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">' +
        '<Soap:Body>' +
        '<Read_Result xmlns="urn:microsoft-dynamics-schemas/page/salesordersalesforce">' +
        '<SalesOrderSalesForce>' +
        '<No>SODOM/2627/00031</No>' +
        '</SalesOrderSalesForce>' +
        '</Read_Result>' +
        '</Soap:Body>' +
        '</Soap:Envelope>';

    private static final String UPDATE_SUCCESS_RESPONSE =
        '<?xml version="1.0" encoding="utf-8"?>' +
        '<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">' +
        '<Soap:Body>' +
        '<Update_Result xmlns="urn:microsoft-dynamics-schemas/page/salesordersalesforce">' +
        '<SalesOrderSalesForce>' +
        '<Key>60;JAAAAACLAQAAAAJ7/1MATwBEAE8ATQAvADIANgAyADcALwAwADAAMAAzADE=8;240356490;</Key>' +
        '<No>SODOM/2627/00031</No>' +
        '<Status>Released</Status>' +
        '</SalesOrderSalesForce>' +
        '</Update_Result>' +
        '</Soap:Body>' +
        '</Soap:Envelope>';

    // =========================================================================
    // MOCK CLASSES
    // =========================================================================

    /**
     * Controls READ (1st call) and UPDATE (2nd call) independently.
     */
    private class MultiCalloutMock implements HttpCalloutMock {
        private Integer callCount    = 0;
        private Integer readStatus;
        private String  readBody;
        private Integer updateStatus;
        private String  updateBody;

        public MultiCalloutMock(
                Integer readStatus,   String readBody,
                Integer updateStatus, String updateBody) {
            this.readStatus   = readStatus;
            this.readBody     = readBody;
            this.updateStatus = updateStatus;
            this.updateBody   = updateBody;
        }

        public HttpResponse respond(HttpRequest req) {
            callCount++;
            HttpResponse res = new HttpResponse();
            if (callCount == 1) {
                res.setStatusCode(readStatus);
                res.setBody(readBody);
            } else {
                res.setStatusCode(updateStatus);
                res.setBody(updateBody);
            }
            return res;
        }
    }

    /** Single-callout mock – used when only READ is expected (no UPDATE). */
    private class SingleCalloutMock implements HttpCalloutMock {
        private Integer statusCode;
        private String  body;

        public SingleCalloutMock(Integer statusCode, String body) {
            this.statusCode = statusCode;
            this.body       = body;
        }

        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(body);
            return res;
        }
    }

    // =========================================================================
    // SETUP HELPER
    // =========================================================================

    /**
     * Inserts the custom setting + Account + Order required by most tests.
     * Returns the Order Id.
     *
     * NOTE: DRC_NBC_BC_Integration__c is a Hierarchy Custom Setting so we use
     *       SetupOwnerId = UserInfo.getOrganizationId() for the org-default tier.
     *       The static initialisers in the production class call getInstance()
     *       which reads the Hierarchy record, so this record must exist before
     *       the class is even loaded – that is why we insert it first.
     */
    private static Id setupTestData() {

        DRC_NBC_BC_Integration__c settings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                    = UserInfo.getOrganizationId(),
            DRC_NBC_BC_Order_Endpoint__c    = 'https://bc.example.com/order',
            DRC_NBC_BC_Line_Item_Endpoint__c= 'https://bc.example.com/lineitem',
            DRC_NBC_SOAP_Order_Namespace__c = 'urn:microsoft-dynamics-schemas/page/salesordersalesforce',
            DRC_NBC_SOAP_Line_Namespace__c  = 'urn:microsoft-dynamics-schemas/page/salesorderline',
            DRC_NBC_Username__c             = 'testuser',
            DRC_NBC_Password__c             = 'testpass'
        );
        insert settings;

        Account acc = new Account(
            Name                          = 'Test Account',
            BillingStreet                 = '302, Amar Business Park',
            BillingCity                   = 'Pune',
            BillingPostalCode             = '411045',
            BillingCountry                = 'India',
            DRC_NBC_Customer_Number__c    = 'CUSTDOM/2526-00014',
            DRC_NBC_BC_Approval_Status__c = true
        );
        insert acc;

        Order ord = new Order(
            AccountId                    = acc.Id,
            Status                       = 'Draft',
            EffectiveDate                = Date.today(),
            Pricebook2Id                 = Test.getStandardPricebookId(),
            ShippingStreet               = 'Test 1234, Test City',
            ShippingCity                 = 'Mumbai',
            ShippingPostalCode           = '400001',
            ShippingCountry              = 'India',
            ShippingCountryCode          = 'IN',
            CurrencyIsoCode              = 'INR',
            PoNumber                     = 'TEST-PO-001',
            DRC_NBC_Cust_Order_Number__c = 'SODOM/2627/00031',
            DRC_NBC_Warehouse__c         = 'CFS - JNPT',
            DRC_NBC_Payment_Terms__c     = '100%',
            DRC_NBC_Inco_Terms__c        = 'Charges Collect (CC)',
            OwnerId                      = UserInfo.getUserId()
        );
        insert ord;

        return ord.Id;
    }

    // =========================================================================
    // TEST 1: Happy Path – READ 200 + UPDATE 200 → SF Order Status = Released
    // =========================================================================
    @isTest
    static void testExecute_HappyPath_OrderStatusSetToReleased() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, UPDATE_SUCCESS_RESPONSE
        ));

        Test.startTest();
        // FIX: call the static execute() method directly – no constructor needed
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.debug('Final Order Status: ' + result.Status);
        System.assertEquals('Released', result.Status,
            'Order Status should be Released after successful BC READ + UPDATE');
    }

    // =========================================================================
    // TEST 2: READ returns HTTP 500 → exits early, Status stays Draft
    // =========================================================================
    @isTest
    static void testExecute_ReadHttpFailure_StatusNotChanged() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new SingleCalloutMock(
            500, '<error>Internal Server Error</error>'
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.debug('Order Status after READ failure: ' + result.Status);
        System.assertNotEquals('Released', result.Status,
            'Order Status should NOT be Released when BC READ returns 500');
    }

    // =========================================================================
    // TEST 3: READ returns 200 but no <Key> → exits early, Status stays Draft
    // =========================================================================
    @isTest
    static void testExecute_ReadNoKeyInResponse_StatusNotChanged() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new SingleCalloutMock(
            200, READ_NO_KEY_RESPONSE
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.debug('Order Status after no Key in response: ' + result.Status);
        System.assertNotEquals('Released', result.Status,
            'Order Status should NOT be Released when READ response has no Key');
    }

    // =========================================================================
    // TEST 4: READ 200 + UPDATE 400 → SF Status NOT changed
    // =========================================================================
    @isTest
    static void testExecute_UpdateHttpFailure_StatusNotChanged() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            400, '<error>Bad Request</error>'
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.debug('Order Status after UPDATE failure: ' + result.Status);
        System.assertNotEquals('Released', result.Status,
            'Order Status should NOT be Released when BC UPDATE returns 400');
    }

    // =========================================================================
    // TEST 5: Null Order Id passed → graceful no-op, no exception
    // =========================================================================
    @isTest
    static void testExecute_NullOrderId_GracefulNoOp() {

        // Custom setting still needs to exist for the class static init
        DRC_NBC_BC_Integration__c settings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                    = UserInfo.getOrganizationId(),
            DRC_NBC_BC_Order_Endpoint__c    = 'https://bc.example.com/order',
            DRC_NBC_SOAP_Order_Namespace__c = 'urn:test',
            DRC_NBC_Username__c             = 'u',
            DRC_NBC_Password__c             = 'p'
        );
        insert settings;

        Test.startTest();
        // Should return immediately without throwing
        DRC_NBC_OrderReadUpdateQueueable.execute(null);
        Test.stopTest();

        // If we reach here without an exception the test passes
        System.assert(true, 'execute(null) should exit gracefully without exception');
    }

   
    // =========================================================================
    // TEST 7: Static method runs without exception (replaces constructor test)
    //         FIX: DRC_NBC_OrderReadUpdateQueueable has no constructor –
    //              the original test_6 instantiated it incorrectly.
    // =========================================================================
    @isTest
    static void testExecute_StaticMethod_NoException() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, UPDATE_SUCCESS_RESPONSE
        ));

        Test.startTest();
        // Just verify calling the static method does not throw
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        System.assert(true, 'Static execute() should run without throwing an exception');
    }

    // =========================================================================
    // TEST 8: Sample Order record type → isSample = true path
    // =========================================================================
    @isTest
    static void testExecute_SampleOrder_HappyPath() {

        DRC_NBC_BC_Integration__c settings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                    = UserInfo.getOrganizationId(),
            DRC_NBC_BC_Order_Endpoint__c    = 'https://bc.example.com/order',
            DRC_NBC_SOAP_Order_Namespace__c = 'urn:microsoft-dynamics-schemas/page/salesordersalesforce',
            DRC_NBC_Username__c             = 'testuser',
            DRC_NBC_Password__c             = 'testpass'
        );
        insert settings;

        Account acc = new Account(
            Name                       = 'Sample Account',
            DRC_NBC_Customer_Number__c = 'CUSTDOM/SAMPLE-001',
            BillingStreet              = 'Sample Street',
            BillingCity                = 'Sample City',
            BillingPostalCode          = '123456'
        );
        insert acc;

        List<RecordType> sampleRT = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Order' AND DeveloperName = 'Sample_Order'
            LIMIT 1
        ];

        Order ord = new Order(
            AccountId                    = acc.Id,
            Status                       = 'Draft',
            EffectiveDate                = Date.today(),
            Pricebook2Id                 = Test.getStandardPricebookId(),
            ShippingCountryCode          = 'IN',
            ShippingStreet               = 'Sample Ship Street',
            ShippingCity                 = 'Sample Ship City',
            ShippingPostalCode           = '654321',
            CurrencyIsoCode              = 'INR',
            DRC_NBC_Cust_Order_Number__c = 'SODOM/SAMPLE/00001',
            DRC_NBC_Warehouse__c         = 'CFS - JNPT',
            DRC_NBC_Payment_Terms__c     = '100',
            DRC_NBC_Inco_Terms__c        = 'Charges Collect (CC)',
            PoNumber                     = 'SAMPLE-PO-123',
            OwnerId                      = UserInfo.getUserId()
        );
        if (!sampleRT.isEmpty()) {
            ord.RecordTypeId = sampleRT[0].Id;
        }
        insert ord;

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, UPDATE_SUCCESS_RESPONSE
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(ord.Id);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :ord.Id LIMIT 1];
        System.debug('Sample Order Status after execution: ' + result.Status);
        System.assertEquals('Released', result.Status,
            'Sample Order Status should be Released after successful BC round-trip');
    }

    // =========================================================================
    // TEST 9: Shipping Address populated path
    // =========================================================================
    @isTest
    static void testExecute_WithShippingAddress_HappyPath() {

        DRC_NBC_BC_Integration__c settings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                    = UserInfo.getOrganizationId(),
            DRC_NBC_BC_Order_Endpoint__c    = 'https://bc.example.com/order',
            DRC_NBC_SOAP_Order_Namespace__c = 'urn:microsoft-dynamics-schemas/page/salesordersalesforce',
            DRC_NBC_Username__c             = 'testuser',
            DRC_NBC_Password__c             = 'testpass'
        );
        insert settings;

        Account acc = new Account(
            Name                       = 'Test Account With Ship To',
            DRC_NBC_Customer_Number__c = 'CUSTDOM/SHIP-001',
            BillingStreet              = 'Billing Line 1',
            BillingCity                = 'Billing City',
            BillingPostalCode          = '111111'
        );
        insert acc;

        DRC_NBC_Addresses__c shipAddr = new DRC_NBC_Addresses__c(
            DRC_NBC_Ship_To_Code__c = 'SHIP-TO-001',
            DRC_NBC_Warehouse__c    = 'CFS - JNPT'
        );
        insert shipAddr;

        Order ord = new Order(
            AccountId                    = acc.Id,
            Status                       = 'Draft',
            EffectiveDate                = Date.today(),
            Pricebook2Id                 = Test.getStandardPricebookId(),
            ShippingCountryCode          = 'IN',
            ShippingStreet               = 'Ship Street 123',
            ShippingCity                 = 'Ship City',
            ShippingPostalCode           = '999999',
            CurrencyIsoCode              = 'INR',
            DRC_NBC_Cust_Order_Number__c = 'SODOM/SHIP/00001',
            DRC_NBC_Shipping_Address__c  = shipAddr.Id,
            DRC_NBC_Warehouse__c         = 'CFS - JNPT',
            DRC_NBC_Payment_Terms__c     = '100',
            DRC_NBC_Inco_Terms__c        = 'Charges Collect (CC)',
            PoNumber                     = 'SHIP-PO-456',
            OwnerId                      = UserInfo.getUserId()
        );
        insert ord;

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, UPDATE_SUCCESS_RESPONSE
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(ord.Id);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :ord.Id LIMIT 1];
        System.assertEquals('Released', result.Status,
            'Order with shipping address should reach Released status');
    }

    // =========================================================================
    // TEST 10: All fields populated – exercises every branch in execute()
    // =========================================================================
    @isTest
    static void testExecute_AllFieldsPopulated_HappyPath() {

        Id orderId = setupTestData();

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, UPDATE_SUCCESS_RESPONSE
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.assertEquals('Released', result.Status,
            'All-fields-populated Order should reach Released status');
    }

    // =========================================================================
    // TEST 11: READ returns SOAP Fault → exits early (hasSoapFault branch)
    // =========================================================================
    @isTest
    static void testExecute_ReadSoapFault_StatusNotChanged() {

        Id orderId = setupTestData();

        String soapFaultBody =
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">' +
            '<Soap:Body>' +
            '<Soap:Fault>' +
            '<faultcode>Soap:Server</faultcode>' +
            '<faultstring>Record not found</faultstring>' +
            '</Soap:Fault>' +
            '</Soap:Body>' +
            '</Soap:Envelope>';

        Test.setMock(HttpCalloutMock.class, new SingleCalloutMock(200, soapFaultBody));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.assertNotEquals('Released', result.Status,
            'Order Status should NOT change when READ returns a SOAP Fault');
    }

    // =========================================================================
    // TEST 12: UPDATE returns SOAP Fault → SF Status NOT changed
    // =========================================================================
    @isTest
    static void testExecute_UpdateSoapFault_StatusNotChanged() {

        Id orderId = setupTestData();

        String soapFaultBody =
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">' +
            '<Soap:Body>' +
            '<Soap:Fault>' +
            '<faultcode>Soap:Server</faultcode>' +
            '<faultstring>Update not allowed in current state</faultstring>' +
            '</Soap:Fault>' +
            '</Soap:Body>' +
            '</Soap:Envelope>';

        Test.setMock(HttpCalloutMock.class, new MultiCalloutMock(
            200, READ_SUCCESS_RESPONSE,
            200, soapFaultBody          // HTTP 200 but SOAP Fault in body
        ));

        Test.startTest();
        DRC_NBC_OrderReadUpdateQueueable.execute(orderId);
        Test.stopTest();

        Order result = [SELECT Id, Status FROM Order WHERE Id = :orderId LIMIT 1];
        System.assertNotEquals('Released', result.Status,
            'Order Status should NOT change when UPDATE response contains a SOAP Fault');
    }
}