force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_C_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_C_GST__c</fullName>
    <formula>IF(
    OR(
        AND(
            ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
            TEXT(Account.BillingStateCode) = &quot;MH&quot;
        ),
        AND(
            ISPICKVAL(DRC_NBC_Sample_Type__c, &quot;Paid Sample&quot;),
            TEXT(Account.BillingStateCode) = &quot;MH&quot;
        )
    ),
    DRC_NBC_Total_Amount__c *
    IF(
        Is_Domestic_Merchnat__c,
        0.001,
        VALUE($Label.DRC_NBC_CGST_Tax_Rate)
    ),
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_I_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_I_GST__c</fullName>
    <formula>IF(
    OR(
        AND(
            ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
            TEXT(Account.BillingStateCode) &lt;&gt; &quot;MH&quot;
        ),
        AND(
            ISPICKVAL(DRC_NBC_Sample_Type__c, &quot;Paid Sample&quot;),
            TEXT(Account.BillingStateCode) &lt;&gt; &quot;MH&quot;
        )
    ),
    DRC_NBC_Total_Amount__c *
    IF(
        Is_Domestic_Merchnat__c,
        0.001,
        VALUE($Label.DRC_NBC_IGST_Tax_Rate)
    ),
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Import_Starting_Sequence__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Import_Starting_Sequence__c</fullName>
    <label>Import Starting Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_S_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_S_GST__c</fullName>
    <formula>IF(
    OR(
        AND(
            ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
            TEXT(Account.BillingStateCode) = &quot;MH&quot;
        ),
        AND(
            ISPICKVAL(DRC_NBC_Sample_Type__c, &quot;Paid Sample&quot;),
            TEXT(Account.BillingStateCode) = &quot;MH&quot;
        )
    ),
    DRC_NBC_Total_Amount__c *
    IF(
        Is_Domestic_Merchnat__c,
        0.001,
        VALUE($Label.DRC_NBC_SGST_Tax_Rate)
    ),
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_C_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_C_GST__c</fullName>
    <formula>IF(
    AND(
        ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
        TEXT( Contact.Account.BillingStateCode ) = &quot;MH&quot;
    ),
    TotalPrice * 0.09,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_I_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_I_GST__c</fullName>
    <formula>IF(
    AND(
        ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
        TEXT( Contact.Account.BillingStateCode) &lt;&gt; &quot;MH&quot;
    ),
    TotalPrice* 0.18,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Import_Starting_Sequence__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Import_Starting_Sequence__c</fullName>
    <label>Domestic Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Inco_terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_terms__c</fullName>
    <label>Inco terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Payemnt_Term__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payemnt_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_S_GST__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_S_GST__c</fullName>
    <formula>IF(
    AND(
        ISPICKVAL(DRC_NBC_Type__c, &quot;Domestic&quot;),
        TEXT( Contact.Account.BillingStateCode ) = &quot;MH&quot;
    ),
    TotalPrice * 0.09,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_DomesticQuotationPDFController.cls
public class DRC_NBC_DomesticQuotationPDFController {
    
    public Quote quoteRecord { get; set; }
    public List<QuoteLineItem> quoteLineItems { get; set; }
    public Decimal subtotal { get; set; }
    public Decimal cgstAmount { get; set; }
    public Decimal sgstAmount { get; set; }
    public Decimal igstAmount { get; set; }
    public Decimal otherTaxAmount { get; set; }
    public Decimal tcsAmount { get; set; }
    public Decimal totalAmount { get; set; }

    // ★ NEW: Full text for special instructions
    public String specialInstructions { get; set; }

    // Existing bullets list
    public List<String> specialRequirementList { get; set; }
    
    public DRC_NBC_DomesticQuotationPDFController(ApexPages.StandardController stdController) {
        Id quoteId = stdController.getId();
        
        // Fetch Quote details
        quoteRecord = [SELECT Id, Name, QuoteNumber, CreatedDate, ExpirationDate,
                       Account.Name, BillingStreet, BillingCity,BillingStateCode,Contact.Account.BillingStateCode,
                       BillingState, BillingPostalCode, BillingCountry, CurrencyISOCode,
                       ShippingStreet, ShippingCity, ShippingState, 
                       ShippingPostalCode, ShippingCountry,
                       Account.DRC_NBC_GST_Number__c, ShippingStateCode,
                       ShippingHandling, Tax, GrandTotal, Subtotal,
                       DRC_NBC_Payemnt_Term__c, DRC_NBC_Inco_terms__c, 
                       DRC_NBC_C_GST__c, DRC_NBC_S_GST__c, DRC_NBC_I_GST__c,
                       DRC_NBC_Type__c,
                       DRC_NBC_Import_Starting_Sequence__c, 
                       DRC_NBC_Grand_Total__c,
                       DRC_NBC_Invoice_Export_Sequence_Number__c,
                       DRC_NBC_Special_Requirements__c,
                       DRC_NBC_Other_Tax_Amount__c, DRC_NBC_TCS_Amount__c
                       FROM Quote 
                       WHERE Id = :quoteId];
        
        Integer generatedSequence = assignQuoteSequenceNumber(quoteRecord);
        
        if (generatedSequence != null) {
            if (quoteRecord.DRC_NBC_Type__c == 'Domestic') {
                quoteRecord.DRC_NBC_Import_Starting_Sequence__c = generatedSequence;
            } else if (quoteRecord.DRC_NBC_Type__c == 'Export') {
                quoteRecord.DRC_NBC_Invoice_Export_Sequence_Number__c = generatedSequence;
            }
        }

        // Fetch Quote Line Items
        quoteLineItems = [SELECT Id, Product2.Name, Quantity, UnitPrice, TotalPrice,
                          DRC_NBC_Unit_Of_Measurement__c,
                          Product2.QuantityUnitOfMeasure, Product2.DRC_NBC_HSN_SAC_Code__c, 
                          Product2.DRC_NBC_KIND_OF_PKG__c, Product2.CurrencyIsoCode,
                          Product2.Description
                          FROM QuoteLineItem 
                          WHERE QuoteId = :quoteId 
                          ORDER BY LineNumber];
        
        // Calculate amounts
        calculateAmounts();

        // ★ NEW — Full Special Instructions text with proper null/blank handling
        specialInstructions = quoteRecord.DRC_NBC_Special_Requirements__c;

         if (specialInstructions == null) {
             specialInstructions = '';
            } else {
            specialInstructions = specialInstructions.trim();
        }


        // Existing — Break into bullet points
        specialRequirementList = new List<String>();
        String specialReqRaw = quoteRecord.DRC_NBC_Special_Requirements__c;
          
        if (!String.isBlank(specialReqRaw)) {
            specialReqRaw = specialReqRaw.replace('\n', ' ').replace('\r', ' ');
            for (String part : specialReqRaw.split('\\.')) {
                if (!String.isBlank(part.trim())) {
                    specialRequirementList.add(part.trim());
                }
            }
        }
    }
    
    private void calculateAmounts() {
        subtotal = 0;
        
        for (QuoteLineItem qli : quoteLineItems) {
            subtotal += qli.TotalPrice != null ? qli.TotalPrice : 0;
        }
        
        cgstAmount = quoteRecord.DRC_NBC_C_GST__c != null ? quoteRecord.DRC_NBC_C_GST__c : 0;
        sgstAmount = quoteRecord.DRC_NBC_S_GST__c != null ? quoteRecord.DRC_NBC_S_GST__c : 0;
        igstAmount = quoteRecord.DRC_NBC_I_GST__c != null ? quoteRecord.DRC_NBC_I_GST__c : 0;
        otherTaxAmount = quoteRecord.DRC_NBC_Other_Tax_Amount__c != null ? quoteRecord.DRC_NBC_Other_Tax_Amount__c : 0;
        tcsAmount = quoteRecord.DRC_NBC_TCS_Amount__c != null ? quoteRecord.DRC_NBC_TCS_Amount__c : 0;
        
        totalAmount = quoteRecord.DRC_NBC_Grand_Total__c;
    }
    
    public String getFormattedDate(Date dt) {
        if (dt != null) {
            return dt.format();
        }
        return '';
    }
    
    
    private static Integer assignQuoteSequenceNumber(Quote quoteRec) {
        Integer newSequenceNumber;
        
        // Domestic logic
        if (quoteRec.DRC_NBC_Type__c == 'Domestic' &&
            quoteRec.DRC_NBC_Import_Starting_Sequence__c == null) {
                
            AggregateResult[] result = [
                SELECT MAX(DRC_NBC_Import_Starting_Sequence__c) maxSeq
                FROM Quote
                WHERE DRC_NBC_Type__c = 'Domestic'
            ];
                
            Decimal maxDecimal = (result.size() > 0 && result[0].get('maxSeq') != null)
                ? (Decimal) result[0].get('maxSeq')
                : Decimal.valueOf(Label.DRC_NBC_Import_Starting_Sequence);
                
            newSequenceNumber = maxDecimal.intValue() + 1;
            return newSequenceNumber;
        }
        
        // Export logic
        if (quoteRec.DRC_NBC_Type__c == 'Export' &&
            quoteRec.DRC_NBC_Invoice_Export_Sequence_Number__c == null) {
                
            AggregateResult[] result = [
                SELECT MAX(DRC_NBC_Invoice_Export_Sequence_Number__c) maxSeq
                FROM Quote
                WHERE DRC_NBC_Type__c = 'Export'
            ];
                
            Decimal maxDecimal = (result.size() > 0 && result[0].get('maxSeq') != null)
                ? (Decimal) result[0].get('maxSeq')
                : Decimal.valueOf(Label.DRC_NBC_Export_Starting_Sequence);
                
            newSequenceNumber = maxDecimal.intValue() + 1;
            return newSequenceNumber;
        }
        
        return null;
    }
}