force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <formula>CASE(
TEXT(DRC_NBC_Payment_Terms_Description__c),

&quot;PDC 90 days&quot;, &quot;PDC90&quot;,
&quot;PDC 60 days&quot;, &quot;PDC60&quot;,
&quot;PDC 45 days&quot;, &quot;PDC45&quot;,
&quot;PDC 30 days&quot;, &quot;PDC30&quot;,

&quot;Irrevocable LC at sight&quot;, &quot;IRRELC&quot;,
&quot;Irrevocable LC 90 days&quot;, &quot;IRRLC90&quot;,
&quot;Irrevocable LC 60 days&quot;, &quot;IRRLC60&quot;,
&quot;Irrevocable LC 45 days&quot;, &quot;IRRLC45&quot;,
&quot;Irrevocable LC 30 days&quot;, &quot;IRRLC30&quot;,

&quot;Free sample&quot;, &quot;FOC&quot;,

&quot;DP AT SIGHT&quot;, &quot;DPSIGHT&quot;,
&quot;DP 90 days&quot;, &quot;DP90&quot;,
&quot;DP 60 days&quot;, &quot;DP60&quot;,
&quot;DP 30 days&quot;, &quot;DP30&quot;,

&quot;DA 90 days&quot;, &quot;DA90&quot;,
&quot;DA 60 days&quot;, &quot;DA60&quot;,
&quot;DA 45 days&quot;, &quot;DA45&quot;,
&quot;DA 30 days&quot;, &quot;DA30&quot;,

&quot;Bond transfer&quot;, &quot;BONTRN&quot;,

&quot;BL 90 days&quot;, &quot;BL90&quot;,
&quot;BL 75 days&quot;, &quot;BL75&quot;,
&quot;BL 60 days&quot;, &quot;BL60&quot;,
&quot;BL 45 days&quot;, &quot;BL45&quot;,
&quot;BL 30 days&quot;, &quot;BL30&quot;,
&quot;BL 120 days&quot;, &quot;BL120&quot;,

&quot;90 days from invoice&quot;, &quot;INV90&quot;,
&quot;75 days from invoice&quot;, &quot;INV75&quot;,
&quot;7 days from invoice&quot;, &quot;INV07&quot;,
&quot;60 days from invoice&quot;, &quot;INV60&quot;,
&quot;45 days from invoice&quot;, &quot;INV45&quot;,
&quot;40 days from invoice&quot;, &quot;INV40&quot;,
&quot;30 days from invoice&quot;, &quot;INV30&quot;,
&quot;20 days from invoice&quot;, &quot;INV20&quot;,
&quot;15 days from invoice&quot;, &quot;INV15&quot;,
&quot;120 days from invoice&quot;, &quot;INV120&quot;,

&quot;60 days from LR&quot;, &quot;LR60&quot;,
&quot;30 days from goods arrival&quot;, &quot;30DDEL&quot;,

&quot;70% advance &amp; 30% CACD&quot;, &quot;70ADV-30CD&quot;,

&quot;50% advance &amp; 50% PDC 45 days&quot;, &quot;50ADV50PDC&quot;,
&quot;50% advance &amp; 50% CACD&quot;, &quot;50ADV-50CD&quot;,
&quot;50% advance &amp; 50% BL 60 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% BL 45 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% against inspection&quot;, &quot;50ADV50INS&quot;,
&quot;50% advance &amp; 50% against dispatch&quot;, &quot;50ADV50DIS&quot;,
&quot;50% advance &amp; 50% 60 days from invoice&quot;, &quot;50ADV50INV&quot;,

&quot;40% advance &amp; 60% before dispatch&quot;, &quot;40ADV60DIS&quot;,

&quot;30% advance &amp; 70% CACD&quot;, &quot;30ADV-70CD&quot;,
&quot;30% advance &amp; 70% before dispatch&quot;, &quot;30ADV70DIS&quot;,

&quot;25% advance &amp; 75% LC at sight&quot;, &quot;25ADV-75LC&quot;,
&quot;25% advance &amp; 75% CACD&quot;, &quot;25ADV-75CD&quot;,
&quot;25% advance &amp; 75% BL 60 days&quot;, &quot;25ADV-75BL&quot;,
&quot;25% advance &amp; 75% before dispatch&quot;, &quot;25ADV75DIS&quot;,

&quot;20% advance &amp; 80% CACD&quot;, &quot;20ADV-80CD&quot;,
&quot;20% advance &amp; 80% before dispatch&quot;, &quot;20ADV80DIS&quot;,
&quot;20% advance &amp; 80% 60 days from invoice&quot;, &quot;20ADV80INV&quot;,

&quot;100% cash against copy documents&quot;, &quot;CACD&quot;,
&quot;100% against delivery&quot;, &quot;100%DEL&quot;,
&quot;100% advance against proforma&quot;, &quot;100%PI&quot;,
&quot;100% advance against BL copy&quot;, &quot;100%CBL&quot;,
&quot;100% advance&quot;, &quot;100%ADV&quot;,

&quot;10% advance &amp; 90% BL 30 days&quot;, &quot;10ADV-90BL&quot;,
&quot;10% ADV &amp; 90% CACD&quot;, &quot;10ADV-90CD&quot;,

&quot;10 days from invoice&quot;, &quot;INV10&quot;,

&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Courier_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Courier_Number__c</fullName>
    <label>Courier Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Delivery_status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Delivery_status__c</fullName>
    <label>Delivery status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Intransit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Expected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Expected_Delivery_Date__c</fullName>
    <label>Expected Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Import_Starting_Sequence__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Import_Starting_Sequence__c</fullName>
    <label>Import Starting Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Term_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Sample_Amount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Sample_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Sample_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Sample_Name__c</fullName>
    <label>Sample Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Sample_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Sample_Sequence_Number__c</fullName>
    <label>Sample Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Sample_Shipping_Cost__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Sample_Shipping_Cost__c</fullName>
    <label>Sample Shipping Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Sample_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Sample_Type__c</fullName>
    <label>Sample Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Sample</fullName>
            </value>
            <value>
                <fullName>Paid Sample</fullName>
            </value>
            <value>
                <fullName>Test Sample</fullName>
            </value>
            <value>
                <fullName>Free Sample</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Unit_Of_Measurement__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Unit_Of_Measurement__c</fullName>
    <label>Unit Of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kilograms</fullName>
                <default>true</default>
                <label>Kilograms</label>
            </value>
            <value>
                <fullName>Pound</fullName>
            </value>
            <value>
                <fullName>u1</fullName>
                <isActive>false</isActive>
                <label>u1</label>
            </value>
            <value>
                <fullName>u2</fullName>
                <isActive>false</isActive>
                <label>u2</label>
            </value>
            <value>
                <fullName>u3</fullName>
                <isActive>false</isActive>
                <label>u3</label>
            </value>
            <value>
                <fullName>u4</fullName>
                <isActive>false</isActive>
                <label>u4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Unit_Of_Measurement__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Unit_Of_Measurement__c</fullName>
    <label>Unit Of Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>Pounds</fullName>
                <isActive>false</isActive>
                <label>Pounds</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_GenerateSamplePiController.cls
/**
* @File Name        : DRC_NBC_GenerateSamplePiController.cls
* @Description      : Controller class for Domestic/International Sample PI Order Visualforce page
* @Author           : Satish Yadav
* @Last Modified By : Satish Yadav
* @Last Modified On : October 22, 2025
* @Modification Log :
*==============================================================================
* Ver   | Date             | Author       | Modification
*==============================================================================
* 1.0   | October 22, 2025 | Satish Yadav | Initial Version
* 1.1   | October 22, 2025 | Satish Yadav | Added additional fields
* 1.2   | March 2026       | Satish Yadav | Dynamic currency; hide GST col for non-India billing
**/

public class DRC_NBC_GenerateSamplePiController {

    // Order Information
    public String orderNumber       { get; set; }
    public Date   orderDate         { get; set; }
    public Date   shipmentDate      { get; set; }
    public String purchaseOrderNo   { get; set; }
    public String SalesPerson       { get; set; }
    public String importSequence    { get; set; }
    public String exportSequence    { get; set; }

    // Customer Information
    public String customerName      { get; set; }
    public String customerGST       { get; set; }
    public String customerNumber    { get; set; }
    public String shippingAddress   { get; set; }
    public String shippingCity      { get; set; }
    public String shippingPostalCode{ get; set; }
    public String shippingCountry   { get; set; }
    public String shippingState     { get; set; }
    public String orderType         { get; set; }
    public String billToCustomer    { get; set; }
    public String PO                { get; set; }
    public String billingAddress    { get; set; }
    public String billingCity       { get; set; }
    public String billingPostalCode { get; set; }
    public String billingCountry    { get; set; }
    public String billingState      { get; set; }

    // Tax Information
    public String gstin { get; set; }
    public String pan   { get; set; }

    // Totals
    public Decimal totalWithoutTax { get; set; }
    public Decimal totalItemGST    { get; set; }
    public Decimal totalWithTax    { get; set; }

    // Terms and Logistics
    public String paymentTerms       { get; set; }
    public String shipmentMethod     { get; set; }
    public String prepaymentPayment  { get; set; }
    public String SampleName         { get; set; }
    public String sampleType         { get; set; }
    public String couriernumber      { get; set; }
    public String deliveryStatus     { get; set; }
    public Date   ExpectedDeliveryDate { get; set; }

    // Contact Information
    public String email       { get; set; }
    public String phoneNumber { get; set; }
    public String website     { get; set; }
    public String Bank        { get; set; }
    public String AccountNo   { get; set; }
    public Decimal sampleShipping { get; set; }

    // ── NEW: Currency & India flag ──────────────────────────────────────────
    /**
     * ISO currency code pulled from the Order record (e.g. "INR", "USD", "EUR").
     * Displayed in the totals label as "Total INR Incl. GST", "Total USD", etc.
     */
    public String  currencyCode     { get; set; }

    /**
     * True when the account's billing country is India (case-insensitive).
     * Controls visibility of the GST % column and "Incl. GST" label in the VF page.
     */
    public Boolean isIndianBilling  { get; set; }
    // ────────────────────────────────────────────────────────────────────────

    // Order Items
    public List<OrderItemWrapper> items { get; set; }

    public class OrderItemWrapper {
        public String  itemCode    { get; set; }
        public String  itemName    { get; set; }
        public String  referenceNo { get; set; }
        public Decimal quantity    { get; set; }
        public String  unit        { get; set; }
        public String  HSN_SAC     { get; set; }
        public Decimal unitPrice   { get; set; }
        public Decimal amount      { get; set; }
        public String  Description { get; set; }
        public Decimal ItemGST     { get; set; }
    }

    public DRC_NBC_GenerateSamplePiController() {

        Id orderId = ApexPages.currentPage().getParameters().get('id');
        if (orderId == null) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Missing Order Id.'
            ));
            return;
        }

        // Fetch order with all required fields
        Order ord = [
            SELECT
                Id,
                OrderNumber,
                EffectiveDate,
                OwnerId,
                Owner.Name,
                CurrencyIsoCode,                          // ← dynamic currency
                Account.Name,
                Account.DRC_NBC_GST_Number__c,
                Account.DRC_NBC_Customer_Number__c,
                Account.BillingCountry,                   // ← billing country from Account
                DRC_NBC_Invoice_Export_Sequence_Number__c,
                DRC_NBC_Import_Starting_Sequence__c,
                ShippingStreet,
                ShippingCity,
                ShippingState,
                ShippingPostalCode,
                ShippingCountry,
                BillingStreet,
                BillingCity,
                BillingState,
                BillingPostalCode,
                BillingCountry,
                Type,
                DRC_NBC_Sample_Type__c,
                DRC_NBC_Sample_Amount__c,
                DRC_NBC_Sample_Shipping_Cost__c,
                DRC_NBC_Expected_Delivery_Date__c,
                DRC_NBC_Sample_Sequence_Number__c,
                DRC_NBC_Sample_Name__c,
                DRC_NBC_Payment_Terms__c,
                DRC_NBC_Delivery_status__c,
                DRC_NBC_Courier_Number__c,
                DRC_NBC_Inco_Terms__c,
                PoNumber
            FROM Order
            WHERE Id = :orderId
            LIMIT 1
        ];

        assignOrderSequenceNumber(ord);

        // ── Currency & India billing flag ───────────────────────────────────
        // Use the Order's own CurrencyIsoCode as the display label.
        currencyCode = String.isNotBlank(ord.CurrencyIsoCode)
            ? ord.CurrencyIsoCode
            : 'INR';

        // Prefer Account.BillingCountry; fall back to Order.BillingCountry.
        String accountBillingCountry = (ord.Account != null && String.isNotBlank(ord.Account.BillingCountry))
            ? ord.Account.BillingCountry
            : (String.isNotBlank(ord.BillingCountry) ? ord.BillingCountry : '');

        isIndianBilling = accountBillingCountry.equalsIgnoreCase('India')
                       || accountBillingCountry.equalsIgnoreCase('IN');
        // ────────────────────────────────────────────────────────────────────

        // Order Information
        orderNumber   = ord.OrderNumber;
        orderDate     = ord.EffectiveDate;
        SalesPerson   = ord.Owner.Name;
        customerName  = ord.Account.Name;
        billToCustomer = ord.Account.DRC_NBC_Customer_Number__c;
        customerGST   = ord.Account.DRC_NBC_GST_Number__c;
        ExpectedDeliveryDate = ord.DRC_NBC_Expected_Delivery_Date__c;
        couriernumber = ord.DRC_NBC_Courier_Number__c;
        deliveryStatus = ord.DRC_NBC_Delivery_status__c;
        sampleShipping = ord.DRC_NBC_Sample_Shipping_Cost__c != null
            ? ord.DRC_NBC_Sample_Shipping_Cost__c
            : 0;

        // Shipping Address
        shippingAddress    = (ord.ShippingStreet     != null ? ord.ShippingStreet     : '');
        shippingCity       = (ord.ShippingCity       != null ? ord.ShippingCity       : '');
        shippingState      = (ord.ShippingState      != null ? ord.ShippingState      : '');
        shippingPostalCode = (ord.ShippingPostalCode != null ? ord.ShippingPostalCode : '');
        shippingCountry    = (ord.ShippingCountry    != null ? ord.ShippingCountry    : '');

        // Billing Address
        billingAddress    = (ord.BillingStreet     != null ? ord.BillingStreet     : '');
        billingCity       = (ord.BillingCity       != null ? ord.BillingCity       : '');
        billingState      = (ord.BillingState      != null ? ord.BillingState      : '');
        billingPostalCode = (ord.BillingPostalCode != null ? ord.BillingPostalCode : '');
        billingCountry    = (ord.BillingCountry    != null ? ord.BillingCountry    : '');
        PO                = (ord.PoNumber          != null ? ord.PoNumber          : '');

        // Terms and Logistics
        paymentTerms  = ord.DRC_NBC_Payment_Terms__c;
        shipmentMethod = ord.DRC_NBC_Inco_Terms__c;
        SampleName    = ord.DRC_NBC_Sample_Name__c  != null ? ord.DRC_NBC_Sample_Name__c.toUpperCase()  : '';
        sampleType    = ord.DRC_NBC_Sample_Type__c  != null ? ord.DRC_NBC_Sample_Type__c.toUpperCase()  : '';

        // Contact Information
        email       = Label.DRC_NBC_Email;
        phoneNumber = Label.DRC_NBC_Phone;
        website     = Label.DRC_NBC_Website;
        Bank        = Label.DRC_NBC_Bank;
        AccountNo   = Label.DRC_NBC_AccountNo;

        // Sequence number
        if (ord.Type == 'Sample Order' && ord.DRC_NBC_Sample_Sequence_Number__c != null) {
            importSequence = String.valueOf(ord.DRC_NBC_Sample_Sequence_Number__c.intValue());
        }

        // Fetch Order Items
        List<OrderItem> orderItems = [
            SELECT
                Product2.Name,
                Product2.ProductCode,
                Quantity,
                UnitPrice,
                TotalPrice,
                Product2.QuantityUnitOfMeasure,
                DRC_NBC_Unit_Of_Measurement__c,
                Product2.DRC_NBC_HSN_SAC_Code__c,
                Product2.DRC_NBC_FG_Code__c,
                Description,
                order.DRC_NBC_Sample_Shipping_Cost__c,
                DRC_NBC_Item_GST__c
            FROM OrderItem
            WHERE OrderId = :orderId
            ORDER BY CreatedDate
        ];

        items          = new List<OrderItemWrapper>();
        totalWithoutTax = 0;
        totalItemGST    = 0;

        for (OrderItem oi : orderItems) {
            OrderItemWrapper wrap = new OrderItemWrapper();
            wrap.itemCode    = oi.Product2.ProductCode;
            wrap.itemName    = oi.Product2.Name;
            wrap.referenceNo = oi.Product2.DRC_NBC_FG_Code__c;
            wrap.quantity    = oi.Quantity;
            wrap.ItemGST     = oi.DRC_NBC_Item_GST__c;
            wrap.unit        = oi.Product2.QuantityUnitOfMeasure;
            wrap.unitPrice   = oi.UnitPrice;
            wrap.amount      = oi.TotalPrice;
            wrap.HSN_SAC     = oi.Product2.DRC_NBC_HSN_SAC_Code__c;
            wrap.Description = oi.Product2.Name;
            totalWithoutTax += oi.TotalPrice;
            totalItemGST    += (oi.DRC_NBC_Item_GST__c != null ? oi.DRC_NBC_Item_GST__c : 0);
            items.add(wrap);
        }

        // Calculate total with tax
        // For non-India billing GST is not applicable, so totalItemGST will be 0 (no GST lines)
        totalWithTax = totalWithoutTax + sampleShipping + (isIndianBilling ? totalItemGST : 0);
    }

    private void assignOrderSequenceNumber(Order ord) {
        if (ord.Type != null &&
            ord.Type == 'Sample Order' &&
            ord.DRC_NBC_Sample_Sequence_Number__c == null) {

            AggregateResult[] result = [
                SELECT MAX(DRC_NBC_Sample_Sequence_Number__c) maxSeq
                FROM Order
                WHERE Type = 'Sample Order'
            ];

            Decimal maxDecimal = (result.size() > 0 && result[0].get('maxSeq') != null)
                ? (Decimal) result[0].get('maxSeq')
                : Decimal.valueOf(Label.DRC_NBC_Sample_Sequence_Number);

            ord.DRC_NBC_Sample_Sequence_Number__c = Decimal.valueOf(maxDecimal.intValue() + 1);
        }
    }
}