force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <formula>CASE(
TEXT(DRC_NBC_Payment_Terms_Description__c),

&quot;PDC 90 days&quot;, &quot;PDC90&quot;,
&quot;PDC 60 days&quot;, &quot;PDC60&quot;,
&quot;PDC 45 days&quot;, &quot;PDC45&quot;,
&quot;PDC 30 days&quot;, &quot;PDC30&quot;,

&quot;Irrevocable LC at sight&quot;, &quot;IRRELC&quot;,
&quot;Irrevocable LC 90 days&quot;, &quot;IRRLC90&quot;,
&quot;Irrevocable LC 60 days&quot;, &quot;IRRLC60&quot;,
&quot;Irrevocable LC 45 days&quot;, &quot;IRRLC45&quot;,
&quot;Irrevocable LC 30 days&quot;, &quot;IRRLC30&quot;,

&quot;Free sample&quot;, &quot;FOC&quot;,

&quot;DP AT SIGHT&quot;, &quot;DPSIGHT&quot;,
&quot;DP 90 days&quot;, &quot;DP90&quot;,
&quot;DP 60 days&quot;, &quot;DP60&quot;,
&quot;DP 30 days&quot;, &quot;DP30&quot;,

&quot;DA 90 days&quot;, &quot;DA90&quot;,
&quot;DA 60 days&quot;, &quot;DA60&quot;,
&quot;DA 45 days&quot;, &quot;DA45&quot;,
&quot;DA 30 days&quot;, &quot;DA30&quot;,

&quot;Bond transfer&quot;, &quot;BONTRN&quot;,

&quot;BL 90 days&quot;, &quot;BL90&quot;,
&quot;BL 75 days&quot;, &quot;BL75&quot;,
&quot;BL 60 days&quot;, &quot;BL60&quot;,
&quot;BL 45 days&quot;, &quot;BL45&quot;,
&quot;BL 30 days&quot;, &quot;BL30&quot;,
&quot;BL 120 days&quot;, &quot;BL120&quot;,

&quot;90 days from invoice&quot;, &quot;INV90&quot;,
&quot;75 days from invoice&quot;, &quot;INV75&quot;,
&quot;7 days from invoice&quot;, &quot;INV07&quot;,
&quot;60 days from invoice&quot;, &quot;INV60&quot;,
&quot;45 days from invoice&quot;, &quot;INV45&quot;,
&quot;40 days from invoice&quot;, &quot;INV40&quot;,
&quot;30 days from invoice&quot;, &quot;INV30&quot;,
&quot;20 days from invoice&quot;, &quot;INV20&quot;,
&quot;15 days from invoice&quot;, &quot;INV15&quot;,
&quot;120 days from invoice&quot;, &quot;INV120&quot;,

&quot;60 days from LR&quot;, &quot;LR60&quot;,
&quot;30 days from goods arrival&quot;, &quot;30DDEL&quot;,

&quot;70% advance &amp; 30% CACD&quot;, &quot;70ADV-30CD&quot;,

&quot;50% advance &amp; 50% PDC 45 days&quot;, &quot;50ADV50PDC&quot;,
&quot;50% advance &amp; 50% CACD&quot;, &quot;50ADV-50CD&quot;,
&quot;50% advance &amp; 50% BL 60 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% BL 45 days&quot;, &quot;50ADV-50BL&quot;,
&quot;50% advance &amp; 50% against inspection&quot;, &quot;50ADV50INS&quot;,
&quot;50% advance &amp; 50% against dispatch&quot;, &quot;50ADV50DIS&quot;,
&quot;50% advance &amp; 50% 60 days from invoice&quot;, &quot;50ADV50INV&quot;,

&quot;40% advance &amp; 60% before dispatch&quot;, &quot;40ADV60DIS&quot;,

&quot;30% advance &amp; 70% CACD&quot;, &quot;30ADV-70CD&quot;,
&quot;30% advance &amp; 70% before dispatch&quot;, &quot;30ADV70DIS&quot;,

&quot;25% advance &amp; 75% LC at sight&quot;, &quot;25ADV-75LC&quot;,
&quot;25% advance &amp; 75% CACD&quot;, &quot;25ADV-75CD&quot;,
&quot;25% advance &amp; 75% BL 60 days&quot;, &quot;25ADV-75BL&quot;,
&quot;25% advance &amp; 75% before dispatch&quot;, &quot;25ADV75DIS&quot;,

&quot;20% advance &amp; 80% CACD&quot;, &quot;20ADV-80CD&quot;,
&quot;20% advance &amp; 80% before dispatch&quot;, &quot;20ADV80DIS&quot;,
&quot;20% advance &amp; 80% 60 days from invoice&quot;, &quot;20ADV80INV&quot;,

&quot;100% cash against copy documents&quot;, &quot;CACD&quot;,
&quot;100% against delivery&quot;, &quot;100%DEL&quot;,
&quot;100% advance against proforma&quot;, &quot;100%PI&quot;,
&quot;100% advance against BL copy&quot;, &quot;100%CBL&quot;,
&quot;100% advance&quot;, &quot;100%ADV&quot;,

&quot;10% advance &amp; 90% BL 30 days&quot;, &quot;10ADV-90BL&quot;,
&quot;10% ADV &amp; 90% CACD&quot;, &quot;10ADV-90CD&quot;,

&quot;10 days from invoice&quot;, &quot;INV10&quot;,

&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Comapny_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Comapny_Name__c</fullName>
    <label>Comapny Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SalesPerson_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SalesPerson_Code__c</fullName>
    <label>SalesPerson Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SendOrderEndpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SendOrderEndpoint__c</fullName>
    <label>SendOrderEndpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SendOrderLineEndpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SendOrderLineEndpoint__c</fullName>
    <label>SendOrderLineEndpoint</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Shipping_Address_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address_Endpoint__c</fullName>
    <label>Shipping Address Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Token_Generated_Time__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Token_Generated_Time__c</fullName>
    <label>Token Generated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <label>FG Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Term_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_SalesPerson_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SalesPerson_Code__c</fullName>
    <label>SalesPerson Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ajit Phadke</fullName>
            </value>
            <value>
                <fullName>Ajit Vasudevan</fullName>
            </value>
            <value>
                <fullName>AKSHTA SAWANT</fullName>
            </value>
            <value>
                <fullName>Amit Drolia</fullName>
            </value>
            <value>
                <fullName>Bhavesh Tambe</fullName>
            </value>
            <value>
                <fullName>Jigna Shah</fullName>
            </value>
            <value>
                <fullName>Kirit Acharya</fullName>
            </value>
            <value>
                <fullName>Manali Maniyar</fullName>
            </value>
            <value>
                <fullName>Nirmal Mansukhani</fullName>
            </value>
            <value>
                <fullName>Shekhar Rege</fullName>
            </value>
            <value>
                <fullName>Shirley D&apos;silva</fullName>
            </value>
            <value>
                <fullName>Tanay Drolia</fullName>
            </value>
            <value>
                <fullName>Vijay Gurnani</fullName>
            </value>
            <value>
                <fullName>Yash Drolia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DRC_NBC_Order_BC_Integration_Test.cls
/**
 * @File Name : DRC_NBC_Order_BC_Integration_Test.cls
 * @Description : Comprehensive test class for Order BC Integration classes
 * @Author : Test Class Generator
 * @Last Modified On : January 05, 2026
 **/
@isTest
private class DRC_NBC_Order_BC_Integration_Test {
    
    // Test data setup
    @testSetup
    static void setupTestData() {
        // ===== CREATE CUSTOM SETTING FIRST =====
        DRC_NBC_BC_Integration__c customSetting = new DRC_NBC_BC_Integration__c(
            Name = 'Test_Config_Sandbox',
            Name__c = 'Sandbox',
            DRC_NBC_Comapny_Name__c = 'D.R. COATS INK AND RESINS PVT. LTD',
            DRC_NBC_Endpoint__c = 'https://api.businesscentral.dynamics.com/v2.0/production/api/v2.0',
            DRC_NBC_SendOrderEndpoint__c = 'SalesOrders',
            DRC_NBC_Shipping_Address_Endpoint__c = 'ShipToAddress',
            DRC_NBC_SendOrderLineEndpoint__c = 'SalesOrderLines',
            DRC_NBC_SalesPerson_Code__c = 'SP001',
            DRC_NBC_Token_Generated_Time__c = System.now()
        );
        insert customSetting;
        
        System.debug(' Custom Setting Created: ' + customSetting.Name);
        
        // Create Account
        Account testAccount = new Account(
            Name = 'Test Account',
            DRC_NBC_Customer_Number__c = 'CUST001',
            DRC_NBC_PAN_No__c = 'AWVPY9594J'
        );
        insert testAccount;
        
        // Create Contact
        Contact billToContact = new Contact(
            FirstName = 'Bill',
            LastName = 'Contact',
            AccountId = testAccount.Id,
            Email = 'bill@test.com'
        );
        insert billToContact;
        
        Contact shipToContact = new Contact(
            FirstName = 'Ship',
            LastName = 'Contact',
            AccountId = testAccount.Id,
            Email = 'ship@test.com'
        );
        insert shipToContact;
        
        // Create Pricebook
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook;
        
        // Create Product
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            ProductCode = 'PROD001',
            IsActive = true,
            DRC_NBC_FG_Code__c = 'FG001',
            DRC_NBC_HSN_SAC_Code__c = 'HSN001',
            QuantityUnitOfMeasure = 'Each'
        );
        insert testProduct;
        
        // Create Pricebook Entry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbe;
        
        // Create Order
        Order testOrder = new Order(
            AccountId = testAccount.Id,
            EffectiveDate = Date.today(),
            EndDate = Date.today().addDays(30),
            Status = 'Draft',
            Pricebook2Id = standardPricebook.Id,
            BillToContactId = billToContact.Id,
            ShipToContactId = shipToContact.Id,
            PoNumber = 'PO12345',
            PoDate = Date.today(),
            DRC_NBC_Payment_Terms__c = '10% - 90%',
            DRC_NBC_Inco_Terms__c = 'Cost Insurance & Freight (CIF)',
            DRC_NBC_Cust_Order_Number__c = 'ORD-001',
            ShippingStreet = '123 Test St',
            ShippingCity = 'Test City',
            ShippingState = 'Maharashtra',
            ShippingPostalCode = '12345',
            ShippingCountry = 'India',
            ShippingCountryCode = 'IN',
            DRC_NBC_Warehouse__c = 'C4/2/2 D.R COATS INK & RESINS PVT LTD (UNIT-III)'
        );
        insert testOrder;
        
        // Create Shipping Address
        DRC_NBC_Addresses__c shippingAddress = new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c = testAccount.Id,
            DRC_NBC_Order__c = testOrder.Id,
            DRC_NBC_Type__c = 'Shipping',
            DRC_NBC_Ship_To_Code__c = 'SHIP001',
            DRC_NBC_Warehouse__c = 'C4/2/2 D.R COATS INK & RESINS PVT LTD (UNIT-III)',
            DRC_NBC_Address__Street__s = '123 Test St',
            DRC_NBC_Address__City__s = 'Test City',
            DRC_NBC_Address__StateCode__s = 'MH',
            DRC_NBC_Address__PostalCode__s = '12345',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_GST_Number__c = '27AWVPY9594J1ZY'
        );
        insert shippingAddress;
        
        // Update Order with Shipping Address
        testOrder.DRC_NBC_Shipping_Address__c = shippingAddress.Id;
        update testOrder;
        
        // Create Order Line Items
        OrderItem testOrderItem = new OrderItem(
            OrderId = testOrder.Id,
            Product2Id = testProduct.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 10,
            UnitPrice = 100.00
        );
        insert testOrderItem;
        
        System.debug(' Test data setup completed');
    }
    
    // Test 1: Verify Custom Setting Created
    @isTest
    static void testCustomSettingExists() {
        Test.startTest();
        DRC_NBC_BC_Integration__c setting = DRC_NBC_BC_Callout_Utility.getConfig();
        Test.stopTest();
        
        System.debug('Custom Setting Name: ' + setting.Name__c);
        System.debug('Company Name: ' + setting.DRC_NBC_Comapny_Name__c);
        System.debug('Endpoint: ' + setting.DRC_NBC_Endpoint__c);
    }
    
    // Test 2: DRC_NBC_Order_BC_Callout - Order Already Synced
    @isTest
    static void testOrderAlreadySynced() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Mark order as already synced
        testOrder.DRC_NBC_Order_Sync_To_BC__c = true;
        update testOrder;
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_BC_Callout(testOrder.Id));
        Test.stopTest();
        
        // Verify order remains synced
        Order updatedOrder = [SELECT DRC_NBC_Order_Sync_To_BC__c FROM Order WHERE Id = :testOrder.Id];
        System.debug('Order Sync Status: ' + updatedOrder.DRC_NBC_Order_Sync_To_BC__c);
    }
    
    // Test 3: DRC_NBC_Order_BC_Callout - Needs Ship-To Code
    @isTest
    static void testNeedsShipToCode() {
        Order testOrder = [SELECT Id, DRC_NBC_Shipping_Address__c FROM Order LIMIT 1];
        
        // Clear Ship-To Code
        DRC_NBC_Addresses__c address = [SELECT Id FROM DRC_NBC_Addresses__c WHERE Id = :testOrder.DRC_NBC_Shipping_Address__c];
        address.DRC_NBC_Ship_To_Code__c = null;
        update address;
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_BC_Callout(testOrder.Id));
        Test.stopTest();
        
        // Verify chain was initiated
        System.debug('Ship-To Code generation initiated');
    }
    
    // Test 4: DRC_NBC_Order_BC_Callout - Needs Order Number
    @isTest
    static void testNeedsOrderNumber() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Clear Order Number
        testOrder.DRC_NBC_Cust_Order_Number__c = null;
        update testOrder;
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_BC_Callout(testOrder.Id));
        Test.stopTest();
        
        // Verify chain was initiated
        System.debug('Order Number generation initiated');
    }
    
    // Test 5: DRC_NBC_Order_BC_Callout - No DML Needed
    @isTest
    static void testNoDMLNeeded() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Mock HTTP Callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_BC_Callout(testOrder.Id));
        Test.stopTest();
        
        // Verify callout chain was initiated
        System.debug('Callout chain initiated');
    }
    
    // Test 6: DRC_NBC_Order_BC_Callout - Exception Handling
    @isTest
    static void testOrderCalloutException() {
        // Create order without required fields to trigger exception
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Order invalidOrder = new Order(
            AccountId = testAccount.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
        insert invalidOrder;
        
        Test.startTest();
        try {
            System.enqueueJob(new DRC_NBC_Order_BC_Callout(invalidOrder.Id));
        } catch (Exception e) {
            System.debug('Exception handled: ' + e.getMessage());
        }
        Test.stopTest();
        
        // Verify error was logged
        System.debug('Exception test completed');
    }
    
    // Test 7: DRC_NBC_Order_DML_Handler - Ship-To Code Generation
    @isTest
    static void testDMLHandlerShipToCode() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_DML_Handler(testOrder.Id, true, false));
        Test.stopTest();
        
        // Verify DML execution
        System.debug('Ship-To Code DML handler executed');
    }
    
    // Test 8: DRC_NBC_Order_DML_Handler - Order Number Generation
    @isTest
    static void testDMLHandlerOrderNumber() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_DML_Handler(testOrder.Id, false, true));
        Test.stopTest();
        
        // Verify DML execution
        System.debug('Order Number DML handler executed');
    }
    
    // Test 9: DRC_NBC_Order_DML_Handler - Both Generations
    @isTest
    static void testDMLHandlerBoth() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_DML_Handler(testOrder.Id, true, true));
        Test.stopTest();
        
        // Verify DML execution
        System.debug('Both DML handlers executed');
    }
    
    // Test 10: DRC_NBC_Order_Callout_Handler - Success
    @isTest
    static void testShippingCalloutSuccess() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify shipping callout executed
        System.debug('Shipping callout executed successfully');
    }
    
    // Test 11: DRC_NBC_Order_Callout_Handler - No Shipping Address
    @isTest
    static void testShippingCalloutNoAddress() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Remove shipping address
        testOrder.DRC_NBC_Shipping_Address__c = null;
        update testOrder;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify skipped shipping callout
        System.debug('Shipping callout skipped - no address');
    }
    
    // Test 12: DRC_NBC_Order_Callout_Handler - Callout Failure
    @isTest
    static void testShippingCalloutFailure() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(400, 'Error'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify error handling
        System.debug('Shipping callout failure handled');
    }
    
    // Test 13: DRC_NBC_Order_Only_Callout_Handler - Success
    @isTest
    static void testOrderOnlyCalloutSuccess() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Only_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify order callout executed
        System.debug('Order callout executed successfully');
    }
    
    // Test 14: DRC_NBC_Order_Only_Callout_Handler - Missing Order Number
    @isTest
    static void testOrderOnlyCalloutMissingNumber() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Clear order number
        testOrder.DRC_NBC_Cust_Order_Number__c = null;
        update testOrder;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Only_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify validation handled
        System.debug('Order number validation handled');
    }
    
    // Test 15: DRC_NBC_Order_Only_Callout_Handler - Callout Failure
    @isTest
    static void testOrderOnlyCalloutFailure() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, 'Server Error'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_Only_Callout_Handler(testOrder.Id));
        Test.stopTest();
        
        // Verify error handling
        System.debug('Order callout failure handled');
    }
    
    // Test 16: DRC_NBC_Order_BC_Update_Service - Process Order Update
    @isTest
    static void testProcessOrderUpdate() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        DRC_NBC_Order_BC_Update_Service.processOrderUpdate(testOrder.Id);
        Test.stopTest();
        
        // Verify order was marked as synced
        Order updatedOrder = [SELECT DRC_NBC_Order_Sync_To_BC__c, DRC_NBC_Integration_Status__c FROM Order WHERE Id = :testOrder.Id];
        System.debug('Order Sync Status: ' + updatedOrder.DRC_NBC_Order_Sync_To_BC__c);
        System.debug('Integration Status: ' + updatedOrder.DRC_NBC_Integration_Status__c);
    }
    
    // Test 17: DRC_NBC_Order_BC_Update_Service - Failed Order Update
    @isTest
    static void testFailedOrderUpdate() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        DRC_NBC_Order_BC_Update_Service.failedOrderUpdate(testOrder.Id);
        Test.stopTest();
        
        // Verify order was marked as failed
        Order updatedOrder = [SELECT DRC_NBC_Integration_Status__c FROM Order WHERE Id = :testOrder.Id];
        System.debug('Integration Status: ' + updatedOrder.DRC_NBC_Integration_Status__c);
    }
    
    // Test 18: DRC_NBC_Shipping_BC_Integration - Success
    @isTest
    static void testShippingIntegrationSuccess() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        String payload = '{"test": "data"}';
        String endpoint = 'ShipToAddress';
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        DRC_NBC_Shipping_BC_Integration integration = new DRC_NBC_Shipping_BC_Integration(
            endpoint, 'POST', payload, testAccount.Id
        );
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
        
        // Verify response
        System.debug('Shipping Integration Response Code: ' + response.getStatusCode());
    }
    
    // Test 19: DRC_NBC_Shipping_BC_Integration - Error
    @isTest
    static void testShippingIntegrationError() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        
        String payload = '{"test": "data"}';
        String endpoint = 'ShipToAddress';
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(400, 'Bad Request'));
        
        Test.startTest();
        DRC_NBC_Shipping_BC_Integration integration = new DRC_NBC_Shipping_BC_Integration(
            endpoint, 'POST', payload, testAccount.Id
        );
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
        
        // Verify error handling
        System.debug('Shipping Integration Error Code: ' + response.getStatusCode());
    }
    
    // Test 20: DRC_NBC_Order_BC_Integration - Success
    @isTest
    static void testOrderIntegrationSuccess() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        String payload = '{"test": "data"}';
        String endpoint = 'SalesOrders';
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        DRC_NBC_Order_BC_Integration integration = new DRC_NBC_Order_BC_Integration(
            endpoint, 'POST', payload, testOrder.Id
        );
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
        
        // Verify response
        System.debug('Order Integration Response Code: ' + integration.httpStatusCode);
        System.debug('Response Summary: ' + integration.responseSummary);
    }
    
    // Test 21: DRC_NBC_Order_BC_Integration - Error
    @isTest
    static void testOrderIntegrationError() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        String payload = '{"test": "data"}';
        String endpoint = 'SalesOrders';
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, 'Server Error'));
        
        Test.startTest();
        DRC_NBC_Order_BC_Integration integration = new DRC_NBC_Order_BC_Integration(
            endpoint, 'POST', payload, testOrder.Id
        );
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
        
        // Verify error handling
        System.debug('Order Integration Error Code: ' + integration.httpStatusCode);
        System.debug('Error Summary: ' + integration.responseSummary);
    }
    
    // Test 22: Test mapOrderToBCPayload - Complete Order
    @isTest
    static void testMapOrderToBCPayload() {
        Order testOrder = [
            SELECT Id, Name, AccountId, Account.Name, Account.DRC_NBC_Customer_Number__c,
                   EffectiveDate, PoNumber, PoDate, DRC_NBC_Warehouse__c, ShipToContactId,
                   DRC_NBC_Cust_Order_Number__c, Status, DRC_NBC_Payment_Terms__c,
                   DRC_NBC_Inco_Terms__c, ShippingStreet, ShippingCity, ShippingState,
                   ShippingPostalCode, ShippingCountry, DRC_NBC_Shipping_Address__c,
                   DRC_NBC_Shipping_Address__r.DRC_NBC_Warehouse__c, RecordType.Name
            FROM Order LIMIT 1
        ];
        
        Test.startTest();
        DRC_NBC_Integration_Payload.OrderPayload payload = 
            DRC_NBC_Order_BC_Callout.mapOrderToBCPayload(testOrder);
        Test.stopTest();
        
        // Verify payload fields
        System.debug('Payload Document Type: ' + payload.Document_Type);
        System.debug('Payload No: ' + payload.No);
        System.debug('Payload Customer No: ' + payload.Sell_to_Customer_No);
        System.debug('Payload Order Date: ' + payload.Order_Date);
    }
    
    // Test 23: Test mapOrderToBCPayload - Long Address
    @isTest
    static void testMapOrderToBCPayloadLongAddress() {
        Order testOrder = [SELECT Id, DRC_NBC_Shipping_Address__c FROM Order LIMIT 1];
        
        // Create address with very long street
        DRC_NBC_Addresses__c address = [SELECT Id FROM DRC_NBC_Addresses__c WHERE Id = :testOrder.DRC_NBC_Shipping_Address__c];
        address.DRC_NBC_Address__Street__s = 'This is a very long street address that exceeds the normal length to test the address splitting functionality in the integration payload mapper method';
        update address;
        
        Test.startTest();
        Order updatedOrder = DRC_NBC_Order_BC_Callout.getOrderDetails(testOrder.Id);
        DRC_NBC_Integration_Payload.OrderPayload payload = 
            DRC_NBC_Order_BC_Callout.mapOrderToBCPayload(updatedOrder);
        Test.stopTest();
        
        // Verify address splitting
        System.debug('Ship to Address: ' + payload.Ship_to_Address);
        System.debug('Ship to Address 2: ' + payload.Ship_to_Address_2);
    }
    
    // Test 24: Test getOrderDetails method
    @isTest
    static void testGetOrderDetails() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        Test.startTest();
        Order retrievedOrder = DRC_NBC_Order_BC_Callout.getOrderDetails(testOrder.Id);
        Test.stopTest();
        
        // Verify order retrieval
        System.debug('Retrieved Order ID: ' + retrievedOrder.Id);
        System.debug('Order Number: ' + retrievedOrder.OrderNumber);
        System.debug('Customer Number: ' + retrievedOrder.Account.DRC_NBC_Customer_Number__c);
    }
    
    // Test 25: Multiple Queueable Chain Test
    @isTest
    static void testCompleteQueueableChain() {
        Order testOrder = [SELECT Id FROM Order LIMIT 1];
        
        // Clear ship-to code to trigger full chain
        DRC_NBC_Addresses__c address = [SELECT Id FROM DRC_NBC_Addresses__c LIMIT 1];
        address.DRC_NBC_Ship_To_Code__c = null;
        update address;
        
        testOrder.DRC_NBC_Cust_Order_Number__c = null;
        update testOrder;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        System.enqueueJob(new DRC_NBC_Order_BC_Callout(testOrder.Id));
        Test.stopTest();
        
        // Verify chain execution
        System.debug('Complete queueable chain executed');
    }
    
    // Test 26: Bulk Test - Multiple Orders
    @isTest
    static void testBulkOrders() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        Pricebook2 pricebook = new Pricebook2(Id = Test.getStandardPricebookId());
        
        List<Order> orders = new List<Order>();
        for (Integer i = 0; i < 5; i++) {
            orders.add(new Order(
                AccountId = testAccount.Id,
                EffectiveDate = Date.today(),
                EndDate = Date.today().addDays(30),
                Status = 'Draft',
                Pricebook2Id = pricebook.Id,
                BillToContactId = contact.Id,
                ShipToContactId = contact.Id,
                DRC_NBC_Cust_Order_Number__c = 'ORD-00' + i
            ));
        }
        insert orders;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, 'Success'));
        
        Test.startTest();
        for (Order ord : orders) {
            try {
                System.enqueueJob(new DRC_NBC_Order_BC_Callout(ord.Id));
            } catch (Exception e) {
                System.debug('Bulk test exception: ' + e.getMessage());
            }
        }
        Test.stopTest();
        
        // Verify bulk processing
        System.debug('Bulk orders processed');
    }
    
    // Mock HTTP Response Generator
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;
        
        public MockHttpResponseGenerator(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }
        
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(responseBody);
            res.setHeader('Content-Type', 'application/json');
            return res;
        }
    }
}