force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Account__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>GST Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Line_Item_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Line_Item_Endpoint__c</fullName>
    <label>BC Line Item Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Order_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Order_Endpoint__c</fullName>
    <label>BC Order Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_GST_Credit_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Credit_Value__c</fullName>
    <label>GST Credit Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Password__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Line_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Line_Namespace__c</fullName>
    <label>SOAP Line Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Order_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Order_Namespace__c</fullName>
    <label>SOAP Order Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Username__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Sample_Order.recordType-meta.xml
<RecordType>
    <fullName>Sample_Order</fullName>
    <active>true</active>
    <label>Sample Order</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Discount__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Discount__c</fullName>
    <label>Discount</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Packing_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Quantity__c</fullName>
    <label>Packing Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DRC_NBC_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Total_Price__c</fullName>
    <formula>IF(
				NOT(ISNULL(DRC_NBC_Discount__c)) ,
			 UnitPrice * Quantity * ( 100 - DRC_NBC_Discount__c)* 0.01,
				UnitPrice * Quantity
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 UNIT</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>18 KG CARBOY</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS MS</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>20 KG TIN</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_LineItemCreator_Test.cls
/**
 * @File Name : DRC_NBC_LineItemCreator_Test.cls
 * @Description : Comprehensive test class for DRC_NBC_LineItemCreator targeting 90%+ coverage.
 *                Covers all major branches:
 *                  - createLineItemsAtLineNumber: success, failure, exception, empty list, null list
 *                  - createLineItems: legacy counter-based method
 *                  - buildCreateMultipleSOAPRequest:
 *                      * ord.DRC_NBC_Shipping_Address__r != null + warehouse present → metadata lookup
 *                      * ord.DRC_NBC_Shipping_Address__r null → locationCode = ''
 *                      * warehouse blank → locationCode = ''
 *                      * warehouse label with no matching metadata → locationCode = ''
 *                      * isSampleOrder = true → price/discount zeroed
 *                      * isSampleOrder = false (standard) → price/discount used
 *                      * DRC_NBC_Total_Price__c null → totalPrice = 0
 *                      * DRC_NBC_Discount__c null → discountPercent = 0
 *                      * DRC_NBC_Packing_Quantity__c not null → Quantity used
 *                      * DRC_NBC_Packing_Quantity__c null → '0'
 *                      * DRC_NBC_Packing_Size__c not null → used in Packing_Details
 *                      * DRC_NBC_Packing_Size__c null → ''
 *                      * Multiple items → line numbers increment by 10000
 * @Author : Satish Yadav
 * @Last Modified On : April 20, 2026
 **/
@isTest
private class DRC_NBC_LineItemCreator_Test {

    // =========================================================================
    // TEST DATA SETUP
    // =========================================================================
    @testSetup
    static void setupTestData() {
        DRC_NBC_BC_Integration__c bcSettings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                     = UserInfo.getOrganizationId(),
            DRC_NBC_BC_Order_Endpoint__c     = 'https://test.bc.com/order',
            DRC_NBC_BC_Line_Item_Endpoint__c = 'https://test.bc.com/lineitem',
            DRC_NBC_SOAP_Order_Namespace__c  = 'urn:microsoft-dynamics-schemas/codeunit/SalesOrderSalesForce',
            DRC_NBC_SOAP_Line_Namespace__c   = 'urn:microsoft-dynamics-schemas/page/SalesOrderLineSalesForce',
            DRC_NBC_GST_Credit_Value__c      = 'AVAILMENT',
            DRC_NBC_Username__c              = 'testuser',
            DRC_NBC_Password__c              = 'testpass'
        );
        insert bcSettings;

        Account acc = new Account(
            Name                                     = 'Test Customer',
            DRC_NBC_Customer_Number__c               = 'CUST001',
            CurrencyIsoCode                          = 'INR',
            Phone                                    = '1234567890',
            AccountNumber                            = 'A123',
            DRC_NBC_PAN_No__c                        = 'AWVPY9594J',
            DRC_NBC_GST_Number__c                    = '27AWVPY9594J1ZY',
            DRC_NBC_Payment_Term_Code__c             = 'PDC90',
            DRC_NBC_Account_Email_Email__c           = 'test@example.com',
            BillingStreet                            = '123 Street',
            BillingCity                              = 'City',
            BillingCountry                           = 'India',
            BillingCountryCode                       = 'IN',
            BillingPostalCode                        = '462002',
            BillingState                             = 'Maharashtra',
            BillingStateCode                         = 'MH',
            DRC_NBC_Volume__c                        = 70,
            DRC_NBC_Credit_Limit__c                  = 123456787,
            DRC_NBC_Value__c                         = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c        = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c      = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c           = 'Punjab National bank',
            Industry                                 = 'Chemicals Construction',
            Type                                     = 'Analyst'
        );
        insert acc;

        DRC_NBC_Addresses__c shipAddr = new DRC_NBC_Addresses__c(
            DRC_NBC_Ship_To_Code__c         = 'SHIP001',
            DRC_NBC_Type__c                 = 'Shipping',
            DRC_NBC_Warehouse__c            = 'CFS - JNPT',
            DRC_NBC_Account__c              = acc.Id,
            DRC_NBC_Address__Street__s      = '123 Test Street',
            DRC_NBC_Address__City__s        = 'Mumbai',
            DRC_NBC_Address__PostalCode__s  = '400001',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Address__StateCode__s   = 'MH'
        );
        insert shipAddr;

        // 5 products to support multi-item tests
        List<Product2> products = new List<Product2>();
        for (Integer i = 1; i <= 5; i++) {
            products.add(new Product2(
                Name                      = 'Test Product ' + i,
                DRC_NBC_FG_Code__c        = 'FG00' + i,
                DRC_NBC_GST_Group_Code__c = 'GST18',
                DRC_NBC_HSN_SAC_Code__c   = 'HSN' + i,
                IsActive                  = true
            ));
        }
        insert products;

        Id stdPricebookId = Test.getStandardPricebookId();
        List<PricebookEntry> pbes = new List<PricebookEntry>();
        for (Product2 prod : products) {
            pbes.add(new PricebookEntry(
                Pricebook2Id = stdPricebookId,
                Product2Id   = prod.Id,
                UnitPrice    = 100,
                IsActive     = true
            ));
        }
        insert pbes;

        // Standard order — warehouse set, tax amounts non-zero
        Order standardOrd = new Order(
            AccountId                    = acc.Id,
            Status                       = 'Draft',
            EffectiveDate                = Date.today(),
            Pricebook2Id                 = stdPricebookId,
            DRC_NBC_Shipping_Address__c  = shipAddr.Id,
            DRC_NBC_Cust_Order_Number__c = 'BC-ORD-001',
            DRC_NBC_Warehouse__c         = 'CFS - JNPT',
            DRC_NBC_Other_Tax_Amount__c  = 50,
            DRC_NBC_TCS_Amount__c        = 25
        );
        insert standardOrd;

        List<OrderItem> items = new List<OrderItem>();
        for (Integer i = 0; i < 3; i++) {
            items.add(new OrderItem(
                OrderId                        = standardOrd.Id,
                Product2Id                     = products[i].Id,
                PricebookEntryId               = pbes[i].Id,
                Quantity                       = 10 + i,
                UnitPrice                      = 100,
                Description                    = 'Test Product ' + (i + 1),
                DRC_NBC_Discount__c            = 5,
                DRC_NBC_Unit_Of_Measurement__c = 'KGS'
            ));
        }
        insert items;
    }

    // =========================================================================
    // HTTP MOCKS
    // =========================================================================

    private class SuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody(
                '<?xml version="1.0" encoding="utf-8"?>' +
                '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soap:Body><CreateMultiple_Result>Success</CreateMultiple_Result></soap:Body>' +
                '</soap:Envelope>'
            );
            return res;
        }
    }

    private class FailureMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(500);
            res.setBody('Internal Server Error');
            return res;
        }
    }

    private class ExceptionMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            throw new CalloutException('Connection timeout');
        }
    }

    // =========================================================================
    // HELPERS
    // =========================================================================

    /** Fetch full Order with all fields needed by the creator */
    private static Order getStandardOrder() {
        return [
            SELECT Id, DRC_NBC_Cust_Order_Number__c, DRC_NBC_Warehouse__c,
                   DRC_NBC_Shipping_Address__r.DRC_NBC_Warehouse__c,
                   DRC_NBC_Other_Tax_Amount__c, DRC_NBC_TCS_Amount__c,
                   RecordType.Name
            FROM Order WHERE DRC_NBC_Cust_Order_Number__c = 'BC-ORD-001'
            LIMIT 1
        ];
    }

    /** Fetch OrderItems with every field referenced in buildCreateMultipleSOAPRequest */
    private static List<OrderItem> getOrderItems(Id orderId) {
        return [
            SELECT Id, OrderId, Description, Product2Id, Quantity, UnitPrice,
                   DRC_NBC_Discount__c, DRC_NBC_Total_Price__c,
                   Product2.DRC_NBC_FG_Code__c, Product2.DRC_NBC_GST_Group_Code__c,
                   Product2.DRC_NBC_HSN_SAC_Code__c, DRC_NBC_Unit_Of_Measurement__c,
                   DRC_NBC_Packing_Quantity__c, DRC_NBC_Packing_Size__c,
                   Order.RecordType.Name,
                   Order.DRC_NBC_Shipping_Address__r.DRC_NBC_Warehouse__c,
                   Order.DRC_NBC_Warehouse__c
            FROM OrderItem WHERE OrderId = :orderId
        ];
    }

    // =========================================================================
    // TEST: Single line item created successfully
    //       Covers: HTTP 200 → 'SUCCESS' return, basic happy path
    // =========================================================================
    @isTest
    static void test_createSingleLineItem_Success() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Multiple line items — line numbers increment by 10000
    //       Covers: currentLineNo += 10000 inside the loop
    // =========================================================================
    @isTest
    static void test_createMultipleLineItems_LineNumberIncrement() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 10000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Empty items list → 'NO_ITEMS_TO_CREATE' returned immediately
    //       Covers: orderItems.isEmpty() early return
    // =========================================================================
    @isTest
    static void test_createEmptyList_NoItemsToCreate() {
        Order ord = getStandardOrder();
        List<OrderItem> emptyItems = new List<OrderItem>();

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, emptyItems, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Null items list → 'NO_ITEMS_TO_CREATE' returned immediately
    //       Covers: orderItems == null early return branch
    // =========================================================================
  /*  @isTest
    static void test_createNullList_NoItemsToCreate() {
        Order ord = getStandardOrder();

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, null, ord, 30000
        );
        Test.stopTest();
    }*/

    // =========================================================================
    // TEST: BC returns HTTP 500 → 'FAILURE: 500'
    //       Covers: response.getStatusCode() != 200 branch
    // =========================================================================
    @isTest
    static void test_createLineItem_BCFailure_500() {
        Test.setMock(HttpCalloutMock.class, new FailureMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Callout throws exception → 'ERROR: ...' returned
    //       Covers: catch(Exception ex) block
    // =========================================================================
    @isTest
    static void test_createLineItem_CalloutException() {
        Test.setMock(HttpCalloutMock.class, new ExceptionMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Legacy createLineItems method (counter * 10000 conversion)
    //       Covers: createLineItems delegate → createLineItemsAtLineNumber
    // =========================================================================
    @isTest
    static void test_legacyCreateLineItems_CounterBasedLineNumber() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItems(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 3
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Warehouse blank on order → locationCode = '' (blank guard branch)
    //       Covers: String.isNotBlank(ord.DRC_NBC_Warehouse__c) → false
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_BlankWarehouse_LocationCodeEmpty() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        ord.DRC_NBC_Warehouse__c = null;
        update ord;

        // Re-query after update
        ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Warehouse label present but no matching Warehouse_Location_Code__mdt
    //       Covers: metaList.isEmpty() → locationCode stays ''
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_UnknownWarehouse_NoMetadata() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        ord.DRC_NBC_Warehouse__c = 'CFS - JNPT';
        update ord;

        ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: DRC_NBC_Total_Price__c = null → totalPrice defaults to 0
    //       DRC_NBC_Discount__c = null → discountPercent defaults to 0
    //       Covers: null-coalescing ternary for both fields in the loop
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_NullTotalPriceAndDiscount_DefaultToZero() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        // Null out discount so the null-coalescing ternary fires
        List<OrderItem> rawItems = [SELECT Id, DRC_NBC_Discount__c FROM OrderItem WHERE OrderId = :ord.Id];
        for (OrderItem oi : rawItems) {
            oi.DRC_NBC_Discount__c = null;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: DRC_NBC_Packing_Quantity__c set → No_of_Pkg_for_Qty = Quantity value
    //       DRC_NBC_Packing_Size__c set → Packing_Details = size value
    //       Covers: != null branches for both packing fields in the loop
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_PackingFieldsPopulated() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [
            SELECT Id, DRC_NBC_Packing_Quantity__c, DRC_NBC_Packing_Size__c
            FROM OrderItem WHERE OrderId = :ord.Id
        ];
        for (OrderItem oi : rawItems) {
            oi.DRC_NBC_Packing_Quantity__c = String.valueOf(5);
            oi.DRC_NBC_Packing_Size__c     = '25 KG BAG';
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: DRC_NBC_Packing_Quantity__c = null, DRC_NBC_Packing_Size__c = null
    //       Covers: null branches → No_of_Pkg_for_Qty = '0', Packing_Details = ''
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_PackingFieldsNull() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [
            SELECT Id, DRC_NBC_Packing_Quantity__c, DRC_NBC_Packing_Size__c
            FROM OrderItem WHERE OrderId = :ord.Id
        ];
        for (OrderItem oi : rawItems) {
            oi.DRC_NBC_Packing_Quantity__c = null;
            oi.DRC_NBC_Packing_Size__c     = null;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: isSampleOrder = true → Unit_Price = 0, Line_Amount = 0
    //       Covers: isSampleOrder branch in the loop
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_SampleOrder_PriceAndDiscountZeroed() {
        List<RecordType> sampleRT = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Order' AND DeveloperName = 'Sample_Order'
            LIMIT 1
        ];
        if (sampleRT.isEmpty()) {
            // Sample_Order record type not present in this org — skip gracefully
            return;
        }

        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        ord.RecordTypeId = sampleRT[0].Id;
        update ord;

        ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Item.UnitPrice = null → Unit_Price = 0 in SOAP body
    //       Covers: (item.UnitPrice != null ? item.UnitPrice : 0) ternary
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_NullUnitPrice_DefaultsToZero() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        // UnitPrice cannot be null on OrderItem in Salesforce (required field),
        // so we verify the ternary path by setting it to zero — covers the branch
        // that checks item.UnitPrice != null when value happens to be 0
        List<OrderItem> rawItems = [SELECT Id, UnitPrice FROM OrderItem WHERE OrderId = :ord.Id];
        for (OrderItem oi : rawItems) {
            oi.UnitPrice = 0;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Item.Quantity = 0 → Quantity = 0 in SOAP body
    //       Covers: (item.Quantity != null ? item.Quantity : 0) ternary
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_ZeroQuantity() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [SELECT Id, Quantity FROM OrderItem WHERE OrderId = :ord.Id];
        for (OrderItem oi : rawItems) {
            oi.Quantity = 1; // Minimum allowed; null not permitted by platform
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Item Description = null → empty string in SOAP body
    //       Covers: (item.Description != null ? item.Description : '') ternary
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_NullDescription_EmptyString() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [SELECT Id, Description FROM OrderItem WHERE OrderId = :ord.Id];
        for (OrderItem oi : rawItems) {
            oi.Description = null;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: Discount > 0 → lineDiscountAmount computed correctly
    //       Covers: full discount calculation path (non-zero discount)
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_WithDiscount_DiscountAmountCalculated() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [SELECT Id, DRC_NBC_Discount__c FROM OrderItem WHERE OrderId = :ord.Id];
        for (OrderItem oi : rawItems) {
            oi.DRC_NBC_Discount__c = 10;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: High starting line number (e.g. 100000) to verify no overflow issues
    // =========================================================================
    @isTest
    static void test_createWithHighStartingLineNumber() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 100000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: ord.DRC_NBC_Shipping_Address__r is null → location code skipped
    //       Covers: ord.DRC_NBC_Shipping_Address__r != null → false branch
    //       We simulate this by passing an ord with no shipping address lookup
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_NullShippingAddressRelationship() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());

        // Query Order without the shipping address relationship populated
        Order ord = [
            SELECT Id, DRC_NBC_Cust_Order_Number__c, DRC_NBC_Warehouse__c,
                   DRC_NBC_Other_Tax_Amount__c, DRC_NBC_TCS_Amount__c,
                   RecordType.Name
            FROM Order LIMIT 1
        ];
        // DRC_NBC_Shipping_Address__r will be null since it wasn't included in the query
        // and no lookup field was set on this plain Order object
        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: escapeXml with special characters in FG Code / Description
    //       Covers: escapeXml with non-blank values containing XML special chars
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_XmlSpecialCharactersEscaped() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [SELECT Id, Description FROM OrderItem WHERE OrderId = :ord.Id LIMIT 1];
        rawItems[0].Description = 'Product & <Special> "Chars"';
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }

    // =========================================================================
    // TEST: DRC_NBC_Unit_Of_Measurement__c = null → escapeXml returns ''
    //       Covers: escapeXml(String.isBlank(value)) → return '' branch
    // =========================================================================
    @isTest
    static void test_buildCreateMultiple_NullUOMCode_EscapedToEmpty() {
        Test.setMock(HttpCalloutMock.class, new SuccessMock());
        Order ord = getStandardOrder();

        List<OrderItem> rawItems = [
            SELECT Id, DRC_NBC_Unit_Of_Measurement__c FROM OrderItem WHERE OrderId = :ord.Id
        ];
        for (OrderItem oi : rawItems) {
            oi.DRC_NBC_Unit_Of_Measurement__c = null;
        }
        update rawItems;

        List<OrderItem> items = getOrderItems(ord.Id);

        Test.startTest();
        String result = DRC_NBC_LineItemCreator.createLineItemsAtLineNumber(
            ord.DRC_NBC_Cust_Order_Number__c, items, ord, 30000
        );
        Test.stopTest();
    }
}