force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_Order_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_Order_Endpoint__c</fullName>
    <label>BC Order Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Password__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Order_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Order_Namespace__c</fullName>
    <label>SOAP Order Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Username__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Cust_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Cust_Order_Number__c</fullName>
    <label>Customer Order Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Grand_Total__c</fullName>
    <formula>IF(
  TEXT(DRC_NBC_Type__c) = &quot;Domestic&quot;,
  /* --- Domestic Calculation --- */
  (
    IF(ISBLANK(TotalAmount), 0, TotalAmount) +
    IF(ISBLANK(DRC_NBC_C_GST__c), 0, DRC_NBC_C_GST__c) +
    IF(ISBLANK(DRC_NBC_S_GST__c), 0, DRC_NBC_S_GST__c) +
    IF(ISBLANK(DRC_NBC_I_GST__c), 0, DRC_NBC_I_GST__c) +
    IF(ISBLANK(DRC_NBC_Other_Tax_Amount__c), 0, DRC_NBC_Other_Tax_Amount__c) +
    IF(ISBLANK(DRC_NBC_TCS_Amount__c), 0, DRC_NBC_TCS_Amount__c)
  ),

  IF(
    TEXT(DRC_NBC_Type__c) = &quot;Export&quot;,
    /* --- Export Calculation --- */
    (
      IF(ISBLANK(TotalAmount), 0, TotalAmount) +
      IF(ISBLANK(DRC_NBC_Other_Tax_Amount__c), 0, DRC_NBC_Other_Tax_Amount__c) +
      IF(ISBLANK(DRC_NBC_Fright_Charges__c), 0, DRC_NBC_Fright_Charges__c) +
      IF(ISBLANK(DRC_NBC_Insurance__c), 0, DRC_NBC_Insurance__c)
    ),

    IF(
      TEXT(Type) = &quot;Sample Order&quot;,
      /* --- Paid Sample Order Calculation --- */
      (
        IF(ISBLANK(TotalAmount), 0, TotalAmount) +
        IF(ISBLANK(DRC_NBC_Sample_Shipping_Cost__c), 0, DRC_NBC_Sample_Shipping_Cost__c) +
        IF(ISBLANK(DRC_NBC_Sample_Amount__c), 0, DRC_NBC_Sample_Amount__c)
      ),
      /* --- Default Fallback --- */
      IF(ISBLANK(TotalAmount), 0, TotalAmount)
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Inco_Terms__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Inco_Terms__c</fullName>
    <label>Inco Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charges Collect (CC)</fullName>
            </value>
            <value>
                <fullName>Cost &amp; Freight (CFR)</fullName>
            </value>
            <value>
                <fullName>Cost Insurance &amp; Freight (CIF)</fullName>
            </value>
            <value>
                <fullName>Courier (COURIER)</fullName>
            </value>
            <value>
                <fullName>Carriage Paid To (CPT)</fullName>
            </value>
            <value>
                <fullName>Delivered At Place (DAP)</fullName>
            </value>
            <value>
                <fullName>Door Delivery (DD)</fullName>
            </value>
            <value>
                <fullName>Delivered Duty Paid (DDP)</fullName>
            </value>
            <value>
                <fullName>Ex Bhiwandi (EXBH)</fullName>
            </value>
            <value>
                <fullName>Ex Works (EXW)</fullName>
            </value>
            <value>
                <fullName>Free On Board (FOB)</fullName>
            </value>
            <value>
                <fullName>Freight Paid Delivered (FOR)</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <isActive>false</isActive>
                <label>CC</label>
            </value>
            <value>
                <fullName>CFR</fullName>
                <isActive>false</isActive>
                <label>CFR</label>
            </value>
            <value>
                <fullName>CIF</fullName>
                <isActive>false</isActive>
                <label>CIF</label>
            </value>
            <value>
                <fullName>COURIER</fullName>
                <isActive>false</isActive>
                <label>COURIER</label>
            </value>
            <value>
                <fullName>CPT</fullName>
                <isActive>false</isActive>
                <label>CPT</label>
            </value>
            <value>
                <fullName>DAP</fullName>
                <isActive>false</isActive>
                <label>DAP</label>
            </value>
            <value>
                <fullName>DD</fullName>
                <isActive>false</isActive>
                <label>DD</label>
            </value>
            <value>
                <fullName>DDP</fullName>
                <isActive>false</isActive>
                <label>DDP</label>
            </value>
            <value>
                <fullName>EXBH</fullName>
                <isActive>false</isActive>
                <label>EXBH</label>
            </value>
            <value>
                <fullName>EXW</fullName>
                <isActive>false</isActive>
                <label>EXW</label>
            </value>
            <value>
                <fullName>FOB</fullName>
                <isActive>false</isActive>
                <label>FOB</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <isActive>false</isActive>
                <label>FOR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Domestic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD (UNIT-III)</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Sample_Order.recordType-meta.xml
<RecordType>
    <fullName>Sample_Order</fullName>
    <active>true</active>
    <label>Sample Order</label>
</RecordType>

force-app/main/default/objects/Warehouse_Location_Code__mdt/Warehouse_Location_Code__mdt.object-meta.xml
<CustomObject>
    <label>Warehouse Location Code</label>
    <pluralLabel>Warehouse Location Code</pluralLabel>
</CustomObject>

force-app/main/default/objects/Warehouse_Location_Code__mdt/fields/DRC_NBC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Location_Code__mdt/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DRC_NBC_OrderReadUpdateQueueable.cls
public class DRC_NBC_OrderReadUpdateQueueable {

    // Custom setting (assumes Hierarchy/Custom Setting with getInstance())
    private static final DRC_NBC_BC_Integration__c bcSettings = DRC_NBC_BC_Integration__c.getInstance();
    private static final String BC_ORDER_ENDPOINT    = bcSettings.DRC_NBC_BC_Order_Endpoint__c;
    private static final String SOAP_ORDER_NAMESPACE = bcSettings.DRC_NBC_SOAP_Order_Namespace__c;
    private static final String BC_USERNAME          = bcSettings.DRC_NBC_Username__c;
    private static final String BC_PASSWORD          = bcSettings.DRC_NBC_Password__c;

    public static void execute(Id orderRecordId) {

        if (orderRecordId == null) {
            System.debug(LoggingLevel.ERROR, 'Order Id is null.');
            return;
        }

        // --- STEP 1: Query Order safely (avoid "List has no rows...")
        List<Order> ordList = [
            SELECT Id, DRC_NBC_Cust_Order_Number__c, EffectiveDate, PoNumber,
                   ShipToContactId, DRC_NBC_Warehouse__c, DRC_NBC_Inco_Terms__c,
                   DRC_NBC_Grand_Total__c, RecordType.Name, CurrencyIsoCode,
                   Account.Name, Account.DRC_NBC_Customer_Number__c, Status,
                   Account.BillingStreet, Account.BillingPostalCode, Account.BillingCity
            FROM Order
            WHERE Id = :orderRecordId
            LIMIT 1
        ];
        if (ordList.isEmpty()) {
            System.debug(LoggingLevel.ERROR, 'No Order found for Id: ' + orderRecordId);
            return;
        }
        Order ord = ordList[0];

        if (String.isBlank(ord.DRC_NBC_Cust_Order_Number__c)) {
            System.debug(LoggingLevel.ERROR, 'Order has blank DRC_NBC_Cust_Order_Number__c. Order Id: ' + ord.Id);
            return;
        }

        // Auth header
        String authHeader = 'Basic ' + EncodingUtil.base64Encode(
            Blob.valueOf(BC_USERNAME + ':' + BC_PASSWORD)
        );

        // --- STEP 2: Metadata lookups BEFORE callout
        String locationCode = resolveMdtCode(ord.DRC_NBC_Warehouse__c, 'Warehouse Location');
        String incoTerms    = resolveMdtCode(ord.DRC_NBC_Inco_Terms__c, 'Inco Terms');

        String  orderDateStr = (ord.EffectiveDate != null) ? String.valueOf(ord.EffectiveDate) : ''; // yyyy-MM-dd
        Decimal orderAmount  = (ord.DRC_NBC_Grand_Total__c != null) ? ord.DRC_NBC_Grand_Total__c : 0;
        Boolean isSample     = (ord.RecordType != null && ord.RecordType.Name == 'Sample_Order');

        System.debug('BC Order No  : ' + ord.DRC_NBC_Cust_Order_Number__c);
        System.debug('locationCode : ' + locationCode);
        System.debug('incoTerms    : ' + incoTerms);
        System.debug('orderAmount  : ' + orderAmount);

        // --- STEP 3: READ
        String readBody =
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
              '<soap:Body>' +
                '<Read xmlns="' + x(SOAP_ORDER_NAMESPACE) + '">' +
                  '<Document_Type>Order</Document_Type>' +
                  '<No>' + x(ord.DRC_NBC_Cust_Order_Number__c) + '</No>' +
                '</Read>' +
              '</soap:Body>' +
            '</soap:Envelope>';

        HttpResponse readRes = sendSoap('Read', readBody, authHeader);
        System.debug('READ HTTP: ' + readRes.getStatusCode());
        System.debug('READ BODY: ' + readRes.getBody());

        if (readRes.getStatusCode() != 200 || hasSoapFault(readRes.getBody())) {
            System.debug(LoggingLevel.ERROR, 'BC READ failed (or SOAP Fault). Not proceeding.');
            return;
        }

        // --- STEP 4: Parse READ response
        Map<String, String> bc = parseSalesOrderFields(readRes.getBody());
        System.debug('BC Status (READ): ' + bc.get('Status'));
        System.debug('BC Key           : ' + bc.get('Key'));

        if (String.isBlank(bc.get('Key')) || String.isBlank(bc.get('No'))) {
            System.debug(LoggingLevel.ERROR, 'READ did not return required fields (Key/No). Not proceeding.');
            return;
        }

        // Fill blanks from BC if Salesforce values missing
        if (String.isBlank(locationCode)) locationCode = (bc.get('Location_Code') != null) ? bc.get('Location_Code') : '';
        if (String.isBlank(incoTerms))    incoTerms    = (bc.get('Shipment_Method_Code') != null) ? bc.get('Shipment_Method_Code') : '';
        if (String.isBlank(orderDateStr)) orderDateStr = (bc.get('Order_Date') != null) ? bc.get('Order_Date') : '';

        // IMPORTANT:
        // Do NOT send Salesforce ContactId into BC Salesperson_Code (often Code[10] in BC).
        // Preserve BC value unless you have a proper mapping.
        String salespersonCode = (bc.get('Salesperson_Code') != null) ? bc.get('Salesperson_Code') : '';

        // --- STEP 5: UPDATE
        String updateBody =
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
              '<soap:Body>' +
                '<Update xmlns="' + x(SOAP_ORDER_NAMESPACE) + '">' +
                  '<SalesOrderSalesForce>' +

                    // Required keys
                    '<Key>'           + x(bc.get('Key'))           + '</Key>' +
                    '<Document_Type>' + x(bc.get('Document_Type')) + '</Document_Type>' +
                    '<No>'            + x(bc.get('No'))            + '</No>' +

                    // Sell-to
                    '<Sell_to_Customer_No>'   + x(bc.get('Sell_to_Customer_No'))   + '</Sell_to_Customer_No>' +
                    '<Sell_to_Customer_Name>' + x(bc.get('Sell_to_Customer_Name')) + '</Sell_to_Customer_Name>' +
                    '<Sell_to_Address>'       + x(bc.get('Sell_to_Address'))       + '</Sell_to_Address>' +
                    '<Sell_to_Address_2>'     + x(bc.get('Sell_to_Address_2'))     + '</Sell_to_Address_2>' +
                    '<Sell_to_Post_Code>'     + x(bc.get('Sell_to_Post_Code'))     + '</Sell_to_Post_Code>' +
                    '<Sell_to_City>'          + x(bc.get('Sell_to_City'))          + '</Sell_to_City>' +

                    // Order
                    '<Order_Date>'            + x(orderDateStr) + '</Order_Date>' +
                    '<External_Document_No>'  + x(ord.PoNumber) + '</External_Document_No>' +
                    '<Salesperson_Code>'      + x(salespersonCode) + '</Salesperson_Code>' +

                    // Status (BC may ignore if not editable; at least you’ll see it in response/readback)
                    '<Status>Released</Status>' +

                    // Codes
                    '<Location_Code>'         + x(locationCode) + '</Location_Code>' +
                    '<Payment_Terms_Code>'    + x(bc.get('Payment_Terms_Code')) + '</Payment_Terms_Code>' +
                    '<Shipment_Method_Code>'  + x(incoTerms) + '</Shipment_Method_Code>' +

                    // Custom flags
                    '<Sample_Sales>'          + String.valueOf(isSample) + '</Sample_Sales>' +
                    '<Salesforce_So_No>'      + x(String.valueOf(ord.Id)) + '</Salesforce_So_No>' +

                    // Ship-to
                    '<Ship_to_Code>'                + x(bc.get('Ship_to_Code'))                + '</Ship_to_Code>' +
                    '<Ship_to_Name>'                + x(bc.get('Ship_to_Name'))                + '</Ship_to_Name>' +
                    '<Ship_to_Name_2>'              + x(bc.get('Ship_to_Name_2'))              + '</Ship_to_Name_2>' +
                    '<Ship_to_Address>'             + x(bc.get('Ship_to_Address'))             + '</Ship_to_Address>' +
                    '<Ship_to_Address_2>'           + x(bc.get('Ship_to_Address_2'))           + '</Ship_to_Address_2>' +
                    '<Ship_to_Country_Region_Code>' + x(bc.get('Ship_to_Country_Region_Code')) + '</Ship_to_Country_Region_Code>' +
                    '<Ship_to_Post_Code>'           + x(bc.get('Ship_to_Post_Code'))           + '</Ship_to_Post_Code>' +
                    '<Ship_to_GST_Customer_Type>'   + x(bc.get('Ship_to_GST_Customer_Type'))   + '</Ship_to_GST_Customer_Type>' +
                    '<Ship_to_GST_Reg_No>'          + x(bc.get('Ship_to_GST_Reg_No'))          + '</Ship_to_GST_Reg_No>' +

                    // Amount/Currency
                    '<Salesforce_Order_Amount>'     + String.valueOf(orderAmount) + '</Salesforce_Order_Amount>' +
                    '<Salesforce_Order_Created>false</Salesforce_Order_Created>' +
                    '<Currency_Code>'               + x(bc.get('Currency_Code')) + '</Currency_Code>' +

                  '</SalesOrderSalesForce>' +
                '</Update>' +
              '</soap:Body>' +
            '</soap:Envelope>';

        HttpResponse updateRes = sendSoap('Update', updateBody, authHeader);
        System.debug('UPDATE HTTP: ' + updateRes.getStatusCode());
        System.debug('UPDATE BODY: ' + updateRes.getBody());

        Boolean bcUpdateOk = (updateRes.getStatusCode() == 200 && !hasSoapFault(updateRes.getBody()));
        if (!bcUpdateOk) {
            System.debug(LoggingLevel.ERROR, 'BC UPDATE failed (or SOAP Fault). Not updating Salesforce Order status.');
            return;
        }

        // Optional: parse UPDATE response to see what BC returned as Status
        Map<String, String> bcAfter = parseSalesOrderFields(updateRes.getBody());
        if (!bcAfter.isEmpty()) {
            System.debug('BC Status (UPDATE response): ' + bcAfter.get('Status'));
        }

        // --- STEP 6: Update Salesforce Order status ONLY after BC success
        try {
            update new Order(
                Id = ord.Id,
                Status = 'Released'
            );
            System.debug('Salesforce Order updated to Status=Released. Order Id: ' + ord.Id);
        } catch (DmlException e) {
            System.debug(LoggingLevel.ERROR, 'Salesforce status update failed: ' + e.getDmlMessage(0));
        }
    }

    // ========== Helpers ==========

    private static HttpResponse sendSoap(String action, String body, String authHeader) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(BC_ORDER_ENDPOINT);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'text/xml; charset=utf-8');

        // Many SOAP tools send SOAPAction in quotes; BC endpoints often like that too.
        req.setHeader('SOAPAction', '"' + SOAP_ORDER_NAMESPACE + ':' + action + '"');

        req.setHeader('Authorization', authHeader);
        req.setTimeout(120000);
        req.setBody(body);
        return new Http().send(req);
    }

    private static Boolean hasSoapFault(String body) {
        if (String.isBlank(body)) return false;
        return body.contains('<soap:Fault') || body.contains(':Fault') || body.contains('<Fault');
    }

    // Escapes XML special characters to prevent broken XML when values contain &, <, >, etc.
    private static String x(String v) {
        if (v == null) return '';
        return v.replace('&','&amp;')
                .replace('<','&lt;')
                .replace('>','&gt;')
                .replace('"','&quot;')
                .replace('\'','&apos;');
    }

    private static String resolveMdtCode(String label, String type) {
        if (String.isBlank(label)) return '';
        List<Warehouse_Location_Code__mdt> rows = [
            SELECT DRC_NBC_Code__c
            FROM Warehouse_Location_Code__mdt
            WHERE MasterLabel = :label
              AND DRC_NBC_Type__c = :type
            LIMIT 1
        ];
        return rows.isEmpty() ? '' : rows[0].DRC_NBC_Code__c;
    }

    // Finds the first node whose name contains a token (case-insensitive)
    private static Dom.XmlNode findNodeContains(Dom.XmlNode node, String tokenLower) {
        if (node == null) return null;
        String n = node.getName();
        if (n != null && n.toLowerCase().contains(tokenLower)) return node;

        for (Dom.XmlNode c : node.getChildElements()) {
            Dom.XmlNode found = findNodeContains(c, tokenLower);
            if (found != null) return found;
        }
        return null;
    }

    // Parses any SOAP response body that contains a SalesOrderSalesForce node
    private static Map<String, String> parseSalesOrderFields(String soapBody) {
        Map<String, String> out = new Map<String, String>();
        if (String.isBlank(soapBody)) return out;

        try {
            Dom.Document doc = new Dom.Document();
            doc.load(soapBody);

            Dom.XmlNode root = doc.getRootElement();
            Dom.XmlNode soNode = findNodeContains(root, 'salesordersalesforce');
            if (soNode == null) return out;

            for (Dom.XmlNode f : soNode.getChildElements()) {
                out.put(f.getName(), f.getText());
            }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'XML parse failed: ' + e.getMessage());
        }
        return out;
    }
}