force-app/main/default/objects/Account/fields/DRC_NBC_Account_Email_Email__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Email_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Credit_Limit__c</fullName>
    <label>Credit Limit</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_GST_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_GST_Number__c</fullName>
    <label>Billing GST Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_PAN_No__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Payment_Term_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Payment_Term_Code__c</fullName>
    <label>Payment Term Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DRC_NBC_Payment_Terms_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PDC90</fullName>
            </value>
            <value>
                <fullName>PDC60</fullName>
            </value>
            <value>
                <fullName>PDC45</fullName>
            </value>
            <value>
                <fullName>PDC30</fullName>
            </value>
            <value>
                <fullName>IRRELC</fullName>
            </value>
            <value>
                <fullName>IRRLC90</fullName>
            </value>
            <value>
                <fullName>IRRLC60</fullName>
            </value>
            <value>
                <fullName>IRRLC45</fullName>
            </value>
            <value>
                <fullName>IRRLC30</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
            <value>
                <fullName>DPSIGHT</fullName>
            </value>
            <value>
                <fullName>DP90</fullName>
            </value>
            <value>
                <fullName>DP60</fullName>
            </value>
            <value>
                <fullName>DP30</fullName>
            </value>
            <value>
                <fullName>DA90</fullName>
            </value>
            <value>
                <fullName>DA60</fullName>
            </value>
            <value>
                <fullName>DA45</fullName>
            </value>
            <value>
                <fullName>DA30</fullName>
            </value>
            <value>
                <fullName>BONTRN</fullName>
            </value>
            <value>
                <fullName>BL90</fullName>
            </value>
            <value>
                <fullName>BL75</fullName>
            </value>
            <value>
                <fullName>BL60</fullName>
            </value>
            <value>
                <fullName>BL45</fullName>
            </value>
            <value>
                <fullName>BL30</fullName>
            </value>
            <value>
                <fullName>BL120</fullName>
            </value>
            <value>
                <fullName>INV90</fullName>
            </value>
            <value>
                <fullName>INV75</fullName>
            </value>
            <value>
                <fullName>70ADV-30CD</fullName>
            </value>
            <value>
                <fullName>INV07</fullName>
            </value>
            <value>
                <fullName>LR60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Value__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Value__c</fullName>
    <label>Value (Crores)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/DRC_NBC_Volume__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Volume__c</fullName>
    <label>Volume (Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesPerson_Code__c.field-meta.xml
<CustomField>
    <fullName>SalesPerson_Code__c</fullName>
    <label>SalesPerson Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ajit Phadke</fullName>
            </value>
            <value>
                <fullName>Ajit Vasudevan</fullName>
            </value>
            <value>
                <fullName>Amit Drolia</fullName>
            </value>
            <value>
                <fullName>Bhavesh Tambe</fullName>
            </value>
            <value>
                <fullName>Jigna Shah</fullName>
            </value>
            <value>
                <fullName>Kirit Acharya</fullName>
            </value>
            <value>
                <fullName>Manali Maniyar</fullName>
            </value>
            <value>
                <fullName>Nirmal Mansukhani</fullName>
            </value>
            <value>
                <fullName>Shirley D&apos;silva</fullName>
            </value>
            <value>
                <fullName>Shekhar Rege</fullName>
            </value>
            <value>
                <fullName>Tanay Drolia</fullName>
            </value>
            <value>
                <fullName>Vijay Gurnani</fullName>
            </value>
            <value>
                <fullName>Yash Drolia</fullName>
            </value>
            <value>
                <fullName>AKSHTA SAWANT</fullName>
            </value>
            <value>
                <fullName>AJITPH</fullName>
                <isActive>false</isActive>
                <label>AJITPH</label>
            </value>
            <value>
                <fullName>AJITVA</fullName>
                <isActive>false</isActive>
                <label>AJITVA</label>
            </value>
            <value>
                <fullName>AMITDR</fullName>
                <isActive>false</isActive>
                <label>AMITDR</label>
            </value>
            <value>
                <fullName>Akhta Sawant</fullName>
                <isActive>false</isActive>
                <label>Akhta Sawant</label>
            </value>
            <value>
                <fullName>BHAVTA</fullName>
                <isActive>false</isActive>
                <label>BHAVTA</label>
            </value>
            <value>
                <fullName>JIGNA</fullName>
                <isActive>false</isActive>
                <label>JIGNA</label>
            </value>
            <value>
                <fullName>KIRTIA</fullName>
                <isActive>false</isActive>
                <label>KIRTIA</label>
            </value>
            <value>
                <fullName>MANMA</fullName>
                <isActive>false</isActive>
                <label>MANMA</label>
            </value>
            <value>
                <fullName>NIRMAL</fullName>
                <isActive>false</isActive>
                <label>NIRMAL</label>
            </value>
            <value>
                <fullName>SHIRLEY</fullName>
                <isActive>false</isActive>
                <label>SHIRLEY</label>
            </value>
            <value>
                <fullName>SHREGE</fullName>
                <isActive>false</isActive>
                <label>SHREGE</label>
            </value>
            <value>
                <fullName>TANYDR</fullName>
                <isActive>false</isActive>
                <label>TANYDR</label>
            </value>
            <value>
                <fullName>VIJYGU</fullName>
                <isActive>false</isActive>
                <label>VIJYGU</label>
            </value>
            <value>
                <fullName>YASHDR</fullName>
                <isActive>false</isActive>
                <label>YASHDR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Account_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account_Approval_Status__c</fullName>
    <label>Account Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Account_Number__c</fullName>
    <label>Consignee Bank Account Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Address__c</fullName>
    <label>Consignee Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_IFSC_Code__c</fullName>
    <label>Consignee Bank IFSC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Consignee_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Consignee_Bank_Name__c</fullName>
    <label>Consignee Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesPerson_Code__mdt/SalesPerson_Code__mdt.object-meta.xml
<CustomObject>
    <label>SalesPerson Code</label>
    <pluralLabel>SalesPerson Code</pluralLabel>
</CustomObject>

force-app/main/default/classes/DRC_NBC_SalesPersonCode_Callout_Test.cls
/**
 * @File Name : DRC_NBC_SalesPersonCode_Callout_Test.cls
 * @Description : Test class for DRC_NBC_SalesPersonCode_Callout and DRC_NBC_SalesPerson_BC_Integration
 * @Author : Satish
 * @Last Modified On : May 25, 2026
**/
@isTest(SeeAllData=true)
private class DRC_NBC_SalesPersonCode_Callout_Test {

    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private Integer statusCode;
        private String responseBody;

        public MockHttpResponseGenerator(Integer statusCode, String responseBody) {
            this.statusCode = statusCode;
            this.responseBody = responseBody;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(responseBody);
            res.setStatusCode(statusCode);
            return res;
        }
    }

    // ─── Helper: fetch a real MDT record's Name__c (SeeAllData=true allows this) ───
    private static String getValidSalesPersonCode() {
        List<SalesPerson_Code__mdt> mdtList = [
            SELECT Name__c
            FROM SalesPerson_Code__mdt
            LIMIT 1
        ];
        return mdtList.isEmpty() ? null : mdtList[0].Name__c;
    }

    // ─── Create Account WITH SalesPerson_Code__c ───
    private static Account createTestAccount(String salesPersonCode) {
        Account acc = new Account(
            Name                                     = 'Test Account',
            DRC_NBC_Customer_Number__c               = 'CUST12345',
            CurrencyIsoCode                          = 'INR',
            Phone                                    = '1234567890',
            AccountNumber                            = 'A123',
            DRC_NBC_PAN_No__c                        = 'AWVPY9594J',
            DRC_NBC_GST_Number__c                    = '27AWVPY9594J1ZY',
            DRC_NBC_Payment_Term_Code__c             = 'PDC90',
            DRC_NBC_Account_Email_Email__c           = 'test@example.com',
            BillingStreet                            = '123 Street',
            BillingCity                              = 'City',
            BillingCountry                           = 'India',
            BillingCountryCode                       = 'IN',
            BillingPostalCode                        = '462002',
            BillingState                             = 'Maharashtra',
            BillingStateCode                         = 'MH',
            DRC_NBC_Volume__c                        = 70,
            DRC_NBC_Credit_Limit__c                  = 123456787,
            DRC_NBC_Value__c                         = 900,
            DRC_NBC_Consignee_Bank_Account_Number__c = '1391001500974141',
            DRC_NBC_Consignee_Bank_Address__c        = 'Barhi 483775',
            DRC_NBC_Consignee_Bank_IFSC_Code__c      = 'PUNB01391000',
            DRC_NBC_Consignee_Bank_Name__c           = 'Punjab National bank',
            Industry                                 = 'Chemicals Construction',
            Type                                     = 'Analyst',
            SalesPerson_Code__c                      = 'Ajit Vasudevan'
        );
        insert acc;
        return acc;
    }

    // ─── Create Order ───
    private static Order createTestOrder(Id accountId) {
        Order ord = new Order(
            Name                               = 'Test Order',
            AccountId                          = accountId,
            Status                             = 'Draft',
            EffectiveDate                      = Date.today(),
            DRC_NBC_Account_Approval_Status__c = 'Pending'
        );
        insert ord;
        return ord;
    }

    // ─── Helper: build a dummy payload for Integration tests ───
    private static String buildDummyPayload() {
        Map<String, Object> payloadMap = new Map<String, Object>{
            'Name'     => 'Test SalesPerson',
            'Phone_No' => '9876543210',
            'E_Mail'   => 'sp@example.com',
            'Code'     => 'SP001'
        };
        return JSON.serialize(payloadMap);
    }

    // ═══════════════════════════════════════════════════════════════
    //  QUEUEABLE TESTS
    // ═══════════════════════════════════════════════════════════════

    @isTest
    static void test_Queueable_SuccessfulCallout() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"message": "Success"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_Queueable_FailedCallout() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, '{"error": "Server Error"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_Queueable_BadRequestCallout() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(400, '{"error": "Bad Request"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    // ═══════════════════════════════════════════════════════════════
    //  SUCCESS PATHS
    // ═══════════════════════════════════════════════════════════════

    @isTest
    static void test_ExecuteCallout_Success200() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, '{"message": "Success"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_Success201() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"message": "Created"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_Success204() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(204, ''));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    // ═══════════════════════════════════════════════════════════════
    //  FAILURE / HTTP ERROR PATHS
    // ═══════════════════════════════════════════════════════════════

    @isTest
    static void test_ExecuteCallout_HttpFailure500() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, '{"error": "Server error"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_BadRequest400() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(400, '{"error": "Bad Request"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_NotFound404() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(404, '{"error": "Not Found"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_Unauthorized401() {
        String spCode = getValidSalesPersonCode();
        Account acc   = createTestAccount(spCode);
        Order ord     = createTestOrder(acc.Id);

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(401, '{"error": "Unauthorized"}'));

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    // ═══════════════════════════════════════════════════════════════
    //  EDGE / NEGATIVE PATHS
    // ═══════════════════════════════════════════════════════════════

    // Account has NO SalesPerson_Code__c → skips callout, chains to Account sync
    @isTest
    static void test_ExecuteCallout_NoSalesPersonCode() {
        Account acc = createTestAccount(null);
        Order ord   = createTestOrder(acc.Id);

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    // SalesPerson_Code__c has a value that does NOT match any MDT record
    @isTest
    static void test_ExecuteCallout_NoMatchingMetadata() {
        Account acc = createTestAccount('NIRMAL_INVALID_CODE');
        Order ord   = createTestOrder(acc.Id);

        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(ord.Id));
        Test.stopTest();
    }

    // Invalid Order Id → triggers catch block in execute()
    @isTest
    static void test_ExecuteCallout_NoAccountOnOrder() {
        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout('801000000000000AAA'));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_InvalidOrderId() {
        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout('801000000000000AAA'));
        Test.stopTest();
    }

    @isTest
    static void test_ExecuteCallout_NullOrderId() {
        Test.startTest();
        System.enqueueJob(new DRC_NBC_SalesPersonCode_Callout(null));
        Test.stopTest();
    }

    // ═══════════════════════════════════════════════════════════════
    //  INTEGRATION CLASS TESTS
    // ═══════════════════════════════════════════════════════════════

    @isTest
    static void test_Integration_PrepareRequest() {
        Account acc     = createTestAccount(null);
        String payload  = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint',
            'POST',
            payload,
            acc.Id
        );

        Test.startTest();
        HttpRequest req = integration.prepareRequest();
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ProcessResponse_Success200() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        HttpResponse successResp = new HttpResponse();
        successResp.setStatusCode(200);
        successResp.setBody('{"message":"Success"}');

        Test.startTest();
        integration.processResponse(successResp);
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ProcessResponse_Success201() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        HttpResponse successResp = new HttpResponse();
        successResp.setStatusCode(201);
        successResp.setBody('{"message":"Created"}');

        Test.startTest();
        integration.processResponse(successResp);
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ProcessResponse_Error500() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        HttpResponse errorResp = new HttpResponse();
        errorResp.setStatusCode(500);
        errorResp.setBody('{"error":"Internal Server Error"}');

        Test.startTest();
        integration.processResponse(errorResp);
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ProcessResponse_Error400() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        HttpResponse errorResp = new HttpResponse();
        errorResp.setStatusCode(400);
        errorResp.setBody('{"error":"Bad Request"}');

        Test.startTest();
        integration.processResponse(errorResp);
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ProcessResponse_Error404() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        HttpResponse errorResp = new HttpResponse();
        errorResp.setStatusCode(404);
        errorResp.setBody('{"error":"Not Found"}');

        Test.startTest();
        integration.processResponse(errorResp);
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ExecuteAndReturnResponse() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201, '{"message": "Success"}'));

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        Test.startTest();
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
    }

    @isTest
    static void test_Integration_ExecuteAndReturnResponse_Failure() {
        Account acc    = createTestAccount(null);
        String payload = buildDummyPayload();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(500, '{"error": "Server Error"}'));

        DRC_NBC_SalesPerson_BC_Integration integration = new DRC_NBC_SalesPerson_BC_Integration(
            'test-endpoint', 'POST', payload, acc.Id
        );

        Test.startTest();
        HttpResponse response = integration.executeAndReturnResponse();
        Test.stopTest();
    }

    @isTest
    static void test_PayloadStructure() {
        Test.startTest();
        String payload = buildDummyPayload();
        Map<String, Object> deserialized = (Map<String, Object>) JSON.deserializeUntyped(payload);
        Test.stopTest();
    }
}