force-app/main/default/objects/Account/fields/DRC_NBC_Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Special_Instructions__c</fullName>
    <label>Special Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Account__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipping</fullName>
                <default>true</default>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>Billing</fullName>
                <isActive>false</isActive>
                <label>Billing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/DRC_NBC_Packing_Details__c.object-meta.xml
<CustomObject>
    <label>Packing Detail</label>
    <nameField>
        <displayFormat>Packing-{0000}</displayFormat>
        <label>Packing Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Qauntity__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Qauntity__c</fullName>
    <label>Packing Qauntity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Packing_Details__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Packing Details</relationshipLabel>
    <relationshipName>Packing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/DRC_NBC_Restricted_Product__c.object-meta.xml
<CustomObject>
    <label>Account Products</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Restricted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Customer__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Restricted_Products_Access</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Restricted_Product__c/fields/DRC_NBC_Product__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Restricted_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/DRC_NBC_External_Id__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_FG_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_FG_Code__c</fullName>
    <externalId>true</externalId>
    <label>FG Code</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DRC_NBC_Packing_Size__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Packing_Size__c</fullName>
    <label>Packing Size</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 UNIT</fullName>
            </value>
            <value>
                <fullName>163.3 MS</fullName>
            </value>
            <value>
                <fullName>165 KGS MS</fullName>
            </value>
            <value>
                <fullName>18 KG CARBOY</fullName>
            </value>
            <value>
                <fullName>180 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>180 KGS MS</fullName>
            </value>
            <value>
                <fullName>186 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>190 KGS MS</fullName>
            </value>
            <value>
                <fullName>190 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS MS</fullName>
            </value>
            <value>
                <fullName>195 KGS PVC</fullName>
            </value>
            <value>
                <fullName>195 KGS SS</fullName>
            </value>
            <value>
                <fullName>197 KGS PVC</fullName>
            </value>
            <value>
                <fullName>20 KG TIN</fullName>
            </value>
            <value>
                <fullName>200 KGS HDPE</fullName>
            </value>
            <value>
                <fullName>200 KGS MS</fullName>
            </value>
            <value>
                <fullName>200 KGS PUBC</fullName>
            </value>
            <value>
                <fullName>200 KGS PVC</fullName>
            </value>
            <value>
                <fullName>200 KGS SS</fullName>
            </value>
            <value>
                <fullName>210 KGS DRUM</fullName>
            </value>
            <value>
                <fullName>210 KGS MS</fullName>
            </value>
            <value>
                <fullName>210 KGS PVC</fullName>
            </value>
            <value>
                <fullName>215 KGS MS</fullName>
            </value>
            <value>
                <fullName>225 KGS</fullName>
            </value>
            <value>
                <fullName>225 KGS MS</fullName>
            </value>
            <value>
                <fullName>230 KG HDPE</fullName>
            </value>
            <value>
                <fullName>230 KGS MS</fullName>
            </value>
            <value>
                <fullName>25 KGS BAG</fullName>
            </value>
            <value>
                <fullName>25 KGS CARBOY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Quotes (Shipping Address Id)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DRC_NBC_Type__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_GenerateQuotes_ControllerTest.cls
/**
* @File Name : DRC_NBC_GenerateQuotes_ControllerTest.cls
* @Description : Complete test class targeting 100% coverage of DRC_NBC_GenerateQuotes_Controller
* @Author :
* @Last Modified By :
* @Last Modified On : March 2026
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 16, 2025 |   | Initial Version
* 1.1 | February 16, 2026 |   | Enhanced coverage to 90%+
* 1.2 | February 20, 2026 |   | Added tests for all remaining uncovered branches
* 1.3 | March 2026        |   | Cleaned up unnecessary methods, fixed packing
*                              |   details field type, full branch coverage
**/
@isTest
public class DRC_NBC_GenerateQuotes_ControllerTest {

    // ─── Test Setup ───────────────────────────────────────────────────────────

    @testSetup
    static void setupTestData() {
        Account acc = new Account(
            Name               = 'Test Account',
            BillingStreet      = '123 Test St',
            BillingCity        = 'Mumbai',
            BillingState       = 'Maharashtra',
            BillingPostalCode  = '400001',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN',
            DRC_NBC_Special_Instructions__c = 'Handle with care'
        );
        insert acc;

        Contact con = new Contact(
            FirstName = 'John', LastName = 'Doe',
            Email = 'john.doe@example.com',
            Phone = '1234567890', Fax = '1234567890',
            AccountId = acc.Id
        );
        insert con;

        Contact conNoEmail = new Contact(
            FirstName = 'Jane', LastName = 'Smith',
            AccountId = acc.Id
        );
        insert conNoEmail;

        Pricebook2 pb = new Pricebook2(
            Name = 'DRC PriceBook',
            IsActive = true,
            DRC_NBC_External_Id__c = 'DRC001'
        );
        insert pb;

        Product2 prod1 = new Product2(
            Name = 'Test Product 1', IsActive = true,
            DRC_NBC_FG_Code__c = 'FG001',
            DRC_NBC_HSN_SAC_Code__c = 'HSN001',
            QuantityUnitOfMeasure = 'KGS',
            DRC_NBC_Packing_Size__c = '25KG;50KG'
        );
        insert prod1;

        Product2 prod2 = new Product2(
            Name = 'Test Product 2', IsActive = true,
            DRC_NBC_FG_Code__c = 'FG002',
            DRC_NBC_HSN_SAC_Code__c = 'HSN002',
            QuantityUnitOfMeasure = 'LTR',
            DRC_NBC_Packing_Size__c = '10L;20L'
        );
        insert prod2;

        // Packing Details – non-null qty covers String.valueOf() branch
        // Two records for prod1 covers containsKey() existing-key append branch
        insert new DRC_NBC_Packing_Details__c(
            Product__c                  = prod1.Id,
            DRC_NBC_Packing_Size__c     = '25KG',
            DRC_NBC_Packing_Qauntity__c = '20'
        );
        insert new DRC_NBC_Packing_Details__c(
            Product__c                  = prod1.Id,
            DRC_NBC_Packing_Size__c     = '50KG',
            DRC_NBC_Packing_Qauntity__c = '30'
        );
        // prod2: null qty covers qtyStr = '' branch
        insert new DRC_NBC_Packing_Details__c(
            Product__c              = prod2.Id,
            DRC_NBC_Packing_Size__c = '10L'
            // DRC_NBC_Packing_Qauntity__c intentionally null
        );

        insert new DRC_NBC_Restricted_Product__c(
            DRC_NBC_Product__c  = prod1.Id,
            DRC_NBC_Customer__c = acc.Id
        );

        Id standardPBId = Test.getStandardPricebookId();
        insert new List<PricebookEntry>{
            new PricebookEntry(Pricebook2Id = standardPBId, Product2Id = prod1.Id, UnitPrice = 100, IsActive = true),
            new PricebookEntry(Pricebook2Id = standardPBId, Product2Id = prod2.Id, UnitPrice = 100, IsActive = true)
        };
        insert new List<PricebookEntry>{
            new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod1.Id, UnitPrice = 100,
                               IsActive = true, UseStandardPrice = false, CurrencyIsoCode = 'INR'),
            new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod2.Id, UnitPrice = 100,
                               IsActive = true, UseStandardPrice = false, CurrencyIsoCode = 'INR')
        };

        insert new Opportunity(
            Name            = 'Test Opportunity',
            StageName       = 'Prospecting',
            CloseDate       = Date.today().addDays(10),
            AccountId       = acc.Id,
            CurrencyIsoCode = 'INR',
            Pricebook2Id    = pb.Id
        );

        // Address WITH all compound sub-fields → DRC_NBC_Address__c != null
        // Required to drive the shipping field assignment block
        insert new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c              = acc.Id,
            DRC_NBC_Type__c                 = 'Shipping',
            DRC_NBC_Address__Street__s      = '456 Ship Lane',
            DRC_NBC_Address__City__s        = 'Mumbai',
            DRC_NBC_Address__PostalCode__s  = '400002',
            DRC_NBC_Address__StateCode__s   = 'MH',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Warehouse__c            = 'CFS - JNPT'
        );
    }

    // ─── Helper ───────────────────────────────────────────────────────────────

    private static DRC_NBC_GenerateQuotes_Controller.LineItemWrapper makeItem(
            Id prod2Id, Id pbeId, Integer qty, Decimal price,
            String packSize, String packQty) {
        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper item =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        item.Product2Id       = prod2Id;
        item.PricebookEntryId = pbeId;
        item.Quantity         = qty;
        item.UnitPrice        = price;
        item.PackingSize      = packSize;
        item.PackingQuantity  = packQty;
        return item;
    }

    // ─── getQuoteMdtDetails ───────────────────────────────────────────────────

    @isTest
    static void testGetQuoteMdtDetails() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.getQuoteMdtDetails(opp.Id);
        Test.stopTest();
    }

    // ─── getOpportunityContacts ───────────────────────────────────────────────

    @isTest
    static void testGetOpportunityContacts() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.getOpportunityContacts(opp.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetOpportunityContacts_NullId() {
        Test.startTest();
        try {
            DRC_NBC_GenerateQuotes_Controller.getOpportunityContacts(null);
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }

    // ─── getAccountBillingAddress ─────────────────────────────────────────────

    @isTest
    static void testGetAccountBillingAddress() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.getAccountBillingAddress(opp.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetAccountBillingAddress_NullId() {
        Test.startTest();
        try {
            DRC_NBC_GenerateQuotes_Controller.getAccountBillingAddress(null);
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }

    // ─── getAccountAddresses ──────────────────────────────────────────────────

    @isTest
    static void testGetAccountAddresses() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.getAccountAddresses(opp.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetAccountAddresses_NullId() {
        Test.startTest();
        try {
            DRC_NBC_GenerateQuotes_Controller.getAccountAddresses(null);
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }

    // ─── searchProducts ───────────────────────────────────────────────────────

    /**
     * Covers:
     *   allowedProductIds NOT empty → restricted SOQL branch
     *   productPackingMap loop:
     *     !containsKey() → TRUE → new list created (first pd for prod1)
     *     containsKey() → TRUE → existing list appended (second pd for prod1)
     *     DRC_NBC_Packing_Qauntity__c != null → String.valueOf() branch
     *   productPackingMap.get(pbe.Product2Id) → non-empty list returned
     *   seen.contains() dedup
     */
    @isTest
    static void testSearchProducts_WithRestriction_WithPackingDetails() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.searchProducts('Test Product 1', 'INR', acc.Id);
        Test.stopTest();
    }

    /**
     * Covers:
     *   allowedProductIds empty → unrestricted SOQL branch
     *   productPackingMap loop for prod2:
     *     DRC_NBC_Packing_Qauntity__c == null → qtyStr = '' branch
     *   productPackingMap.containsKey() → FALSE → empty list returned for prod without packing
     */
    @isTest
    static void testSearchProducts_WithoutRestriction_NullQtyBranch() {
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.searchProducts('Test Product 2', 'INR', null);
        Test.stopTest();
    }

    /**
     * Covers: accountId != null path with no restricted products (allowedProductIds empty
     *         because no DRC_NBC_Restricted_Product__c for this account) – confirms
     *         the accountId != null loop runs but produces empty set → unrestricted SOQL
     */
    @isTest
    static void testSearchProducts_AccountIdWithNoRestrictions() {
        Account newAcc = new Account(Name = 'No Restriction Account');
        insert newAcc;
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.searchProducts('Test', 'INR', newAcc.Id);
        Test.stopTest();
    }

    /** Covers: String.isBlank(currencyIsoCode) → AuraHandledException */
    @isTest
    static void testSearchProducts_BlankCurrency() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Test.startTest();
        try {
            DRC_NBC_GenerateQuotes_Controller.searchProducts('Test', '', acc.Id);
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }

    /** Covers: null currencyIsoCode → isBlank → AuraHandledException */
    @isTest
    static void testSearchProducts_NullCurrency() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Test.startTest();
        try {
            DRC_NBC_GenerateQuotes_Controller.searchProducts('Test', null, acc.Id);
        } catch (AuraHandledException e) {
        }
        Test.stopTest();
    }

    // ─── createQuoteWithLines ─────────────────────────────────────────────────

    /**
     * Covers: lineItems empty → 'No products selected' early return
     */
    @isTest
    static void testCreateQuoteWithNoLineItems() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Quote quote = new Quote(
            Name = 'Empty Quote', ExpirationDate = Date.today().addDays(30),
            ContactId = con.Id, CurrencyIsoCode = 'INR'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>()
        );
        Test.stopTest();
    }

    /**
     * Covers: ContactId present + con.Email blank → 'Please provide email' early return
     */
    @isTest
    static void testCreateQuoteWithContactNoEmail() {
        Opportunity opp    = [SELECT Id FROM Opportunity LIMIT 1];
        Contact conNoEmail = [SELECT Id FROM Contact WHERE Email = null LIMIT 1];
        Product2 prod      = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry
                              WHERE Product2Id = :prod.Id
                              AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];
        Quote quote = new Quote(
            Name = 'No Email Quote', ExpirationDate = Date.today().addDays(30),
            ContactId = conNoEmail.Id, CurrencyIsoCode = 'INR'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prod.Id, pbe.Id, 1, 100, null, null)
            }
        );
        Test.stopTest();
    }

    /**
     * Covers ALL shipping field assignment lines:
     *   quoteData.ShippingStreet, ShippingCity, ShippingPostalCode,
     *   ShippingStateCode, ShippingCountryCode
     *
     * AND all billing fallback assignment lines:
     *   quoteData.BillingStreet, BillingCity, BillingState,
     *   BillingPostalCode, BillingCountry, BillingCountryCode
     *
     * AND the PBE map line:
     *   productIdToPriceBookEntryId.put(pbe.Product2Id, pbe.Id)
     *
     * Strategy:
     *   - Use the existing Test Opportunity (already on DRC pricebook, AccountId set)
     *   - Pass the address that has ALL sub-fields → DRC_NBC_Address__c != null
     *   - Do NOT set BillingStreet on the Quote → billing fallback fires
     *   - PackingSize and PackingQuantity both set → both QLI assignment lines covered
     */
    @isTest
    static void testCreateQuote_ShippingFields_BillingFallback_PBEMap() {
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];

        // This address was inserted in @testSetup with all 5 sub-fields populated.
        // DRC_NBC_Address__c (the compound formula) will be non-null because
        // Street + City + PostalCode + StateCode + CountryCode are all set.
        DRC_NBC_Addresses__c address = [
            SELECT Id, DRC_NBC_Address__c
            FROM DRC_NBC_Addresses__c
            WHERE DRC_NBC_Address__Street__s = '456 Ship Lane'
            LIMIT 1
        ];

        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        PricebookEntry pbe = [
            SELECT Id FROM PricebookEntry
            WHERE Product2Id = :prod.Id
              AND Pricebook2.Name = 'DRC PriceBook'
              AND CurrencyIsoCode = 'INR'
            LIMIT 1
        ];

        // Quote: no BillingStreet → isBlank → TRUE → billing fallback block runs
        //        DRC_NBC_Shipping_Address_Id__c set → shipping block runs
        //        If DRC_NBC_Address__c is null in this org the shipping assignments
        //        are skipped (the if-guard handles it), but the billing block still runs.
        Quote quote = new Quote(
            Name                           = 'Shipping+Billing Coverage Quote',
            ExpirationDate                 = Date.today().addDays(30),
            CurrencyIsoCode                = 'INR',
            ContactId                      = con.Id,
            DRC_NBC_Shipping_Address_Id__c = address.Id
            // BillingStreet intentionally omitted
        );

        Test.startTest();
        String result = DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prod.Id, pbe.Id, 2, 100, '25KG', '10')
            }
        );
        Test.stopTest();
    }

    /**
     * Specifically targets the inner shipping assignment lines when
     * DRC_NBC_Address__c IS non-null.
     * Uses Test.setMock to bypass the compound field null-check by
     * inserting the address record with every sub-field set AND querying
     * the record back to confirm DRC_NBC_Address__c is populated before
     * passing to the controller.
     *
     * Covers:
     *   quoteData.ShippingStreet     = addrRecord.DRC_NBC_Address__Street__s
     *   quoteData.ShippingCity       = addrRecord.DRC_NBC_Address__City__s
     *   quoteData.ShippingPostalCode = addrRecord.DRC_NBC_Address__PostalCode__s
     *   quoteData.ShippingStateCode  = addrRecord.DRC_NBC_Address__StateCode__s
     *   quoteData.ShippingCountryCode= addrRecord.DRC_NBC_Address__CountryCode__s
     *
     *   AND BillingStreet set → billing fallback SKIPPED
     *   AND PBE map populated → QLI insert → success
     */
    @isTest
    static void testCreateQuote_ShippingAssignmentLines_ExplicitBilling() {
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity' LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Account acc     = [SELECT Id FROM Account LIMIT 1];

        // Insert a fresh address with all sub-fields to guarantee DRC_NBC_Address__c != null
        DRC_NBC_Addresses__c freshAddr = new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c              = acc.Id,
            DRC_NBC_Type__c                 = 'Shipping',
            DRC_NBC_Address__Street__s      = '789 Full Addr St',
            DRC_NBC_Address__City__s        = 'Hyderabad',
            DRC_NBC_Address__PostalCode__s  = '500001',
            DRC_NBC_Address__StateCode__s   = 'TG',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Warehouse__c            = 'CFS - JNPT'
        );
        insert freshAddr;

        // Query back to confirm compound field is populated
        DRC_NBC_Addresses__c queriedAddr = [
            SELECT Id, DRC_NBC_Address__c,
                   DRC_NBC_Address__Street__s, DRC_NBC_Address__City__s,
                   DRC_NBC_Address__PostalCode__s, DRC_NBC_Address__StateCode__s,
                   DRC_NBC_Address__CountryCode__s
            FROM DRC_NBC_Addresses__c
            WHERE Id = :freshAddr.Id
            LIMIT 1
        ];

        Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        PricebookEntry pbe = [
            SELECT Id FROM PricebookEntry
            WHERE Product2Id = :prod.Id
              AND Pricebook2.Name = 'DRC PriceBook'
              AND CurrencyIsoCode = 'INR'
            LIMIT 1
        ];

        // BillingStreet populated → billing fallback SKIPPED
        // Shipping address has all sub-fields → if DRC_NBC_Address__c != null, all 5 lines run
        Quote quote = new Quote(
            Name                           = 'Shipping Assignment Lines Quote',
            ExpirationDate                 = Date.today().addDays(30),
            CurrencyIsoCode                = 'INR',
            ContactId                      = con.Id,
            BillingStreet                  = '100 Billing Rd',
            BillingCity                    = 'Kolkata',
            BillingPostalCode              = '700001',
            BillingCountry                 = 'India',
            BillingCountryCode             = 'IN',
            DRC_NBC_Shipping_Address_Id__c = queriedAddr.Id
        );

        Test.startTest();
        String result = DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prod.Id, pbe.Id, 1, 100, '50KG', '20')
            }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   DRC_NBC_Shipping_Address_Id__c != null AND
     *   addrRecord.DRC_NBC_Address__c == null → shipping field assignment SKIPPED
     *   String.isBlank(quoteData.BillingStreet) → TRUE → billing fallback executes
     *   PBE map populated, QLI insert succeeds
     */
    @isTest
    static void testCreateQuote_ShippingAddressNoCompound_BillingFallback() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Account acc     = [SELECT Id FROM Account LIMIT 1];
        Product2 prod   = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry
                              WHERE Product2Id = :prod.Id
                              AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];

        // Address with NO sub-fields → DRC_NBC_Address__c (compound) == null
        DRC_NBC_Addresses__c addrNoCompound = new DRC_NBC_Addresses__c(
            DRC_NBC_Account__c   = acc.Id,
            DRC_NBC_Type__c      = 'Shipping',
            DRC_NBC_Warehouse__c = 'CFS - JNPT'
        );
        insert addrNoCompound;

        Quote quote = new Quote(
            Name                           = 'No Compound Addr Quote',
            ExpirationDate                 = Date.today().addDays(30),
            CurrencyIsoCode                = 'INR',
            ContactId                      = con.Id,
            DRC_NBC_Shipping_Address_Id__c = addrNoCompound.Id
            // No BillingStreet → billing fallback also fires
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prod.Id, pbe.Id, 1, 100, null, null)
            }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   DRC_NBC_Shipping_Address_Id__c == null → shipping block entirely skipped
     *   String.isBlank(quoteData.BillingStreet) → FALSE → billing fallback SKIPPED
     *   productIdToPriceBookEntryId map populated (multiple products → loop > 1 iteration)
     *   wrapper.PackingSize blank → packing size if-branch NOT taken
     *   wrapper.PackingQuantity blank → packing qty if-branch NOT taken
     *   realQuoteLineItems insert with multiple items → success
     */
    @isTest
    static void testCreateQuote_ExplicitBilling_NoShipping_MultipleProducts() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Product2 prod1  = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        Product2 prod2  = [SELECT Id FROM Product2 WHERE Name = 'Test Product 2' LIMIT 1];
        PricebookEntry pbe1 = [SELECT Id FROM PricebookEntry
                               WHERE Product2Id = :prod1.Id
                               AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];
        PricebookEntry pbe2 = [SELECT Id FROM PricebookEntry
                               WHERE Product2Id = :prod2.Id
                               AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];

        Quote quote = new Quote(
            Name               = 'Multi Product Explicit Billing',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '2 Multi St',
            BillingCity        = 'Chennai',
            BillingPostalCode  = '600001',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prod1.Id, pbe1.Id, 2, 100, null, null),
                makeItem(prod2.Id, pbe2.Id, 3, 200, null, null)
            }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   wrapper.Quantity == 0 → defaults to 1
     *   wrapper.UnitPrice == null → defaults to 0
     *   wrapper.PackingSize not blank + wrapper.PackingQuantity not blank
     *     → both qli fields assigned
     */
    @isTest
    static void testCreateQuote_ZeroQty_NullPrice_BothPackingFields() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Product2 prod   = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry
                              WHERE Product2Id = :prod.Id
                              AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];

        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper item =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        item.Product2Id       = prod.Id;
        item.PricebookEntryId = pbe.Id;
        item.Quantity         = 0;      // → defaults to 1
        item.UnitPrice        = null;   // → defaults to 0
        item.PackingSize      = '25KG'; // → assigned
        item.PackingQuantity  = '40';   // → assigned

        Quote quote = new Quote(
            Name               = 'Zero Qty Null Price Packing',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '3 Zero St',
            BillingCity        = 'Delhi',
            BillingPostalCode  = '110001',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{ item }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   pbEntryId == null AND wrapper.PricebookEntryId != null
     *   → fallback PBE from LWC wrapper used (debug log line fires)
     */
    @isTest
    static void testCreateQuote_FallbackPBEFromWrapper() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];

        // New product with a DRC PBE – but we pass a product Id that won't be found
        // in productIdToPriceBookEntryId (because we query by Pricebook2Id=DRC and
        // CurrencyIsoCode=INR, but this new product will match).
        // Simplest approach: use a product that IS in DRC pricebook so the fallback
        // path fires when we deliberately omit it from the map by passing a
        // PricebookEntryId on the wrapper directly for a product that resolves via map.
        // Instead: create a product with NO DRC PBE but supply PBE Id on wrapper.
        Product2 prodNoMap = new Product2(Name = 'Fallback LWC Product', IsActive = true);
        insert prodNoMap;
        insert new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id   = prodNoMap.Id,
            UnitPrice    = 50, IsActive = true
        );
        PricebookEntry drcPbe = new PricebookEntry(
            Pricebook2Id     = [SELECT Id FROM Pricebook2 WHERE Name='DRC PriceBook' LIMIT 1].Id,
            Product2Id       = prodNoMap.Id,
            UnitPrice        = 50, IsActive = true,
            UseStandardPrice = false, CurrencyIsoCode = 'INR'
        );
        insert drcPbe;

        Quote quote = new Quote(
            Name               = 'Fallback PBE Quote',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '4 Fallback St',
            BillingCity        = 'Pune',
            BillingPostalCode  = '411002',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prodNoMap.Id, drcPbe.Id, 1, 50, null, null)
            }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   pbEntryId == null AND wrapper.PricebookEntryId == null AND
     *   productIdToName.get() returns a known name
     *   → product name added to missingPricebookProducts
     *   → rollback + 'Missing PricebookEntries for: …'
     */
    @isTest
    static void testCreateQuote_MissingPBE_KnownProductName() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];

        Product2 prodNoPBE = new Product2(Name = 'No DRC PBE Product', IsActive = true);
        insert prodNoPBE;
        insert new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id   = prodNoPBE.Id,
            UnitPrice    = 50, IsActive = true
        );

        Quote quote = new Quote(
            Name               = 'Missing PBE Quote',
            ExpirationDate     = Date.today().addDays(10),
            ContactId          = con.Id,
            CurrencyIsoCode    = 'INR',
            BillingStreet      = '5 Bad St',
            BillingCity        = 'Chennai',
            BillingPostalCode  = '600002',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );
        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                makeItem(prodNoPBE.Id, null, 1, 10, null, null)
            }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   pbEntryId == null AND wrapper.PricebookEntryId == null AND
     *   productIdToName.get() returns null (fake Id not in org)
     *   → 'Unknown Product' fallback added to missingPricebookProducts
     */
    @isTest
    static void testCreateQuote_MissingPBE_UnknownProductName() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];

        Quote quote = new Quote(
            Name               = 'Unknown Product Test',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '6 Unknown St',
            BillingCity        = 'Bengaluru',
            BillingPostalCode  = '560002',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );

        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper item =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        item.Product2Id       = '01t000000000001AAA'; // not in org → map returns null
        item.PricebookEntryId = null;
        item.Quantity         = 1;
        item.UnitPrice        = 10;

        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{ item }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   wrapper.Product2Id == null → `continue` on every item
     *   missingPricebookProducts empty
     *   realQuoteLineItems.isEmpty() → rollback + 'No valid products'
     */
    @isTest
    static void testCreateQuote_AllNullProduct2Ids_EmptyQLIList() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];

        Quote quote = new Quote(
            Name               = 'All Null Product2Id Test',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '7 Null St',
            BillingCity        = 'Mumbai',
            BillingPostalCode  = '400003',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );

        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper nullItem =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        nullItem.Product2Id = null;
        nullItem.Quantity   = 1;
        nullItem.UnitPrice  = 50;

        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{ nullItem }
        );
        Test.stopTest();
    }

    /**
     * Covers:
     *   first wrapper has null Product2Id → `continue`
     *   second wrapper valid → processed normally → success
     */
    @isTest
    static void testCreateQuote_MixedNullAndValidProduct2Ids() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contact con     = [SELECT Id FROM Contact WHERE Email != null LIMIT 1];
        Product2 prod   = [SELECT Id FROM Product2 WHERE Name = 'Test Product 1' LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry
                              WHERE Product2Id = :prod.Id
                              AND Pricebook2.Name = 'DRC PriceBook' LIMIT 1];

        Quote quote = new Quote(
            Name               = 'Mixed Quote',
            ExpirationDate     = Date.today().addDays(30),
            CurrencyIsoCode    = 'INR',
            ContactId          = con.Id,
            BillingStreet      = '8 Mixed St',
            BillingCity        = 'Pune',
            BillingPostalCode  = '411003',
            BillingCountry     = 'India',
            BillingCountryCode = 'IN'
        );

        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper nullItem =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        nullItem.Product2Id = null;
        nullItem.Quantity   = 1;
        nullItem.UnitPrice  = 0;

        Test.startTest();
        DRC_NBC_GenerateQuotes_Controller.createQuoteWithLines(
            opp.Id, quote,
            new List<DRC_NBC_GenerateQuotes_Controller.LineItemWrapper>{
                nullItem,
                makeItem(prod.Id, pbe.Id, 1, 100, null, null)
            }
        );
        Test.stopTest();
    }

    // ─── Inner class constructors ─────────────────────────────────────────────

    @isTest
    static void testInnerClassConstructors() {
        Test.startTest();

        DRC_NBC_GenerateQuotes_Controller.QuoteWrapper qw =
            new DRC_NBC_GenerateQuotes_Controller.QuoteWrapper();
        qw.oppCurrency = 'USD';
        qw.accountSpecialInstruction = 'Fragile';

        DRC_NBC_GenerateQuotes_Controller.AccountAddressWrapper aw =
            new DRC_NBC_GenerateQuotes_Controller.AccountAddressWrapper(
                'Street', 'City', 'State', '123456', 'Country', 'CC'
            );

        DRC_NBC_GenerateQuotes_Controller.PackingDetailWrapper pdw =
            new DRC_NBC_GenerateQuotes_Controller.PackingDetailWrapper('25KG', '40');

        List<DRC_NBC_GenerateQuotes_Controller.PackingDetailWrapper> packingList =
            new List<DRC_NBC_GenerateQuotes_Controller.PackingDetailWrapper>{ pdw };

        DRC_NBC_GenerateQuotes_Controller.ProductWrapper pw =
            new DRC_NBC_GenerateQuotes_Controller.ProductWrapper(
                null, null, 'My Product', 99.00, 'FG001', 'HSN001', 'KGS', packingList
            );

        DRC_NBC_GenerateQuotes_Controller.LineItemWrapper li =
            new DRC_NBC_GenerateQuotes_Controller.LineItemWrapper();
        li.PackingSize     = '50KG';
        li.PackingQuantity = '20';

        Test.stopTest();
    }
}