force-app/main/default/objects/Account/fields/DRC_NBC_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/DRC_NBC_Addresses__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>NO.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Order__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_Addresses__c/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/DRC_NBC_BC_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BC Integration</label>
</CustomObject>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_BC_ShipTo_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_BC_ShipTo_Endpoint__c</fullName>
    <label>DRC_NBC_BC_ShipTo_Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Password__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Password__c</fullName>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_SOAP_Order_Namespace__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_SOAP_Order_Namespace__c</fullName>
    <label>SOAP Order Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DRC_NBC_BC_Integration__c/fields/DRC_NBC_Username__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Shipping_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address Id</label>
    <referenceTo>DRC_NBC_Addresses__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/DRC_NBC_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>DRC_NBC_Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTHER COUNTRY</fullName>
            </value>
            <value>
                <fullName>Andheri Air Port</fullName>
            </value>
            <value>
                <fullName>ARSHIYA LOGISTICS SERVICES LIMITED</fullName>
            </value>
            <value>
                <fullName>C4/2/2 D.R COATS INK &amp; RESINS PVT LTD (UNIT-III)</fullName>
            </value>
            <value>
                <fullName>CFS - JNPT</fullName>
            </value>
            <value>
                <fullName>Commercial Sample</fullName>
            </value>
            <value>
                <fullName>DARSHAN CHEMICALS</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (GUJ)</fullName>
            </value>
            <value>
                <fullName>E-123</fullName>
            </value>
            <value>
                <fullName>EXBHIWANDI TRANSPORTERS WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>GATIK SYNTHESIS LLP</fullName>
            </value>
            <value>
                <fullName>D R Coats Ink and Resins Pvt Ltd (GUJ)</fullName>
            </value>
            <value>
                <fullName>Plot No.H-4/2-B</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
            <value>
                <fullName>IN TANSIT</fullName>
            </value>
            <value>
                <fullName>D.R COATS INK &amp; RESINS PVT LTD (UNIT-II)</fullName>
            </value>
            <value>
                <fullName>K-34</fullName>
            </value>
            <value>
                <fullName>PAONA CHEMPRO P LTD</fullName>
            </value>
            <value>
                <fullName>NHAVA SEVA PORT</fullName>
            </value>
            <value>
                <fullName>Production Sample</fullName>
            </value>
            <value>
                <fullName>Quality Control</fullName>
            </value>
            <value>
                <fullName>Rejection - RM &amp; FG</fullName>
            </value>
            <value>
                <fullName>Research &amp; development</fullName>
            </value>
            <value>
                <fullName>SAI SON RESINS AND CHEMICALS</fullName>
            </value>
            <value>
                <fullName>TARAPUR</fullName>
            </value>
            <value>
                <fullName>Vapi - Job Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DRC_NBC_UpdateShippingAddressTest.cls
/**
* @File Name : DRC_NBC_UpdateShippingAddressTest.cls
* @Description : Test class for DRC_NBC_UpdateShippingAddress
*                Covers all branches: SUCCESS, SKIPPED, ERROR, READ failure,
*                Location_Code match/mismatch, missing fields, HTTP failures
* @Author : Satish YADAV
* @Last Modified On : February 19, 2026
**/
@isTest
private class DRC_NBC_UpdateShippingAddressTest {
    
    private static void setupCustomSetting(String shipToEndpoint) {
        DRC_NBC_BC_Integration__c settings = new DRC_NBC_BC_Integration__c(
            SetupOwnerId                    = UserInfo.getOrganizationId(),
            DRC_NBC_BC_ShipTo_Endpoint__c   = shipToEndpoint,
            DRC_NBC_SOAP_Order_Namespace__c  = 'urn:microsoft-dynamics-schemas/page/customershiptoaddresssalesforce',
            DRC_NBC_Username__c             = 'testuser',
            DRC_NBC_Password__c             = 'testpass'
        );
        insert settings;
    }
    
    private static Account createAccount(String customerNo) {
        Account acc = new Account(
            Name                        = 'Test Account',
            DRC_NBC_Customer_Number__c  = customerNo
        );
        insert acc;
        return acc;
    }
    
    private static DRC_NBC_Addresses__c createShippingAddress(Id accountId, String shipToCode, String warehouse) {
        DRC_NBC_Addresses__c addr = new DRC_NBC_Addresses__c(
            DRC_NBC_Ship_To_Code__c         = shipToCode,
            DRC_NBC_Address__Street__s      = 'Unit 501, EON Free Zone Tower 2',
            DRC_NBC_Address__City__s        = 'Pune',
            DRC_NBC_Address__PostalCode__s  = '411014',
            DRC_NBC_Address__CountryCode__s = 'IN',
            DRC_NBC_Address__StateCode__s   = 'MH',
            DRC_NBC_Warehouse__c            = warehouse,
            DRC_NBC_Order__c                = null  // set after order creation if needed
        );
        insert addr;
        return addr;
    }
    
    private static Order createOrder(Id accountId, Id shippingAddressId, String warehouse) {
        Order ord = new Order(
            AccountId                       = accountId,
            Status                          = 'Draft',
            EffectiveDate                   = Date.today(),
            DRC_NBC_Shipping_Address__c     = shippingAddressId,
            DRC_NBC_Warehouse__c            = warehouse
        );
        insert ord;
        return ord;
    }
    
    private static String buildReadSuccessResponse(String key, String locationCode) {
        return
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
            '<soap:Body>' +
            '<Read_Result xmlns="urn:microsoft-dynamics-schemas/page/customershiptoaddresssalesforce">' +
            '<CustomerShiptoAddressSalesForce>' +
            '<Key>' + key + '</Key>' +
            '<CustomerNo>CUST001</CustomerNo>' +
            '<ShiptoCode>SF-123519</ShiptoCode>' +
            '<Name>Test Shipping Address</Name>' +
            '<Location_Code>' + locationCode + '</Location_Code>' +
            '</CustomerShiptoAddressSalesForce>' +
            '</Read_Result>' +
            '</soap:Body>' +
            '</soap:Envelope>';
    }
    
    private static String buildUpdateSuccessResponse() {
        return
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
            '<soap:Body>' +
            '<Update_Result xmlns="urn:microsoft-dynamics-schemas/page/customershiptoaddresssalesforce">' +
            '<CustomerShiptoAddressSalesForce>' +
            '<Key>testkey123==</Key>' +
            '</CustomerShiptoAddressSalesForce>' +
            '</Update_Result>' +
            '</soap:Body>' +
            '</soap:Envelope>';
    }
    
    private class ShipToMock implements HttpCalloutMock {
        private Integer readStatusCode;
        private String  readBody;
        private Integer updateStatusCode;
        private String  updateBody;
        private Integer callCount = 0;
        
        public ShipToMock(Integer readStatus, String readBody,
                          Integer updateStatus, String updateBody) {
                              this.readStatusCode   = readStatus;
                              this.readBody         = readBody;
                              this.updateStatusCode = updateStatus;
                              this.updateBody       = updateBody;
                          }
        
        public HttpResponse respond(HttpRequest req) {
            callCount++;
            HttpResponse res = new HttpResponse();
            
            // First call = Read, Second call = Update
            if (callCount == 1) {
                res.setStatusCode(readStatusCode);
                res.setBody(readBody);
            } else {
                res.setStatusCode(updateStatusCode);
                res.setBody(updateBody);
            }
            return res;
        }
    }
    
    private class SingleCallMock implements HttpCalloutMock {
        private Integer statusCode;
        private String  body;
        
        public SingleCallMock(Integer statusCode, String body) {
            this.statusCode = statusCode;
            this.body       = body;
        }
        
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(statusCode);
            res.setBody(body);
            return res;
        }
    }
    
    @isTest
    static void testSyncSuccess_LocationCodeChanged() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc   = createAccount('CUST001');
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, 'SF-123519', 'Andheri Air Port');
        Order ord     = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        // BC returns OLD location code (different from SF resolved code)
        String readResp   = buildReadSuccessResponse('bckey==', 'OLD_LOC');
        String updateResp = buildUpdateSuccessResponse();
        
        Test.setMock(HttpCalloutMock.class, new ShipToMock(200, readResp, 200, updateResp));
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
    
    @isTest
    static void testSyncSkipped_LocationCodeUnchanged() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc   = createAccount('CUST001');
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, 'SF-123519', 'Andheri Air Port');
        Order ord     = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        String readResp = buildReadSuccessResponse('bckey==', '');
        
        Test.setMock(HttpCalloutMock.class, new SingleCallMock(200, readResp));
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testSyncSkipped_NoShippingAddress() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc = createAccount('CUST001');
        Order ord = new Order(
            AccountId     = acc.Id,
            Status        = 'Draft',
            EffectiveDate = Date.today()
        );
        insert ord;
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    @isTest
    static void testSyncSkipped_BlankCustomerNumber() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc = new Account(Name = 'No Cust No Account');
        insert acc;
        
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, 'SF-123519', 'Andheri Air Port');
        Order ord = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testSyncSkipped_BlankShipToCode() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc = createAccount('CUST001');
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, null, 'Andheri Air Port'); // No ShipToCode
        Order ord = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testSyncError_BCReadReturns200WithNoKey() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc   = createAccount('CUST001');
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, 'SF-123519', 'Andheri Air Port');
        Order ord     = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        // Valid XML but missing Key element in response
        String emptyReadResp =
            '<?xml version="1.0" encoding="utf-8"?>' +
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
            '<soap:Body>' +
            '<Read_Result xmlns="urn:microsoft-dynamics-schemas/page/customershiptoaddresssalesforce">' +
            '</Read_Result>' +
            '</soap:Body>' +
            '</soap:Envelope>';
        
        Test.setMock(HttpCalloutMock.class, new SingleCallMock(200, emptyReadResp));
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testSyncError_BCReadReturnsMalformedXML() {
        setupCustomSetting('https://bc.example.com/ShipTo');
        Account acc   = createAccount('CUST001');
        DRC_NBC_Addresses__c addr = createShippingAddress(acc.Id, 'SF-123519', 'Andheri Air Port');
        Order ord     = createOrder(acc.Id, addr.Id, 'Andheri Air Port');
        
        Test.setMock(HttpCalloutMock.class, new SingleCallMock(200, 'not xml at all %%$$'));
        
        Test.startTest();
        String result = DRC_NBC_UpdateShippingAddress.syncShippingAddress(ord.Id);
        Test.stopTest();
    }
    
}